# Problem

- data does not contain year
- needs cleaning

### Solution

- Create function that does:
    1. create a column for given year
    2. create a full_year column that appends date and year column
    3. convert full_year column to datetime
    4. split result column with two colums given score of each team
    5. organize dataframe
    6. create winner column based on score of teams
    7. set and sort index to full_date column 

-  dataframes will be loaded one at a time given year

In [8]:
import pandas as pd
import numpy as np
import glob, os
import warnings
warnings.filterwarnings('ignore')

In [1]:
ls data/MLS/HOU/reg/

HOU_10.csv*  HOU_12.csv*  HOU_14.csv*  HOU_16.csv*
HOU_11.csv*  HOU_13.csv*  HOU_15.csv*  HOU_17.csv*

In [2]:

h10 = 'data//MLS/HOU/reg/HOU_10.csv'
h11 = 'data/MLS/HOU/reg/HOU_11.csv'
h12 = 'data/MLS/HOU/reg/HOU_12.csv'
h13 = 'data/MLS/HOU/reg/HOU_13.csv'
h14 = 'data/MLS/HOU/reg/HOU_14.csv'
h15 = 'data/MLS/HOU/reg/HOU_15.csv'
h16 = 'data/MLS/HOU/reg/HOU_16.csv'
h17 = 'data/MLS/HOU/reg/HOU_17.csv'

## create dataframes per year

In [5]:
df10 = pd.read_csv(h10)
df11 = pd.read_csv(h11)
df12 = pd.read_csv(h12)
df13 = pd.read_csv(h13)
df14 = pd.read_csv(h14)
df15 = pd.read_csv(h15)
df16 = pd.read_csv(h16)
df17 = pd.read_csv(h17)

## Create function
- joins dfs

In [6]:
def cleanup(df,year):
    '''function that clean up dataframe'''
    df['year'] = year  # create col with var year
    df['full_date'] = df['date'] + ' ' + df['year']  # append date and year cols
    df['full_date'] =  pd.to_datetime(df['full_date'])  # convert full_date to datetime
    df['home_score']= df['result'].str.split('-').apply(lambda x: x[0])  # split score vals
    df['away_score']= df['result'].str.split('-').apply(lambda x: x[1])  # split score vals
    df = df[['full_date','home_team','home_score','away_team','away_score']]  # org df
    # winner cols given value scores
    df['winner'] = np.where(df['home_score'] > df['away_score'], df['home_team'], df['away_team']) 
    df = df.set_index('full_date').sort_index(ascending=True)  # set full_date as index
    return df

In [9]:

dy_10 = cleanup(df10,'2010')
dy_11 = cleanup(df11,'2011')
dy_12 = cleanup(df12,'2012')
dy_13 = cleanup(df13,'2013')
dy_14 = cleanup(df14,'2014')
dy_15 = cleanup(df15,'2015')
dy_16 = cleanup(df16,'2016')
dy_17 = cleanup(df17,'2017')

In [10]:
dy_10

,home_team,home_score,away_team,away_score,winner
full_date,,,,,
2010-03-27,FC Dallas,1,HOU,1,HOU
2010-04-01,HOU,2,Real Salt Lake,1,HOU
2010-04-10,HOU,0,LA Galaxy,2,LA Galaxy
2010-04-17,HOU,3,Chivas USA,0,HOU
2010-04-24,Chicago,2,HOU,0,Chicago
2010-05-01,HOU,3,Sporting KC,0,HOU
2010-05-05,HOU,0,FC Dallas,1,FC Dallas
2010-05-08,Chivas USA,0,HOU,2,HOU
2010-05-13,Real Salt Lake,3,HOU,1,Real Salt Lake
2010-05-22,HOU,2,D.C. United,0,HOU
2010-05-29,HOU,2,Philadelphia,3,Philadelphia
2010-06-02,NY Red Bulls,2,HOU,1,NY Red Bulls
2010-06-05,LA Galaxy,4,HOU,1,LA Galaxy
2010-06-26,HOU,2,Colorado,2,Colorado
2010-07-01,Toronto FC,1,HOU,1,HOU
2010-07-10,HOU,0,Columbus,0,Columbus
2010-07-24,Columbus,3,HOU,0,Columbus
2010-07-31,HOU,2,NY Red Bulls,2,NY Red Bulls
2010-08-08,Seattle,2,HOU,0,Seattle
2010-08-14,New England,1,HOU,0,New England
2010-08-21,HOU,4,Chicago,3,HOU
2010-08-28,Colorado,3,HOU,0,Colorado
2010-09-05,HOU,1,San Jose,2,San Jose
2010-09-18,HOU,1,Toronto FC,2,Toronto FC
2010-09-22,Sporting KC,4,HOU,3,Sporting KC
2010-09-25,D.C. United,1,HOU,3,HOU
2010-10-02,Philadelphia,1,HOU,1,HOU
2010-10-10,HOU,1,New England,2,New England
2010-10-16,San Jose,0,HOU,1,HOU
2010-10-23,Seattle,2,HOU,1,Seattle

## combine df
2010 - 2017

In [11]:
frames = [dy_10,dy_11,dy_12,dy_13,
          dy_14,dy_15,dy_16,dy_17]

dynamo10_17 = pd.concat(frames)

In [12]:
dynamo10_17.head()

            home_team home_score       away_team away_score     winner
full_date
2010-03-27  FC Dallas          1             HOU          1        HOU
2010-04-01        HOU          2  Real Salt Lake          1        HOU
2010-04-10        HOU          0       LA Galaxy          2  LA Galaxy
2010-04-17        HOU          3      Chivas USA          0        HOU
2010-04-24    Chicago          2             HOU          0    Chicago

In [13]:
dynamo10_17.apply(lambda x: sum(x.isnull()))

home_team     0
home_score    0
away_team     0
away_score    0
winner        0
dtype: int64

## create a season col

In [14]:
dynamo10_17['season'] = 'reg'

# cleanup cols

In [17]:
len(dynamo10_17.home_team.unique())

23

In [19]:
dynamo10_17.home_team.unique()

array(['FC Dallas', 'HOU', 'Chicago', 'Chivas USA', 'Real Salt Lake',
       'NY Red Bulls', 'LA Galaxy', 'Toronto FC', 'Columbus', 'Seattle',
       'New England', 'Colorado', 'Sporting KC', 'D.C. United',
       'Philadelphia', 'San Jose', 'Vancouver', 'Portland', 'Montreal',
       'NYCFC', 'Orlando', 'Atlanta', 'Minnesota'], dtype=object)

In [22]:
dynamo10_17.home_team = dynamo10_17.home_team.str.strip()

In [23]:
len(dynamo10_17.home_team.unique())

23

In [24]:
len(dynamo10_17.away_team.unique())

22

In [25]:
dynamo10_17.away_team.unique()

array(['HOU', 'Real Salt Lake', 'LA Galaxy', 'Chivas USA', 'Sporting KC',
       'FC Dallas', 'D.C. United', 'Philadelphia', 'Colorado', 'Columbus',
       'NY Red Bulls', 'Chicago', 'San Jose', 'Toronto FC', 'New England',
       'Vancouver', 'Portland', 'Montreal', 'Orlando', 'NYCFC', 'Seattle',
       'Minnesota'], dtype=object)

In [26]:
dynamo10_17.away_team = dynamo10_17.away_team.str.strip()

In [27]:
len(dynamo10_17.away_team.unique())

22

## Change home team col name

In [30]:
dynamo10_17.home_team.replace( 'HOU', 'Houston Dynamo', inplace=True)
dynamo10_17

,home_team,home_score,away_team,away_score,winner,season
full_date,,,,,,
2010-03-27,FC Dallas,1,HOU,1,HOU,reg
2010-04-01,Houston Dynamo,2,Real Salt Lake,1,HOU,reg
2010-04-10,Houston Dynamo,0,LA Galaxy,2,LA Galaxy,reg
2010-04-17,Houston Dynamo,3,Chivas USA,0,HOU,reg
2010-04-24,Chicago,2,HOU,0,Chicago,reg
2010-05-01,Houston Dynamo,3,Sporting KC,0,HOU,reg
2010-05-05,Houston Dynamo,0,FC Dallas,1,FC Dallas,reg
2010-05-08,Chivas USA,0,HOU,2,HOU,reg
2010-05-13,Real Salt Lake,3,HOU,1,Real Salt Lake,reg
2010-05-22,Houston Dynamo,2,D.C. United,0,HOU,reg
2010-05-29,Houston Dynamo,2,Philadelphia,3,Philadelphia,reg
2010-06-02,NY Red Bulls,2,HOU,1,NY Red Bulls,reg
2010-06-05,LA Galaxy,4,HOU,1,LA Galaxy,reg
2010-06-26,Houston Dynamo,2,Colorado,2,Colorado,reg
2010-07-01,Toronto FC,1,HOU,1,HOU,reg
2010-07-10,Houston Dynamo,0,Columbus,0,Columbus,reg
2010-07-24,Columbus,3,HOU,0,Columbus,reg
2010-07-31,Houston Dynamo,2,NY Red Bulls,2,NY Red Bulls,reg
2010-08-08,Seattle,2,HOU,0,Seattle,reg
2010-08-14,New England,1,HOU,0,New England,reg
2010-08-21,Houston Dynamo,4,Chicago,3,HOU,reg
2010-08-28,Colorado,3,HOU,0,Colorado,reg
2010-09-05,Houston Dynamo,1,San Jose,2,San Jose,reg
2010-09-18,Houston Dynamo,1,Toronto FC,2,Toronto FC,reg
2010-09-22,Sporting KC,4,HOU,3,Sporting KC,reg
2010-09-25,D.C. United,1,HOU,3,HOU,reg
2010-10-02,Philadelphia,1,HOU,1,HOU,reg
2010-10-10,Houston Dynamo,1,New England,2,New England,reg
2010-10-16,San Jose,0,HOU,1,HOU,reg
2010-10-23,Seattle,2,HOU,1,Seattle,reg
...,...,...,...,...,...,...
2017-04-08,New England,2,HOU,0,New England,reg
2017-04-15,Houston Dynamo,2,Minnesota,2,Minnesota,reg
2017-04-22,Houston Dynamo,2,San Jose,0,HOU,reg
2017-04-28,Toronto FC,2,HOU,0,Toronto FC,reg
2017-05-06,Houston Dynamo,4,Orlando,0,HOU,reg
2017-05-12,Houston Dynamo,2,Vancouver,1,HOU,reg
2017-05-17,Philadelphia,2,HOU,0,Philadelphia,reg
2017-05-20,Atlanta,4,HOU,1,Atlanta,reg
2017-05-28,FC Dallas,0,HOU,0,HOU,reg
2017-05-31,Houston Dynamo,5,Real Salt Lake,1,HOU,reg
2017-06-04,Seattle,1,HOU,0,Seattle,reg
2017-06-17,LA Galaxy,2,HOU,2,HOU,reg
2017-06-23,Houston Dynamo,1,FC Dallas,1,FC Dallas,reg
2017-07-01,Colorado,3,HOU,1,Colorado,reg
2017-07-05,Houston Dynamo,3,Montreal,1,HOU,reg
2017-07-19,Minnesota,0,HOU,0,HOU,reg
2017-07-22,D.C. United,1,HOU,3,HOU,reg
2017-07-29,Houston Dynamo,2,Portland,2,Portland,reg
2017-08-05,Real Salt Lake,0,HOU,0,HOU,reg
2017-08-12,Houston Dynamo,3,San Jose,0,HOU,reg
2017-08-19,Vancouver,2,HOU,1,Vancouver,reg
2017-08-23,FC Dallas,3,HOU,3,HOU,reg
2017-09-09,Houston Dynamo,0,Colorado,1,Colorado,reg
2017-09-16,San Jose,1,HOU,0,San Jose,reg
2017-09-23,NYCFC,1,HOU,1,HOU,reg
2017-09-27,Houston Dynamo,3,LA Galaxy,3,LA Galaxy,reg
2017-09-30,Houston Dynamo,2,Minnesota,1,HOU,reg
2017-10-11,Houston Dynamo,2,Sporting KC,1,HOU,reg
2017-10-15,Sporting KC,0,HOU,0,HOU,reg
2017-10-22,Houston Dynamo,3,Chicago,0,HOU,reg

## Save

In [31]:
dynamo10_17.to_csv('data/clean/dynamo_reg.csv')

In [32]:
ls data/clean

astros_clean.csv*      astros_clean_reg.csv*  dynamo_reg.csv*  UH_clean.csv*
astros_clean_plo.csv*  dynamo_plo.csv*        Rice_clean.csv*