In [1]:
import pandas as pd
import numpy as np

In [2]:
ls data/sports_scores/

astros_1A10.csv*   Rice_10H80.csv*    Tex_15E40.csv*
dynamo_10H30.csv*  rockets_1A10.csv*  UH_10H50.csv*

In [3]:
ls data/crime_beats/

crime_10H30_10_17.csv*  crime_10H80_10_17.csv*  crime_1A10_10_17.csv*
crime_10H50_10_17.csv*  crime_15E40_10_17.csv*

In [4]:
games = 'data/sports_scores/astros_1A10.csv'

In [5]:
crime = 'data/crime_beats/crime_1A10_10_17.csv'

In [9]:
df = pd.read_csv(games,index_col='date')
crime_df = pd.read_csv(crime,index_col='Date')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 658 entries, 2015-10-11 to 2017-09-24
Data columns (total 8 columns):
Unnamed: 0    658 non-null int64
team          658 non-null object
team_score    658 non-null int64
home_away     658 non-null object
opposing      658 non-null object
opp_score     658 non-null int64
season        658 non-null object
beat          658 non-null object
dtypes: int64(3), object(5)
memory usage: 46.3+ KB

In [14]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15329 entries, 1971-02-03 to 2017-12-31
Data columns (total 11 columns):
Beat           15329 non-null object
BlockRange     15329 non-null object
StreetName     15329 non-null object
OffenseType    15329 non-null object
Premise        15329 non-null object
NumOffenses    15329 non-null float64
Hour           15329 non-null float64
day            15329 non-null int64
weekday        15329 non-null object
month          15329 non-null object
year           15329 non-null int64
dtypes: float64(2), int64(2), object(7)
memory usage: 1.4+ MB

In [16]:
df.head()

,Unnamed: 0,team,team_score,home_away,opposing,opp_score,season,beat
date,,,,,,,,
2015-10-11,3,Houston,4,HOME,Kansas City,2,plo,1A10
2015-10-12,4,Houston,6,HOME,Kansas City,9,plo,1A10
2017-10-06,7,Houston,8,HOME,Boston,2,plo,1A10
2017-10-13,10,Houston,2,HOME,New York,1,plo,1A10
2017-10-14,11,Houston,2,HOME,New York,1,plo,1A10

In [17]:
df['win'] =  np.where(df['team_score'] > df['opp_score'],1,0)

In [18]:
df.head()

,Unnamed: 0,team,team_score,home_away,opposing,opp_score,season,beat,win
date,,,,,,,,,
2015-10-11,3,Houston,4,HOME,Kansas City,2,plo,1A10,1
2015-10-12,4,Houston,6,HOME,Kansas City,9,plo,1A10,0
2017-10-06,7,Houston,8,HOME,Boston,2,plo,1A10,1
2017-10-13,10,Houston,2,HOME,New York,1,plo,1A10,1
2017-10-14,11,Houston,2,HOME,New York,1,plo,1A10,1

In [19]:
df = df[['opposing','win']]

In [20]:
crime_df = crime_df.iloc[2010:]  # data from 2010- 2017

In [21]:
crime_df = crime_df[['OffenseType','Premise','NumOffenses','Hour','weekday']]

In [23]:
df.head()

               opposing  win
date
2015-10-11  Kansas City    1
2015-10-12  Kansas City    0
2017-10-06       Boston    1
2017-10-13     New York    1
2017-10-14     New York    1

## merge

In [24]:
merge = pd.merge(df,crime_df, how='inner', left_index=True, right_index=True)

In [25]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3277 entries, 2011-04-08 to 2017-10-29
Data columns (total 7 columns):
opposing       3277 non-null object
win            3277 non-null int64
OffenseType    3277 non-null object
Premise        3277 non-null object
NumOffenses    3277 non-null float64
Hour           3277 non-null float64
weekday        3277 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 204.8+ KB

In [28]:
merge

,opposing,win,OffenseType,Premise,NumOffenses,Hour,weekday
2011-04-08,FLA,0,Theft,BUS STOP,1.0,13.0,Friday
2011-04-08,FLA,0,Aggravated Assault,ROAD/STREET/SIDEWALK,1.0,17.0,Friday
2011-04-08,FLA,0,Theft,ROAD/STREET/SIDEWALK,1.0,2.0,Friday
2011-04-08,FLA,0,Theft,ROAD/STREET/SIDEWALK,1.0,20.0,Friday
2011-04-08,FLA,0,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,16.0,Friday
2011-04-08,FLA,0,Aggravated Assault,STADIUM/SPRTS ARENA/RACE TRACK,1.0,3.0,Friday
2011-04-08,FLA,0,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,17.0,Friday
2011-04-08,FLA,0,Theft,HOTEL/MOTEL/ETC.,1.0,15.0,Friday
2011-04-09,FLA,0,Theft,BAR/NIGHT CLUB,1.0,0.0,Saturday
2011-04-09,FLA,0,Theft,ROAD/STREET/SIDEWALK,1.0,7.0,Saturday
2011-04-09,FLA,0,Theft,"PARKS & RECREATION, ZOO, SWIM POOL",1.0,15.0,Saturday
2011-04-09,FLA,0,Auto Theft,ROAD/STREET/SIDEWALK,1.0,13.0,Saturday
2011-04-09,FLA,0,Auto Theft,BAR/NIGHT CLUB,1.0,1.0,Saturday
2011-04-09,FLA,0,Theft,OTHER PARKING LOT,1.0,18.0,Saturday
2011-04-10,FLA,1,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,17.0,Sunday
2011-04-11,CHC,0,Auto Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,17.0,Monday
2011-04-11,CHC,0,Theft,"LIBRARIES, MUSEUMS",1.0,19.0,Monday
2011-04-11,CHC,0,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,17.0,Monday
2011-04-11,CHC,0,Theft,ROAD/STREET/SIDEWALK,1.0,18.0,Monday
2011-04-11,CHC,0,Auto Theft,ROAD/STREET/SIDEWALK,1.0,17.0,Monday
2011-04-12,CHC,1,Theft,DEPARTMENT/DISCOUNT STORE,1.0,15.0,Tuesday
2011-04-12,CHC,1,Theft,COMMERCIAL BUILDING,1.0,14.0,Tuesday
2011-04-12,CHC,1,Robbery,ROAD/STREET/SIDEWALK,1.0,8.0,Tuesday
2011-04-12,CHC,1,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,22.0,Tuesday
2011-04-12,CHC,1,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,21.0,Tuesday
2011-04-12,CHC,1,Theft,OTHER/UNKNOWN,1.0,7.0,Tuesday
2011-04-12,CHC,1,Theft,ROAD/STREET/SIDEWALK,1.0,23.0,Tuesday
2011-04-12,CHC,1,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,10.0,Tuesday
2011-04-12,CHC,1,Theft,RESTAURANT/CAFETERIA PARKING LOT,1.0,21.0,Tuesday
2011-04-13,CHC,0,Theft,OFFICE BUILDING,1.0,16.0,Wednesday
...,...,...,...,...,...,...,...
2017-10-14,New York,1,Theft,Other Parking Lot,1.0,9.0,Saturday
2017-10-14,New York,1,Auto Theft,Other Parking Lot,1.0,14.0,Saturday
2017-10-20,New York,1,Theft,Condominium,1.0,16.0,Friday
2017-10-20,New York,1,Theft,Commercial Parking Lot or Garage,1.0,22.0,Friday
2017-10-20,New York,1,Robbery,"Road, Street, or Sidewalk",1.0,4.0,Friday
2017-10-20,New York,1,Aggravated Assault,"Road, Street, or Sidewalk",1.0,5.0,Friday
2017-10-20,New York,1,Theft,"Hotel, Motel, Inn, Etc.",1.0,7.0,Friday
2017-10-21,New York,1,Theft,Office Building,1.0,16.0,Saturday
2017-10-21,New York,1,Theft,Other Parking Lot,1.0,15.0,Saturday
2017-10-21,New York,1,Aggravated Assault,"Road, Street, or Sidewalk",1.0,0.0,Saturday
2017-10-21,New York,1,Theft,"Amusement Park, Bowling Alley, Skate Rink",1.0,19.0,Saturday
2017-10-21,New York,1,Theft,"Parks and Recreation, Zoo, Swimming Pool",1.0,2.0,Saturday
2017-10-27,Los Angeles,1,Theft,Restaurant or Cafeteria,1.0,10.0,Friday
2017-10-27,Los Angeles,1,Theft,Commercial Parking Lot or Garage,1.0,15.0,Friday
2017-10-27,Los Angeles,1,Theft,"Road, Street, or Sidewalk",1.0,10.0,Friday
2017-10-27,Los Angeles,1,Theft,Office Building,1.0,11.0,Friday
2017-10-27,Los Angeles,1,Theft,"Other, Unknown, or Not Listed",1.0,21.0,Friday
2017-10-27,Los Angeles,1,Burglary,Restaurant or Cafeteria Parking Lot,1.0,12.0,Friday
2017-10-27,Los Angeles,1,Theft,"Stadium, Sports Arena, Race Track",1.0,23.0,Friday
2017-10-28,Los Angeles,0,Theft,"Stadium, Sports Arena, Race Track",1.0,20.0,Saturday
2017-10-28,Los Angeles,0,Theft,"Stadium, Sports Arena, Race Track",1.0,21.0,Saturday
2017-10-28,Los Angeles,0,Theft,"Stadium, Sports Arena, Race Track",1.0,9.0,Saturday
2017-10-28,Los Angeles,0,Aggravated Assault,"Road, Street, or Sidewalk",1.0,1.0,Saturday
2017-10-28,Los Angeles,0,Theft,Bar or Night Club,1.0,16.0,Saturday
2017-10-28,Los Angeles,0,Theft,Commercial Parking Lot or Garage,1.0,14.0,Saturday
2017-10-28,Los Angeles,0,Theft,Bar or Night Club,1.0,15.0,Saturday
2017-10-29,Los Angeles,1,Theft,Light Rail (Metro Rail) Vehicle,1.0,3.0,Sunday
2017-10-29,Los Angeles,1,Aggravated Assault,Apartment,1.0,20.0,Sunday
2017-10-29,Los Angeles,1,Theft,"Road, Street, or Sidewalk",1.0,16.0,Sunday
2017-10-29,Los Angeles,1,Theft,"Road, Street, or Sidewalk",1.0,10.0,Sunday