In [4]:
import pandas as pd
import numpy as np

In [18]:
ls data/sports_scores/

astros_1A10.csv*   Rice_10H80.csv*    Tex_15E40.csv*
dynamo_10H30.csv*  rockets_1A10.csv*  UH_10H50.csv*

In [19]:
ls data/crime_beats/

crime_10H30_10_17.csv*  crime_10H80_10_17.csv*  crime_1A10_10_17.csv*
crime_10H50_10_17.csv*  crime_15E40_10_17.csv*

In [20]:
games = 'data/sports_scores/rockets_1A10.csv'

In [21]:
crime = 'data/crime_beats/crime_1A10_10_17.csv'

In [22]:
df = pd.read_csv(games,index_col='Date')
crime_df = pd.read_csv(crime,index_col='Date')

In [23]:
df.head()

,Unnamed: 0,Team,Team_score,Location,Opponent,Opponent_score,season,beat
Date,,,,,,,,
2009-10-31,2,Houston Rockets,111,home,Portland Trail Blazers,107,reg,1A10
2009-11-04,4,Houston Rockets,102,home,Los Angeles Lakers,103,reg,1A10
2009-11-06,5,Houston Rockets,105,home,Oklahoma City Thunder,94,reg,1A10
2009-11-11,7,Houston Rockets,104,home,Memphis Grizzlies,79,reg,1A10
2009-11-17,10,Houston Rockets,105,home,Phoenix Suns,111,reg,1A10

In [24]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15329 entries, 1971-02-03 to 2017-12-31
Data columns (total 11 columns):
Beat           15329 non-null object
BlockRange     15329 non-null object
StreetName     15329 non-null object
OffenseType    15329 non-null object
Premise        15329 non-null object
NumOffenses    15329 non-null float64
Hour           15329 non-null float64
day            15329 non-null int64
weekday        15329 non-null object
month          15329 non-null object
year           15329 non-null int64
dtypes: float64(2), int64(2), object(7)
memory usage: 1.4+ MB

In [25]:
df.head()

,Unnamed: 0,Team,Team_score,Location,Opponent,Opponent_score,season,beat
Date,,,,,,,,
2009-10-31,2,Houston Rockets,111,home,Portland Trail Blazers,107,reg,1A10
2009-11-04,4,Houston Rockets,102,home,Los Angeles Lakers,103,reg,1A10
2009-11-06,5,Houston Rockets,105,home,Oklahoma City Thunder,94,reg,1A10
2009-11-11,7,Houston Rockets,104,home,Memphis Grizzlies,79,reg,1A10
2009-11-17,10,Houston Rockets,105,home,Phoenix Suns,111,reg,1A10

In [26]:
df['win'] =  np.where(df['Team_score'] > df['Opponent_score'],1,0)

In [27]:
df.head()

,Unnamed: 0,Team,Team_score,Location,Opponent,Opponent_score,season,beat,win
Date,,,,,,,,,
2009-10-31,2,Houston Rockets,111,home,Portland Trail Blazers,107,reg,1A10,1
2009-11-04,4,Houston Rockets,102,home,Los Angeles Lakers,103,reg,1A10,0
2009-11-06,5,Houston Rockets,105,home,Oklahoma City Thunder,94,reg,1A10,1
2009-11-11,7,Houston Rockets,104,home,Memphis Grizzlies,79,reg,1A10,1
2009-11-17,10,Houston Rockets,105,home,Phoenix Suns,111,reg,1A10,0

In [28]:
df = df[['Opponent','win']]

In [29]:
crime_df = crime_df.iloc[2010:]  # data from 2010- 2017

In [30]:
crime_df = crime_df[['OffenseType','Premise','NumOffenses','Hour','weekday']]

In [31]:
df.head()

                          Opponent  win
Date
2009-10-31  Portland Trail Blazers    1
2009-11-04      Los Angeles Lakers    0
2009-11-06   Oklahoma City Thunder    1
2009-11-11       Memphis Grizzlies    1
2009-11-17            Phoenix Suns    0

## merge

In [32]:
merge = pd.merge(df,crime_df, how='inner', left_index=True, right_index=True)

In [33]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1640 entries, 2010-10-30 to 2017-05-11
Data columns (total 7 columns):
Opponent       1640 non-null object
win            1640 non-null int64
OffenseType    1640 non-null object
Premise        1640 non-null object
NumOffenses    1640 non-null float64
Hour           1640 non-null float64
weekday        1640 non-null object
dtypes: float64(2), int64(1), object(4)
memory usage: 102.5+ KB

In [34]:
merge

,Opponent,win,OffenseType,Premise,NumOffenses,Hour,weekday
Date,,,,,,,
2010-10-30,Denver Nuggets,0,Burglary,RESTAURANT/CAFETERIA,1.0,5.0,Saturday
2010-10-30,Denver Nuggets,0,Theft,RESTAURANT/CAFETERIA,1.0,11.0,Saturday
2010-10-30,Denver Nuggets,0,Theft,ROAD/STREET/SIDEWALK,1.0,18.0,Saturday
2010-10-30,Denver Nuggets,0,Burglary,APARTMENT,1.0,5.0,Saturday
2010-10-30,Denver Nuggets,0,Aggravated Assault,OTHER/UNKNOWN,1.0,22.0,Saturday
2010-10-30,Denver Nuggets,0,Aggravated Assault,ROAD/STREET/SIDEWALK,1.0,12.0,Saturday
2010-10-30,Denver Nuggets,0,Auto Theft,HOSPITAL PARKING LOT,1.0,12.0,Saturday
2010-10-30,Denver Nuggets,0,Theft,ROAD/STREET/SIDEWALK,1.0,22.0,Saturday
2010-10-30,Denver Nuggets,0,Auto Theft,ROAD/STREET/SIDEWALK,1.0,19.0,Saturday
2010-11-03,New Orleans Hornets,0,Theft,COMMERCIAL BUILDING,1.0,17.0,Wednesday
2010-11-03,New Orleans Hornets,0,Theft,OTHER/UNKNOWN,1.0,16.0,Wednesday
2010-11-03,New Orleans Hornets,0,Theft,ROAD/STREET/SIDEWALK,1.0,22.0,Wednesday
2010-11-07,Minnesota Timberwolves,1,Theft,OFFICE BUILDING,1.0,13.0,Sunday
2010-11-07,Minnesota Timberwolves,1,Theft,BAR/NIGHT CLUB,1.0,1.0,Sunday
2010-11-07,Minnesota Timberwolves,1,Theft,BUS STATION,1.0,11.0,Sunday
2010-11-07,Minnesota Timberwolves,1,Theft,HOSPITAL,1.0,18.0,Sunday
2010-11-07,Minnesota Timberwolves,1,Theft,ROAD/STREET/SIDEWALK,1.0,15.0,Sunday
2010-11-16,Chicago Bulls,0,Theft,DEPARTMENT/DISCOUNT STORE,1.0,11.0,Tuesday
2010-11-16,Chicago Bulls,0,Robbery,"PARKS & RECREATION, ZOO, SWIM POOL",1.0,19.0,Tuesday
2010-11-16,Chicago Bulls,0,Auto Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,7.0,Tuesday
2010-11-16,Chicago Bulls,0,Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,20.0,Tuesday
2010-11-16,Chicago Bulls,0,Theft,OFFICE BUILDING,1.0,12.0,Tuesday
2010-11-16,Chicago Bulls,0,Theft,OTHER PARKING LOT,1.0,11.0,Tuesday
2010-11-22,Phoenix Suns,0,Burglary,BAR/NIGHT CLUB,1.0,2.0,Monday
2010-11-22,Phoenix Suns,0,Auto Theft,COMMERCIAL PARKING LOT/GARAGE,1.0,6.0,Monday
2010-11-22,Phoenix Suns,0,Theft,DEPARTMENT/DISCOUNT STORE,1.0,11.0,Monday
2010-11-22,Phoenix Suns,0,Theft,OTHER/UNKNOWN,1.0,6.0,Monday
2010-11-24,Golden State Warriors,1,Theft,DEPARTMENT/DISCOUNT STORE,1.0,13.0,Wednesday
2010-11-24,Golden State Warriors,1,Theft,OTHER PARKING LOT,1.0,8.0,Wednesday
2010-11-24,Golden State Warriors,1,Theft,OTHER/UNKNOWN,1.0,10.0,Wednesday
...,...,...,...,...,...,...,...
2017-04-19,Oklahoma City Thunder,1,Theft,Miscellaneous Business (Non-Specific),1.0,6.0,Wednesday
2017-04-19,Oklahoma City Thunder,1,Theft,Apartment Parking Lot,1.0,6.0,Wednesday
2017-04-19,Oklahoma City Thunder,1,Theft,Commercial Parking Lot or Garage,1.0,12.0,Wednesday
2017-04-19,Oklahoma City Thunder,1,Theft,Commercial Parking Lot or Garage,1.0,23.0,Wednesday
2017-04-19,Oklahoma City Thunder,1,Rape,"Road, Street, or Sidewalk",1.0,23.0,Wednesday
2017-04-25,Oklahoma City Thunder,1,Theft,"Road, Street, or Sidewalk",1.0,10.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Theft,Commercial Parking Lot or Garage,1.0,22.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Theft,Other Parking Lot,1.0,22.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Theft,"Road, Street, or Sidewalk",1.0,22.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Theft,Commercial Parking Lot or Garage,1.0,22.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Theft,No label,1.0,23.0,Tuesday
2017-04-25,Oklahoma City Thunder,1,Auto Theft,Miscellaneous Business (Non-Specific),1.0,8.0,Tuesday
2017-05-05,San Antonio Spurs,0,Theft,Commercial Parking Lot or Garage,1.0,16.0,Friday
2017-05-05,San Antonio Spurs,0,Theft,Apartment Parking Lot,1.0,22.0,Friday
2017-05-05,San Antonio Spurs,0,Theft,Light Rail Platform,1.0,18.0,Friday
2017-05-05,San Antonio Spurs,0,Theft,Drug Store or Medical Supply,1.0,12.0,Friday
2017-05-07,San Antonio Spurs,1,Theft,Convention Center or Exhibit Halls,1.0,13.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,"Road, Street, or Sidewalk",1.0,13.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,Other Parking Lot,1.0,1.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,Other Parking Lot,1.0,16.0,Sunday
2017-05-07,San Antonio Spurs,1,Auto Theft,Commercial Parking Lot or Garage,1.0,20.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,Convention Center or Exhibit Halls,1.0,23.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,Convention Center or Exhibit Halls,1.0,23.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,"Road, Street, or Sidewalk",1.0,21.0,Sunday
2017-05-07,San Antonio Spurs,1,Theft,Other Parking Lot,1.0,18.0,Sunday
2017-05-11,San Antonio Spurs,0,Theft,Commercial Building,1.0,13.0,Thursday
2017-05-11,San Antonio Spurs,0,Auto Theft,"Other, Unknown, or Not Listed",1.0,16.0,Thursday
2017-05-11,San Antonio Spurs,0,Theft,"Road, Street, or Sidewalk",1.0,19.0,Thursday
2017-05-11,San Antonio Spurs,0,Theft,Commercial Parking Lot or Garage,1.0,14.0,Thursday
2017-05-11,San Antonio Spurs,0,Aggravated Assault,Restaurant or Cafeteria Parking Lot,1.0,8.0,Thursday