In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

# Source

#### basketball-reference.com
https://www.basketball-reference.com/teams/HOU/2017_games.html

- saved regular and playoff seasons from 2010 - 2017 to csv

In [2]:
ls sports_data_raw/NBA/

plo/  reg/

In [3]:
path = 'sports_data_raw/NBA/reg'
all_files = glob.glob(os.path.join(path, "*.csv")) 

df_from_each_file = (pd.read_csv(f) for f in all_files)
df_reg   = pd.concat(df_from_each_file, ignore_index=True)

In [4]:
# path = 'sports_data_raw/NBA/plo'
# all_files = glob.glob(os.path.join(path, "*.csv")) 

# df_from_each_file = (pd.read_csv(f) for f in all_files)
# df_plo   = pd.concat(df_from_each_file, ignore_index=True)

In [5]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 15 columns):
G             640 non-null int64
Date          640 non-null object
Unnamed: 2    640 non-null object
Unnamed: 3    8 non-null object
Unnamed: 4    640 non-null object
Unnamed: 5    320 non-null object
Opponent      640 non-null object
Unnamed: 7    640 non-null object
Unnamed: 8    47 non-null object
Tm            640 non-null int64
Opp           640 non-null int64
W             640 non-null int64
L             640 non-null int64
Streak        640 non-null object
Notes         1 non-null object
dtypes: int64(5), object(10)
memory usage: 75.1+ KB

## Create column base on regular season or playoffs

In [6]:
df_reg['season'] = 'reg'

In [7]:
df_reg

,G,Date,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Opponent,Unnamed: 7,Unnamed: 8,Tm,Opp,W,L,Streak,Notes,season
0,1,"Tue, Oct 27, 2009",7:00p ET,NaN,Box Score,@,Portland Trail Blazers,L,NaN,87,96,0,1,L 1,NaN,reg
1,2,"Wed, Oct 28, 2009",7:30p ET,NaN,Box Score,@,Golden State Warriors,W,NaN,108,107,1,1,W 1,NaN,reg
2,3,"Sat, Oct 31, 2009",7:30p ET,NaN,Box Score,NaN,Portland Trail Blazers,W,NaN,111,107,2,1,W 2,NaN,reg
3,4,"Mon, Nov 2, 2009",7:00p ET,NaN,Box Score,@,Utah Jazz,W,NaN,113,96,3,1,W 3,NaN,reg
4,5,"Wed, Nov 4, 2009",7:30p ET,NaN,Box Score,NaN,Los Angeles Lakers,L,OT,102,103,3,2,L 1,NaN,reg
5,6,"Fri, Nov 6, 2009",7:30p ET,NaN,Box Score,NaN,Oklahoma City Thunder,W,NaN,105,94,4,2,W 1,NaN,reg
6,7,"Tue, Nov 10, 2009",7:30p ET,NaN,Box Score,@,Dallas Mavericks,L,NaN,103,121,4,3,L 1,NaN,reg
7,8,"Wed, Nov 11, 2009",7:30p ET,NaN,Box Score,NaN,Memphis Grizzlies,W,NaN,104,79,5,3,W 1,NaN,reg
8,9,"Fri, Nov 13, 2009",7:00p ET,NaN,Box Score,@,Sacramento Kings,L,NaN,100,109,5,4,L 1,NaN,reg
9,10,"Sun, Nov 15, 2009",6:30p ET,NaN,Box Score,@,Los Angeles Lakers,W,NaN,101,91,6,4,W 1,NaN,reg
10,11,"Tue, Nov 17, 2009",7:30p ET,NaN,Box Score,NaN,Phoenix Suns,L,NaN,105,111,6,5,L 1,NaN,reg
11,12,"Wed, Nov 18, 2009",7:00p ET,NaN,Box Score,@,Minnesota Timberwolves,W,NaN,97,84,7,5,W 1,NaN,reg
12,13,"Fri, Nov 20, 2009",7:30p ET,NaN,Box Score,@,Atlanta Hawks,L,NaN,103,105,7,6,L 1,NaN,reg
13,14,"Sat, Nov 21, 2009",7:30p ET,NaN,Box Score,NaN,Sacramento Kings,W,NaN,113,106,8,6,W 1,NaN,reg
14,15,"Wed, Nov 25, 2009",7:30p ET,NaN,Box Score,NaN,Dallas Mavericks,L,NaN,99,130,8,7,L 1,NaN,reg
15,16,"Fri, Nov 27, 2009",7:30p ET,NaN,Box Score,NaN,San Antonio Spurs,L,NaN,84,92,8,8,L 2,NaN,reg
16,17,"Sun, Nov 29, 2009",6:00p ET,NaN,Box Score,@,Oklahoma City Thunder,W,NaN,100,91,9,8,W 1,NaN,reg
17,18,"Wed, Dec 2, 2009",7:30p ET,NaN,Box Score,@,Los Angeles Clippers,W,NaN,102,85,10,8,W 2,NaN,reg
18,19,"Thu, Dec 3, 2009",7:30p ET,NaN,Box Score,@,Golden State Warriors,W,NaN,111,109,11,8,W 3,NaN,reg
19,20,"Sat, Dec 5, 2009",7:00p ET,NaN,Box Score,@,Portland Trail Blazers,L,NaN,89,90,11,9,L 1,NaN,reg
20,21,"Wed, Dec 9, 2009",7:30p ET,NaN,Box Score,NaN,Cleveland Cavaliers,W,NaN,95,85,12,9,W 1,NaN,reg
21,22,"Fri, Dec 11, 2009",7:00p ET,NaN,Box Score,@,Philadelphia 76ers,W,NaN,96,91,13,9,W 2,NaN,reg
22,23,"Sun, Dec 13, 2009",12:30p ET,NaN,Box Score,@,Toronto Raptors,L,NaN,88,101,13,10,L 1,NaN,reg
23,24,"Tue, Dec 15, 2009",7:30p ET,NaN,Box Score,NaN,Detroit Pistons,W,NaN,107,96,14,10,W 1,NaN,reg
24,25,"Wed, Dec 16, 2009",7:00p ET,NaN,Box Score,@,Denver Nuggets,L,NaN,101,111,14,11,L 1,NaN,reg
25,26,"Fri, Dec 18, 2009",7:30p ET,NaN,Box Score,@,Dallas Mavericks,W,OT,116,108,15,11,W 1,NaN,reg
26,27,"Sat, Dec 19, 2009",7:30p ET,NaN,Box Score,NaN,Oklahoma City Thunder,W,NaN,95,90,16,11,W 2,NaN,reg
27,28,"Tue, Dec 22, 2009",7:30p ET,NaN,Box Score,NaN,Los Angeles Clippers,W,NaN,108,99,17,11,W 3,NaN,reg
28,29,"Wed, Dec 23, 2009",7:00p ET,NaN,Box Score,@,Orlando Magic,L,NaN,87,102,17,12,L 1,NaN,reg
29,30,"Sat, Dec 26, 2009",7:30p ET,NaN,Box Score,@,New Jersey Nets,W,NaN,98,93,18,12,W 1,NaN,reg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,53,"Thu, Feb 2, 2017",8:00p ET,NaN,Box Score,NaN,Atlanta Hawks,L,NaN,108,113,36,17,L 1,NaN,reg
611,54,"Fri, Feb 3, 2017",8:00p ET,NaN,Box Score,NaN,Chicago Bulls,W,OT,121,117,37,17,W 1,NaN,reg
612,55,"Tue, Feb 7, 2017",8:00p ET,NaN,Box Score,NaN,Orlando Magic,W,NaN,128,104,38,17,W 2,NaN,reg
613,56,"Thu, Feb 9, 2017",7:00p ET,NaN,Box Score,@,Charlotte Hornets,W,NaN,107,95,39,17,W 3,NaN,reg
614,57,"Sat, Feb 11, 2017",9:00p ET,NaN,Box Score,NaN,Phoenix Suns,W,NaN,133,102,40,17,W 4,NaN,reg
615,58,"Wed, Feb 15, 2017",8:00p ET,NaN,Box Score,NaN,Miami Heat,L,NaN,109,117,40,18,L 1,NaN,reg
616,59,"Thu, Feb 23, 2017",8:00p ET,NaN,Box Score,@,New Orleans Pelicans,W,NaN,129,99,41,18,W 1,NaN,reg
617,60,"Sat, Feb 25, 2017",9:00p ET,NaN,Box Score,NaN,Minnesota Timberwolves,W,NaN,142,130,42,18,W 2,NaN,reg
618,61,"Mon, Feb 27, 2017",9:30p ET,NaN,Box Score,NaN,Indiana Pacers,L,NaN,108,117,42,19,L 1,NaN,reg
619,62,"Wed, Mar 1, 2017",10:30p ET,NaN,Box Score,@,Los Angeles Clippers,W,NaN,122,103,43,19,W 1,NaN,reg
620,63,"Sat, Mar 4, 2017",9:00p ET,NaN,Box Score,NaN,Memphis Grizzlies,W,NaN,123,108,44,19,W 2,NaN,reg
621,64,"Mon, Mar 6, 2017",8:30p ET,NaN,Box Score,@,San Antonio Spurs,L,NaN,110,112,44,20,L 1,NaN,reg
622,65,"Wed, Mar 8, 2017",8:00p ET,NaN,Box Score,NaN,Utah Jazz,L,NaN,108,115,44,21,L 2,NaN,reg
623,66,"Fri, Mar 10, 2017",8:00p ET,NaN,Box Score,@,Chicago Bulls,W,NaN,115,94,45,21,W 1,NaN,reg
624,67,"Sun, Mar 12, 2017",9:00p ET,NaN,Box Score,NaN,Cleveland Cavaliers,W,NaN,117,112,46,21,W 2,NaN,reg
625,68,"Wed, Mar 15, 2017",8:00p ET,NaN,Box Score,NaN,Los Angeles Lakers,W,NaN,139,100,47,21,W 3,NaN,reg
626,69,"Fri, Mar 17, 2017",8:00p ET,NaN,Box Score,@,New Orleans Pelicans,L,NaN,112,128,47,22,L 1,NaN,reg
627,70,"Sat, Mar 18, 2017",9:30p ET,NaN,Box Score,@,Denver Nuggets,W,NaN,109,105,48,22,W 1,NaN,reg
628,71,"Mon, Mar 20, 2017",8:00p ET,NaN,Box Score,NaN,Denver Nuggets,W,NaN,125,124,49,22,W 2,NaN,reg
629,72,"Fri, Mar 24, 2017",8:00p ET,NaN,Box Score,NaN,New Orleans Pelicans,W,NaN,117,107,50,22,W 3,NaN,reg
630,73,"Sun, Mar 26, 2017",3:30p ET,NaN,Box Score,NaN,Oklahoma City Thunder,W,NaN,137,125,51,22,W 4,NaN,reg
631,74,"Tue, Mar 28, 2017",8:00p ET,NaN,Box Score,NaN,Golden State Warriors,L,NaN,106,113,51,23,L 1,NaN,reg
632,75,"Thu, Mar 30, 2017",10:30p ET,NaN,Box Score,@,Portland Trail Blazers,L,NaN,107,117,51,24,L 2,NaN,reg
633,76,"Fri, Mar 31, 2017",10:30p ET,NaN,Box Score,@,Golden State Warriors,L,NaN,98,107,51,25,L 3,NaN,reg
634,77,"Sun, Apr 2, 2017",9:00p ET,NaN,Box Score,@,Phoenix Suns,W,NaN,123,116,52,25,W 1,NaN,reg
635,78,"Wed, Apr 5, 2017",8:00p ET,NaN,Box Score,NaN,Denver Nuggets,W,NaN,110,104,53,25,W 2,NaN,reg
636,79,"Fri, Apr 7, 2017",8:00p ET,NaN,Box Score,NaN,Detroit Pistons,L,NaN,109,114,53,26,L 1,NaN,reg
637,80,"Sun, Apr 9, 2017",6:00p ET,NaN,Box Score,@,Sacramento Kings,W,NaN,135,128,54,26,W 1,NaN,reg
638,81,"Mon, Apr 10, 2017",10:30p ET,NaN,Box Score,@,Los Angeles Clippers,L,NaN,96,125,54,27,L 1,NaN,reg
639,82,"Wed, Apr 12, 2017",8:00p ET,NaN,Box Score,NaN,Minnesota Timberwolves,W,NaN,123,118,55,27,W 1,NaN,reg

## Join the two dataframes

In [ ]:
#df = pd.concat([df_reg, df_plo])

In [ ]:
#df.info()

In [8]:
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 16 columns):
G             640 non-null int64
Date          640 non-null object
Unnamed: 2    640 non-null object
Unnamed: 3    8 non-null object
Unnamed: 4    640 non-null object
Unnamed: 5    320 non-null object
Opponent      640 non-null object
Unnamed: 7    640 non-null object
Unnamed: 8    47 non-null object
Tm            640 non-null int64
Opp           640 non-null int64
W             640 non-null int64
L             640 non-null int64
Streak        640 non-null object
Notes         1 non-null object
season        640 non-null object
dtypes: int64(5), object(11)
memory usage: 80.1+ KB

In [9]:
df = df_reg

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 16 columns):
G             640 non-null int64
Date          640 non-null object
Unnamed: 2    640 non-null object
Unnamed: 3    8 non-null object
Unnamed: 4    640 non-null object
Unnamed: 5    320 non-null object
Opponent      640 non-null object
Unnamed: 7    640 non-null object
Unnamed: 8    47 non-null object
Tm            640 non-null int64
Opp           640 non-null int64
W             640 non-null int64
L             640 non-null int64
Streak        640 non-null object
Notes         1 non-null object
season        640 non-null object
dtypes: int64(5), object(11)
memory usage: 80.1+ KB

## Create slice with only needed columns

In [11]:
hou_rockets = df[['Date','Unnamed: 2','Unnamed: 5','Opponent','Unnamed: 7','Tm','Opp','season']]

## Create a column with Houston Rockets

In [12]:
hou_rockets['team'] ='Houston Rockets'

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
hou_rockets = hou_rockets[['Date','Unnamed: 2', 'team','Tm','Unnamed: 5','Opponent','Opp','Unnamed: 7','season']]

In [14]:
hou_rockets.head()

,Date,Unnamed: 2,team,Tm,Unnamed: 5,Opponent,Opp,Unnamed: 7,season
0,"Tue, Oct 27, 2009",7:00p ET,Houston Rockets,87,@,Portland Trail Blazers,96,L,reg
1,"Wed, Oct 28, 2009",7:30p ET,Houston Rockets,108,@,Golden State Warriors,107,W,reg
2,"Sat, Oct 31, 2009",7:30p ET,Houston Rockets,111,NaN,Portland Trail Blazers,107,W,reg
3,"Mon, Nov 2, 2009",7:00p ET,Houston Rockets,113,@,Utah Jazz,96,W,reg
4,"Wed, Nov 4, 2009",7:30p ET,Houston Rockets,102,NaN,Los Angeles Lakers,103,L,reg

## Rename Columns

In [15]:
hou_rockets.rename(columns={
    'Unnamed: 2':'Time',
    'team': 'Team',
    'Tm': 'Team_score',
    'Unnamed: 5': 'Location',
    'Opp': 'Opponent_score',
    'Unnamed: 7': 'Result'
},inplace=True)

In [16]:
hou_rockets.head()

,Date,Time,Team,Team_score,Location,Opponent,Opponent_score,Result,season
0,"Tue, Oct 27, 2009",7:00p ET,Houston Rockets,87,@,Portland Trail Blazers,96,L,reg
1,"Wed, Oct 28, 2009",7:30p ET,Houston Rockets,108,@,Golden State Warriors,107,W,reg
2,"Sat, Oct 31, 2009",7:30p ET,Houston Rockets,111,NaN,Portland Trail Blazers,107,W,reg
3,"Mon, Nov 2, 2009",7:00p ET,Houston Rockets,113,@,Utah Jazz,96,W,reg
4,"Wed, Nov 4, 2009",7:30p ET,Houston Rockets,102,NaN,Los Angeles Lakers,103,L,reg

## Inspect Data

In [17]:
#hou_rockets.Date.unique()  # need split day

In [18]:
hou_rockets.Time.unique()  # need correct time

array(['7:00p ET', '7:30p ET', '6:30p ET', '6:00p ET', '12:30p ET',
       '2:00p ET', '1:00p ET', '3:00p ET', '8:00p ET', '9:00p ET',
       '10:30p ET', '10:00p ET', '9:30p ET', '8:30p ET', '3:30p ET',
       '5:30p ET', '5:00p ET'], dtype=object)

In [19]:
hou_rockets.Team.unique()  # ok

array(['Houston Rockets'], dtype=object)

In [20]:
hou_rockets.Team_score.unique()  # ok

array([ 87, 108, 111, 113, 102, 105, 103, 104, 100, 101,  97,  99,  84,
        89,  95,  96,  88, 107, 116,  98,  83,  79, 110,  94, 120, 106,
        92, 119,  66, 127, 115, 109,  81, 112, 125,  93, 117, 128, 121,
        91, 118, 114,  85, 129, 124, 123, 131,  82,  90,  86, 126, 140,
       122, 136,  78,  80, 134, 130, 145,  69,  77, 132, 137, 133, 142,
       139, 135])

In [21]:
hou_rockets.Location.unique()  #

array(['@', nan], dtype=object)

In [22]:
hou_rockets.Opponent.unique()  # ok

array(['Portland Trail Blazers', 'Golden State Warriors', 'Utah Jazz',
       'Los Angeles Lakers', 'Oklahoma City Thunder', 'Dallas Mavericks',
       'Memphis Grizzlies', 'Sacramento Kings', 'Phoenix Suns',
       'Minnesota Timberwolves', 'Atlanta Hawks', 'San Antonio Spurs',
       'Los Angeles Clippers', 'Cleveland Cavaliers',
       'Philadelphia 76ers', 'Toronto Raptors', 'Detroit Pistons',
       'Denver Nuggets', 'Orlando Magic', 'New Jersey Nets',
       'New Orleans Hornets', 'New York Knicks', 'Charlotte Bobcats',
       'Miami Heat', 'Milwaukee Bucks', 'Chicago Bulls', 'Indiana Pacers',
       'Washington Wizards', 'Boston Celtics', 'Brooklyn Nets',
       'New Orleans Pelicans', 'Charlotte Hornets'], dtype=object)

In [23]:
hou_rockets.Opponent.value_counts(dropna=False)  # ok

San Antonio Spurs         32
Memphis Grizzlies         32
Dallas Mavericks          31
Oklahoma City Thunder     30
Phoenix Suns              29
Denver Nuggets            29
Sacramento Kings          29
Minnesota Timberwolves    29
Golden State Warriors     28
Los Angeles Lakers        28
Portland Trail Blazers    28
Los Angeles Clippers      28
Utah Jazz                 28
Toronto Raptors           16
Washington Wizards        16
New Orleans Pelicans      16
Miami Heat                15
Detroit Pistons           15
Cleveland Cavaliers       15
Philadelphia 76ers        15
Orlando Magic             15
Boston Celtics            15
New York Knicks           15
Atlanta Hawks             15
Milwaukee Bucks           15
Indiana Pacers            15
Chicago Bulls             15
New Orleans Hornets       15
Charlotte Bobcats         10
Brooklyn Nets             10
Charlotte Hornets          6
New Jersey Nets            5
Name: Opponent, dtype: int64

In [24]:
hou_rockets.Opponent_score.unique()  # ok

array([ 96, 107, 103,  94, 121,  79, 109,  91, 111,  84, 105, 106, 130,
        92,  85,  90, 101, 108,  99, 102,  93, 100,  88, 118, 114, 115,
        98, 104,  97,  83, 125, 110, 133, 123, 112, 122, 119, 116, 132,
       124,  95, 117,  87, 113,  89,  78,  77,  70,  80,  76, 120,  81,
        82, 134, 137,  86,  65, 131, 126, 140, 128, 127])

In [25]:
hou_rockets.Result.unique()  # ok

array(['L', 'W'], dtype=object)

## Location Column

- change @ to away, nan to home

In [26]:
hou_rockets.Location.value_counts(dropna=False)

@      320
NaN    320
Name: Location, dtype: int64

In [27]:
hou_rockets['Location'] = np.where(hou_rockets['Location'] =='@', 'away', 'home')

In [28]:
hou_rockets.Location.value_counts(dropna=False)

away    320
home    320
Name: Location, dtype: int64

In [ ]:
hou_rockets.head()

## Date column

- split Date:
    - Day : Sun
    - Date : Month, day, Year

In [ ]:
# hou_rockets['Day'] = hou_rockets['Date'].str.split(',').apply(lambda x: x[0])
# hou_rockets['Date'] = hou_rockets['Date'].str.split(',').apply(lambda x: x[1:])

In [29]:
hou_rockets.head()

,Date,Time,Team,Team_score,Location,Opponent,Opponent_score,Result,season
0,"Tue, Oct 27, 2009",7:00p ET,Houston Rockets,87,away,Portland Trail Blazers,96,L,reg
1,"Wed, Oct 28, 2009",7:30p ET,Houston Rockets,108,away,Golden State Warriors,107,W,reg
2,"Sat, Oct 31, 2009",7:30p ET,Houston Rockets,111,home,Portland Trail Blazers,107,W,reg
3,"Mon, Nov 2, 2009",7:00p ET,Houston Rockets,113,away,Utah Jazz,96,W,reg
4,"Wed, Nov 4, 2009",7:30p ET,Houston Rockets,102,home,Los Angeles Lakers,103,L,reg

In [30]:
#day = hou_rockets['Date'].str.split(',').apply(lambda x: x[0])

In [31]:
hou_rockets['Date'] = pd.to_datetime(hou_rockets['Date'])

In [32]:
hou_rockets.head()

,Date,Time,Team,Team_score,Location,Opponent,Opponent_score,Result,season
0,2009-10-27,7:00p ET,Houston Rockets,87,away,Portland Trail Blazers,96,L,reg
1,2009-10-28,7:30p ET,Houston Rockets,108,away,Golden State Warriors,107,W,reg
2,2009-10-31,7:30p ET,Houston Rockets,111,home,Portland Trail Blazers,107,W,reg
3,2009-11-02,7:00p ET,Houston Rockets,113,away,Utah Jazz,96,W,reg
4,2009-11-04,7:30p ET,Houston Rockets,102,home,Los Angeles Lakers,103,L,reg

In [33]:
hou_rockets = hou_rockets.set_index('Date').sort_index(ascending=True)

In [34]:
hou_rockets.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 640 entries, 2009-10-27 to 2017-04-12
Data columns (total 8 columns):
Time              640 non-null object
Team              640 non-null object
Team_score        640 non-null int64
Location          640 non-null object
Opponent          640 non-null object
Opponent_score    640 non-null int64
Result            640 non-null object
season            640 non-null object
dtypes: int64(2), object(6)
memory usage: 45.0+ KB

In [35]:
hou_rockets.season.value_counts(dropna=False)

reg    640
Name: season, dtype: int64

In [36]:
hou_rockets.head()

,Time,Team,Team_score,Location,Opponent,Opponent_score,Result,season
Date,,,,,,,,
2009-10-27,7:00p ET,Houston Rockets,87,away,Portland Trail Blazers,96,L,reg
2009-10-28,7:30p ET,Houston Rockets,108,away,Golden State Warriors,107,W,reg
2009-10-31,7:30p ET,Houston Rockets,111,home,Portland Trail Blazers,107,W,reg
2009-11-02,7:00p ET,Houston Rockets,113,away,Utah Jazz,96,W,reg
2009-11-04,7:30p ET,Houston Rockets,102,home,Los Angeles Lakers,103,L,reg

## Save clean data to  to csv

In [37]:
hou_rockets.to_csv('sports_data_clean/hou_rockets_10_17_reg_clean.csv')

In [38]:
ls sports_data_clean/

astros_08_17_clean.csv*           hou_rockets_10_17_reg_clean.csv*
astros_10_17_clean.csv*           hou_rockets_10_17_reg_plo_clean.csv*
astros_10_17_plo_clean.csv*       nfl_08_17_clean.csv*
astros_10_17_reg_clean.csv*       nfl10clean.csv*
dynamo_08_17_clean.csv*           nfl10yearsfull.csv*
dynamo_10_17_clean.csv*           nfl17years_clean.csv*
dynamo_10_17_plo.csv*             nfl17years_PST_clean.csv*
dynamo_10_17__reg_clean.csv*      rice_08_17_clean.csv*
hou_home_10_17_clean.csv*         tsu_08_17_clean.csv*
hou_rockets_08_17_clean.csv*      uh_08_17_clean.csv*
hou_rockets_10_17_plo_clean.csv*

In [ ]:
## Finish