In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
path ='data/crime_astros_final.csv'
games = 'sports_scores/astros_1A10.csv'

In [3]:
df = pd.read_csv(path)
df=df.rename(columns = {'Unnamed: 0':'date',
                       'Hour':'hour'})
df.hour = df.hour.astype(int)
df.day = df.day.astype(int)
df.year = df.year.astype(int)
df.date = pd.to_datetime(df.date)  # datetime index
df = df.set_index('date').sort_index(ascending=True)
df['game_on'] = np.where(df.game =='No Game',0,1)
df.drop(['game'],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23947 entries, 2010-01-01 to 2017-12-31
Data columns (total 14 columns):
Beat            23947 non-null object
OffenseType     23947 non-null object
Premise         23947 non-null object
NumOffenses     23947 non-null float64
hour            23947 non-null int64
day             23947 non-null int64
weekday         23947 non-null object
month           23947 non-null object
year            23947 non-null int64
lat             23947 non-null float64
lon             23947 non-null float64
add             23947 non-null object
dist_stadium    23947 non-null float64
game_on         23947 non-null int64
dtypes: float64(4), int64(4), object(6)
memory usage: 3.4+ MB

In [4]:
df.head()

,Beat,OffenseType,Premise,NumOffenses,hour,day,weekday,month,year,lat,lon,add,dist_stadium,game_on
date,,,,,,,,,,,,,,
2010-01-01,1A10,Auto Theft,bar/night club parking lot,1.0,0,1,Friday,Jan,2010,29.757212,-95.353294,"350 Hamilton St, Houston, TX 77002, USA",0.137184,0
2010-01-01,1A10,Theft,bar/night club,1.0,0,1,Friday,Jan,2010,29.753512,-95.363811,"1250 Caroline St, Houston, TX 77002, USA",0.549562,0
2010-01-01,1A10,Burglary,office building,1.0,0,1,Friday,Jan,2010,29.760954,-95.362089,"450 S Main St, Houston, TX 77002, USA",0.480008,0
2010-01-01,1A10,Theft,other/unknown,1.0,0,1,Friday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA",0.734357,0
2010-01-01,1A10,Theft,convention center/exhibit halls,1.0,0,1,Friday,Jan,2010,29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701...",0.403381,0

In [ ]:
# games = df[['game_on']]
# games.head()

In [5]:
games = 'sports_scores/astros_1A10.csv'

In [6]:
game_df = pd.read_csv(games,index_col='date').sort_index(ascending=True)

## win column
game_df['win'] =  np.where(game_df['team_score'] > game_df['opp_score'],1,0)

# only oposing name and win boolean
#df = df[['opposing','win']]
game_df = game_df[['win']]


# show

game_df.head()

            win
date
2010-04-05    0
2010-04-06    0
2010-04-07    0
2010-04-09    0
2010-04-10    0

## merge

In [9]:
crime_game = pd.merge(df,game_df,  left_index=True, right_index=True, how='left')
crime_game

,Beat,OffenseType,Premise,NumOffenses,hour,day,weekday,month,year,lat,lon,add,dist_stadium,game_on,win
date,,,,,,,,,,,,,,,
2010-01-01,1A10,Auto Theft,bar/night club parking lot,1.0,0,1,Friday,Jan,2010,29.757212,-95.353294,"350 Hamilton St, Houston, TX 77002, USA",0.137184,0,NaN
2010-01-01,1A10,Theft,bar/night club,1.0,0,1,Friday,Jan,2010,29.753512,-95.363811,"1250 Caroline St, Houston, TX 77002, USA",0.549562,0,NaN
2010-01-01,1A10,Burglary,office building,1.0,0,1,Friday,Jan,2010,29.760954,-95.362089,"450 S Main St, Houston, TX 77002, USA",0.480008,0,NaN
2010-01-01,1A10,Theft,other/unknown,1.0,0,1,Friday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA",0.734357,0,NaN
2010-01-01,1A10,Theft,convention center/exhibit halls,1.0,0,1,Friday,Jan,2010,29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701...",0.403381,0,NaN
2010-01-01,1A10,Burglary,restaurant/cafeteria,1.0,1,1,Friday,Jan,2010,29.753827,-95.365190,"1250 San Jacinto St, Houston, TX 77002, USA",0.617517,0,NaN
2010-01-01,1A10,Theft,bar/night club parking lot,1.0,2,1,Friday,Jan,2010,29.758682,-95.363866,"750 S Main St, Houston, TX 77002, USA",0.513569,0,NaN
2010-01-01,1A10,Theft,road/street/sidewalk,1.0,2,1,Friday,Jan,2010,29.759401,-95.359398,"450 Caroline St, Houston, TX 77002, USA",0.286270,0,NaN
2010-01-01,1A10,Auto Theft,auto repair,1.0,6,1,Friday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA",0.734357,0,NaN
2010-01-01,1A10,Theft,bar/night club,1.0,23,1,Friday,Jan,2010,29.758682,-95.363866,"750 S Main St, Houston, TX 77002, USA",0.513569,0,NaN
2010-01-01,1A10,Burglary,"theatres,dinner theaters,auditor.",1.0,23,1,Friday,Jan,2010,29.761574,-95.365701,"650 Texas St, Houston, TX 77002, USA",0.688051,0,NaN
2010-01-01,10H10,Burglary,misc. business (non-specific),1.0,0,1,Friday,Jan,2010,29.743716,-95.332731,"550 Eastwood St, Houston, TX 77011, USA",1.646844,0,NaN
2010-01-01,10H10,Rape,residence/house,1.0,6,1,Friday,Jan,2010,29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA",0.464100,0,NaN
2010-01-01,10H10,Burglary,apartment,1.0,17,1,Friday,Jan,2010,29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA",0.484864,0,NaN
2010-01-01,10H10,Theft,road/street/sidewalk,1.0,20,1,Friday,Jan,2010,29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA",0.484864,0,NaN
2010-01-01,10H30,Theft,residence/house,1.0,0,1,Friday,Jan,2010,29.739066,-95.348975,"1750 Sampson St, Houston, TX 77003, USA",1.293373,0,NaN
2010-01-01,10H30,Theft,apartment parking lot,1.0,19,1,Friday,Jan,2010,29.753648,-95.351078,"550 Bastrop St, Houston, TX 77003, USA",0.352089,0,NaN
2010-01-01,10H30,Theft,residence/house,1.0,20,1,Friday,Jan,2010,29.745298,-95.359324,"1750 Hutchins St, Houston, TX 77003, USA",0.833475,0,NaN
2010-01-02,1A10,Theft,commercial building,1.0,0,2,Saturday,Jan,2010,29.758122,-95.368310,"1050 Louisiana St, Houston, TX 77002, USA",0.770779,0,NaN
2010-01-02,1A10,Theft,bar/night club,1.0,0,2,Saturday,Jan,2010,29.763859,-95.361350,"150 Travis St, Houston, TX 77002, USA",0.589988,0,NaN
2010-01-02,1A10,Theft,other/unknown,1.0,1,2,Saturday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA",0.734357,0,NaN
2010-01-02,1A10,Theft,apartment,1.0,3,2,Saturday,Jan,2010,29.761727,-95.361468,"350 S Main St, Houston, TX 77002, USA",0.484539,0,NaN
2010-01-02,1A10,Theft,highway/freeway,1.0,14,2,Saturday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA",0.734357,0,NaN
2010-01-02,1A10,Theft,convention center/exhibit halls,1.0,14,2,Saturday,Jan,2010,29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701...",0.403381,0,NaN
2010-01-02,1A10,Auto Theft,road/street/sidewalk,1.0,14,2,Saturday,Jan,2010,29.753138,-95.362235,"1450 Dallas St, Houston, TX 77002, USA",0.479434,0,NaN
2010-01-02,1A10,Theft,residence/house,1.0,18,2,Saturday,Jan,2010,29.751411,-95.368310,"1650 Fannin St, Houston, TX 77002, USA",0.856047,0,NaN
2010-01-02,1A10,Burglary,jail/prison,1.0,19,2,Saturday,Jan,2010,29.758311,-95.360323,"1250 Texas St, Houston, TX 77002, USA",0.301551,0,NaN
2010-01-02,1A10,Theft,convenience store parking lot,1.0,19,2,Saturday,Jan,2010,29.757785,-95.362132,"750 San Jacinto St, Houston, TX 77002, USA",0.399452,0,NaN
2010-01-02,1A10,Theft,commercial parking lot/garage,1.0,23,2,Saturday,Jan,2010,29.761720,-95.363098,"450 Travis St, Houston, TX 77002, USA",0.560088,0,NaN
2010-01-02,10H10,Burglary,residence/house,1.0,19,2,Saturday,Jan,2010,29.750896,-95.337716,"50 N York St, Houston, TX 77003, USA",1.150279,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-27,1A10,Theft,road/street/sidewalk,1.0,23,27,Wednesday,Dec,2017,29.900468,-95.623985,"Shorebrook Dr, Houston, TX 77095, USA",18.910601,0,NaN
2017-12-27,10H10,Theft,road/street/sidewalk,1.0,8,27,Wednesday,Dec,2017,29.739191,-95.316836,"450 Cowling St, Houston, TX 77011, USA",2.628923,0,NaN
2017-12-27,10H30,Rape,apartment,1.0,14,27,Wednesday,Dec,2017,29.744186,-95.359011,"2250 Jefferson St, Houston, TX 77003, USA",0.902945,0,NaN
2017-12-27,10H30,Theft,road/street/sidewalk,1.0,18,27,Wednesday,Dec,2017,29.757881,-95.350422,"2050 Commerce St, Houston, TX 77002, USA",0.315227,0,NaN
2017-12-28,1A10,Theft,"hotel, motel, inn, etc.",1.0,10,28,Thursday,Dec,2017,29.755586,-95.358684,"750 Crawford St, Houston, TX 77002, USA",0.209963,0,NaN
2017-12-28,1A10,Theft,road/street/sidewalk,1.0,13,28,Thursday,Dec,2017,29.764627,-95.357128,"750 N San Jacinto St, Houston, TX 77002, USA",0.537568,0,NaN
2017-12-28,10H10,Robbery,convenience store,1.0,10,28,Thursday,Dec,2017,29.752561,-95.338303,"3350 Canal St, Houston, TX 77003, USA",1.079949,0,NaN
2017-12-28,10H10,Auto Theft,driveway,1.0,12,28,Thursday,Dec,2017,29.746025,-95.334668,"350 Hunt St, Houston, TX 77003, USA",1.463465,0,NaN
2017-12-28,10H10,Theft,restaurant/cafeteria parking lot,1.0,12,28,Thursday,Dec,2017,29.756278,-95.341400,"2850 Navigation Blvd, Houston, TX 77003, USA",0.852013,0,NaN
2017-12-28,10H10,Robbery,road/street/sidewalk,1.0,20,28,Thursday,Dec,2017,29.840329,-95.282279,"7950 Laura Koppe Rd, Houston, TX 77028, USA",7.236403,0,NaN
2017-12-28,10H30,Theft,residence/house,1.0,13,28,Thursday,Dec,2017,29.745298,-95.359324,"1750 Hutchins St, Houston, TX 77003, USA",0.833475,0,NaN
2017-12-29,1A10,Aggravated Assault,apartment,1.0,2,29,Friday,Dec,2017,29.751411,-95.368310,"1650 Fannin St, Houston, TX 77002, USA",0.856047,0,NaN
2017-12-29,1A10,Theft,garage or carport,1.0,9,29,Friday,Dec,2017,29.758513,-95.365254,"850 Travis St, Houston, TX 77002, USA",0.592771,0,NaN
2017-12-29,1A10,Theft,rental storage facility,1.0,10,29,Friday,Dec,2017,29.673019,-95.431014,"10650 S Main St, Houston, TX 77054, USA",7.348322,0,NaN
2017-12-29,1A10,Auto Theft,road/street/sidewalk,1.0,10,29,Friday,Dec,2017,29.692994,-95.417079,"8333 Braesmain Dr, Houston, TX 77025, USA",5.751672,0,NaN
2017-12-29,1A10,Auto Theft,commercial parking lot or garage,1.0,16,29,Friday,Dec,2017,29.763832,-95.360101,"950 Commerce St, Houston, TX 77002, USA",0.547409,0,NaN
2017-12-29,10H30,Theft,residence/house,1.0,16,29,Friday,Dec,2017,29.742569,-95.349999,"1450 Palmer St, Houston, TX 77003, USA",1.044944,0,NaN
2017-12-29,10H30,Robbery,road/street/sidewalk,1.0,23,29,Friday,Dec,2017,29.746279,-95.355971,"1450 Emancipation Ave, Houston, TX 77003, USA",0.735014,0,NaN
2017-12-30,1A10,Theft,commercial parking lot or garage,1.0,11,30,Saturday,Dec,2017,30.050840,-95.186626,"4321 Kingwood Dr #28, Kingwood, TX 77339, USA",22.639994,0,NaN
2017-12-30,1A10,Theft,apartment,1.0,15,30,Saturday,Dec,2017,29.745560,-95.362803,"1850 St Joseph Pkwy, Houston, TX 77003, USA",0.896988,0,NaN
2017-12-30,10H10,Burglary,restaurant or cafeteria,1.0,6,30,Saturday,Dec,2017,29.756278,-95.341400,"2850 Navigation Blvd, Houston, TX 77003, USA",0.852013,0,NaN
2017-12-30,10H30,Theft,other parking lot,1.0,20,30,Saturday,Dec,2017,29.629608,-95.215229,"9050 Iron Springs Dr, Houston, TX 77034, USA",12.171158,0,NaN
2017-12-31,1A10,Aggravated Assault,"hotel, motel, inn, etc.",1.0,2,31,Sunday,Dec,2017,29.752417,-95.361416,"1550 Dallas St, Houston, TX 77002, USA",0.470373,0,NaN
2017-12-31,1A10,Robbery,bus stop,1.0,16,31,Sunday,Dec,2017,29.749452,-95.370759,"950 Pierce St, Houston, TX 77002, USA",1.049378,0,NaN
2017-12-31,1A10,Theft,commercial parking lot or garage,1.0,17,31,Sunday,Dec,2017,29.609287,-95.442111,"14950 Monrad Dr, Houston, TX 77053, USA",11.425112,0,NaN
2017-12-31,1A10,Auto Theft,road/street/sidewalk,1.0,22,31,Sunday,Dec,2017,29.767134,-95.354628,"750 Walnut St, Houston, TX 77002, USA",0.704084,0,NaN
2017-12-31,10H10,Theft,road/street/sidewalk,1.0,11,31,Sunday,Dec,2017,29.759400,-95.341881,"450 N Live Oak St, Houston, TX 77003, USA",0.839089,0,NaN
2017-12-31,10H10,Theft,other parking lot,1.0,18,31,Sunday,Dec,2017,29.756351,-95.347639,"2350 Commerce St, Houston, TX 77003, USA",0.477558,0,NaN
2017-12-31,10H30,Theft,road/street/sidewalk,1.0,2,31,Sunday,Dec,2017,29.936241,-95.284769,"6950 Oak Village Dr, Humble, TX 77396, USA",13.060760,0,NaN
2017-12-31,10H30,Theft,service or gas station,1.0,16,31,Sunday,Dec,2017,29.731120,-95.346909,"3650 Dennis St, Houston, TX 77004, USA",1.853094,0,NaN

In [ ]:
ww.win.unique()

In [12]:
crime_sum_days = df.groupby(df.index)['OffenseType',].count()
crime_sum_days.head()

            OffenseType
date
2010-01-01           18
2010-01-02           13
2010-01-03           12
2010-01-04            9
2010-01-05            8

## Trim df

In [ ]:
print(list(df.columns))

In [ ]:
#df= df[[ 'OffenseType', 'hour', 'weekday', 'dist_stadium', 'game_on']]
df = df[[ 'OffenseType', 'hour', 'dist_stadium', 'game_on']]

In [ ]:
df.head()

In [ ]:
df.describe()

## TEST1

In [ ]:
one_mile =  df.dist_stadium <= 3.0
df = df[one_mile]

In [ ]:

# find distribution of target column / trying to predict
sns.distplot(df['dist_stadium'])

In [ ]:
df.corr()

In [ ]:

sns.heatmap(df.corr(),annot=True)

## Get dummies

In [ ]:
pd.get_dummies?

In [ ]:
dfdm = pd.get_dummies(df, drop_first=True)

In [ ]:
sns.heatmap(dfdm.corr(),annot=False)

In [ ]:
dfdm.head()

In [ ]:
df.head()

## Pairplot

In [ ]:
#sns.pairplot(dfdm)

In [ ]:
#dfdm.drop(['dist_stadium'],axis=1)
#dfdm['game_on']

In [ ]:
sns.lmplot(x='game_on',y='dist_stadium', data=dfdm)

In [ ]:
from sklearn.cross_validation import train_test_split

X = dfdm.drop(['dist_stadium'],axis=1)

y = dfdm['dist_stadium']

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                test_size=0.3,
                                random_state=42)

# train model

In [ ]:
from sklearn.linear_model import LinearRegression

# create a linear regression object
model =  LinearRegression()


# train fit model
model.fit(X_train,y_train)

# Evalueate model

In [ ]:
print(model.intercept_)
print(model.coef_)

## Create a dataframe from coeff

In [ ]:
coeff_df = pd.DataFrame(model.coef_,X.columns,columns=['Coefficient'])
coeff_df

## Predictions from our test

In [ ]:
predictions = model.predict(X_test)

## Pefrorm scatteplot

In [ ]:
plt.scatter(y_test,predictions)
plt.xlabel('Y Test (True Values)')
plt.ylabel('Predicted Y')
plt.show()

In [ ]:
# histogram of the residuals
sns.distplot((y_test - predictions),bins='auto')

## Calculate metrics

In [ ]:
from sklearn import metrics

## MAE
**Mean Absolute Error** (MAE) is the mean of the absolute value of the errors:
- mean of the absolute error
- take your error and take the absolute value of it and average it out.

$$\frac 1n\sum_{i=1}^n|y_i-\hat{y}_i|$$

In [ ]:
print('MAE:', metrics.mean_absolute_error(y_test, predictions))

In [ ]:
def L1(yHat, y):
    return np.sum(np.absolute(yHat - y))

L1(y_test,predictions)

# MSE

**Mean Squared Error** (MSE) is the mean of the squared errors:

- mean of the squared errors
- popular b/c it punish larger errors
- more usefull in the real world  because it takes into account larger b/c its square them.


$$\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2$$

In [ ]:
print('MSE:', metrics.mean_squared_error(y_test, predictions))

In [ ]:
def MSE(yHat, y):
    return np.sum((yHat - y)**2) / y.size

MSE(y_test,predictions)

# RMSE
**Root Mean Squared Error** (RMSE) is the square root of the mean of the squared errors:

$$\sqrt{\frac 1n\sum_{i=1}^n(y_i-\hat{y}_i)^2}$$

In [ ]:
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

## RSQ

In [ ]:
print('RSQ:', metrics.explained_variance_score(y_test, predictions))

In [ ]:
params = pd.Series(model.coef_, index=X.columns)
params

In [ ]:
from sklearn.utils import resample
np.random.seed(1)
err = np.std([model.fit(*resample(X, y)).coef_
              for i in range(1000)], 0)

In [ ]:
print(pd.DataFrame({'effect': params.round(0),
                    'error': err.round(0)}))