In [2]:
import pandas as pd
import numpy as np

In [3]:
ls crime_data_clean/

beats_alternate_10_17.csv*      crime_10H70_10_17df_2000.csv*
beats_filter_10_17.csv*         crime_10H70_10_17df_3000.csv*
crime_10H10_10_17ADD.csv*       crime_10H70_10_17df_4000.csv*
crime_10H10_10_17.csv*          crime_10H70_10_17df_5000.csv*
crime_10H10_10_17df_1000.csv*   crime_10H70_10_17df_6000.csv*
crime_10H10_10_17df_2000.csv*   crime_10H70_10_17df_7000.csv*
crime_10H10_10_17df_3000.csv*   crime_10H70_10_17df_8000.csv*
crime_10H10_10_17df_4000.csv*   crime_10H70_10_17df_9000.csv*
crime_10H30_10_17ADD.csv*       crime_10H80_10_17ADD.csv*
crime_10H30_10_17.csv*          crime_10H80_10_17.csv*
crime_10H30_10_17FINAL.csv*     crime_10H80_10_17FINAL.csv*
crime_10H40_10_17ADD.csv*       crime_15E40_10_17ADD.csv*
crime_10H40_10_17.csv*          crime_15E40_10_17.csv*
crime_10H40_10_17df_10000.csv*  crime_15E40_10_17df_12000.csv*
crime_10H40_10_17df_1000.csv*   crime_15E40_10_17df_16281.csv*
crime_10H40_10_17df_2000.csv*   crime_15E40_10_17df_4000.csv*
crime_10H40_10_17df_3000.csv*   crime_15E40_10_17df_8000.csv*
crime_10H40_10_17df_4000.csv*   crime_15E40_10_17FINAL.csv*
crime_10H40_10_17df_5000.csv*   crime_1A10_10_17ADD.csv*
crime_10H40_10_17df_6000.csv*   crime_1A10_10_17.csv*
crime_10H40_10_17df_7000.csv*   crime_1A10_10_17df_14978.csv*
crime_10H40_10_17df_8000.csv*   crime_1A10_10_17df_4000.csv*
crime_10H40_10_17df_9000.csv*   crime_1A10_10_17df_8000.csv*
crime_10H40_10_17LATLON.csv*    crime_1A10_10_17df_p1.csv*
crime_10H50_10_17ADD.csv*       crime_1A10_10_17df_p2.csv*
crime_10H50_10_17.csv*          crime_1A10_10_17df_p3.csv*
crime_10H50_10_17FINAL.csv*     crime_1A10_10_17df_p4.csv*
crime_10H60_10_17ADD.csv*       crime_1A10_10_17FINAL.csv*
crime_10H60_10_17.csv*          crime_1A10_10_17LATLON.csv*
crime_10H60_10_17df_1000.csv*   crime_final_clean10_17.csv*
crime_10H60_10_17df_2000.csv*   df_10H10FINAL.csv*
crime_10H60_10_17df_3000.csv*   df_10H30FINAL.csv*
crime_10H60_10_17df_4000.csv*   df_10H40FINAL.csv*
crime_10H60_10_17df_5000.csv*   df_10H50FINAL.csv*
crime_10H60_10_17df_6000.csv*   df_10H60FINAL.csv*
crime_10H60_10_17df_7000.csv*   df_10H70FINAL.csv*
crime_10H60_10_17LATLON.csv*    df_1A10FINAL.csv*
crime_10H70_10_17ADD.csv*       new/
crime_10H70_10_17.csv*          stadium_beats_geocode.csv*
crime_10H70_10_17df_10000.csv*  stadiums_final.csv*
crime_10H70_10_17df_1000.csv*   years/

##  ~~10H40~~ , ~~10H60~~, 10H70, ~~10H10~~

# 10H40

In [4]:
path = 'crime_data_clean/crime_10H40_10_17LATLON.csv'

In [6]:
df_10H40 = pd.read_csv(path)

In [46]:
df_10H40.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 01:00:00,10H40,Theft,bar/night club,1,1,1,Friday,Jan,2010,29.745307,-95.371946,"2450 San Jacinto St, Houston, TX 77002, USA"
1,2010-01-01 03:00:00,10H40,Theft,other parking lot,1,3,1,Friday,Jan,2010,29.738960,-95.397363,"1450 W Alabama St, Houston, TX 77006, USA"

In [15]:
df_10H40 = df_10H40[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'add']]

In [17]:
df_10H40.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10406 entries, 0 to 10405
Data columns (total 13 columns):
Date_Hour      10406 non-null object
Beat           10406 non-null object
OffenseType    10406 non-null object
Premise        10406 non-null object
NumOffenses    10406 non-null int64
Hour           10406 non-null int64
day            10406 non-null int64
weekday        10406 non-null object
month          10406 non-null object
year           10406 non-null int64
lat            10406 non-null float64
lon            10406 non-null float64
add            10406 non-null object
dtypes: float64(2), int64(4), object(7)
memory usage: 1.0+ MB

In [18]:
df_10H40.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 01:00:00,10H40,Theft,bar/night club,1,1,1,Friday,Jan,2010,29.745307,-95.371946,"2450 San Jacinto St, Houston, TX 77002, USA"
1,2010-01-01 03:00:00,10H40,Theft,other parking lot,1,3,1,Friday,Jan,2010,29.738960,-95.397363,"1450 W Alabama St, Houston, TX 77006, USA"
2,2010-01-01 05:00:00,10H40,Theft,bar/night club,1,5,1,Friday,Jan,2010,29.745307,-95.371946,"2450 San Jacinto St, Houston, TX 77002, USA"
3,2010-01-02 00:00:00,10H40,Theft,road/street/sidewalk,1,0,2,Saturday,Jan,2010,29.741186,-95.373694,"1250 Anita St, Houston, TX 77004, USA"
4,2010-01-02 17:00:00,10H40,Theft,other parking lot,1,17,2,Saturday,Jan,2010,29.734911,-95.382958,"4250 S Main St, Houston, TX 77002, USA"

In [20]:
df_10H40.to_csv('crime_data_clean/df_10H40FINAL.csv')

# 10H60

In [21]:
ls crime_data_clean/

beats_alternate_10_17.csv*      crime_10H60_10_17df_6000.csv*
beats_filter_10_17.csv*         crime_10H60_10_17df_7000.csv*
crime_10H10_10_17ADD.csv*       crime_10H60_10_17LATLON.csv*
crime_10H10_10_17.csv*          crime_10H70_10_17.csv*
crime_10H10_10_17df_1000.csv*   crime_10H70_10_17df_1000.csv*
crime_10H10_10_17df_2000.csv*   crime_10H70_10_17df_2000.csv*
crime_10H10_10_17df_3000.csv*   crime_10H70_10_17df_3000.csv*
crime_10H10_10_17df_4000.csv*   crime_10H80_10_17ADD.csv*
crime_10H30_10_17ADD.csv*       crime_10H80_10_17.csv*
crime_10H30_10_17.csv*          crime_10H80_10_17FINAL.csv*
crime_10H30_10_17FINAL.csv*     crime_15E40_10_17ADD.csv*
crime_10H40_10_17ADD.csv*       crime_15E40_10_17.csv*
crime_10H40_10_17.csv*          crime_15E40_10_17df_12000.csv*
crime_10H40_10_17df_10000.csv*  crime_15E40_10_17df_16281.csv*
crime_10H40_10_17df_1000.csv*   crime_15E40_10_17df_4000.csv*
crime_10H40_10_17df_2000.csv*   crime_15E40_10_17df_8000.csv*
crime_10H40_10_17df_3000.csv*   crime_15E40_10_17FINAL.csv*
crime_10H40_10_17df_4000.csv*   crime_1A10_10_17ADD.csv*
crime_10H40_10_17df_5000.csv*   crime_1A10_10_17.csv*
crime_10H40_10_17df_6000.csv*   crime_1A10_10_17df_14978.csv*
crime_10H40_10_17df_7000.csv*   crime_1A10_10_17df_4000.csv*
crime_10H40_10_17df_8000.csv*   crime_1A10_10_17df_8000.csv*
crime_10H40_10_17df_9000.csv*   crime_1A10_10_17df_p1.csv*
crime_10H40_10_17LATLON.csv*    crime_1A10_10_17df_p2.csv*
crime_10H50_10_17ADD.csv*       crime_1A10_10_17df_p3.csv*
crime_10H50_10_17.csv*          crime_1A10_10_17df_p4.csv*
crime_10H50_10_17FINAL.csv*     crime_1A10_10_17FINAL.csv*
crime_10H60_10_17ADD.csv*       crime_1A10_10_17LATLON.csv*
crime_10H60_10_17.csv*          crime_final_clean10_17.csv*
crime_10H60_10_17df_1000.csv*   df_10H40FINAL.csv*
crime_10H60_10_17df_2000.csv*   new/
crime_10H60_10_17df_3000.csv*   stadium_beats_geocode.csv*
crime_10H60_10_17df_4000.csv*   stadiums_final.csv*
crime_10H60_10_17df_5000.csv*   years/

In [22]:
# crime_10H60_10_17LATLON

path = 'crime_data_clean/crime_10H60_10_17LATLON.csv'
df_10H60 = pd.read_csv(path)

In [24]:
df_10H60.head()

,Unnamed: 0,Date_Hour,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add,lat,lon,add
0,0,2010-01-01 00:00:00,10H60,2500-2599,SOUTHMORE,Burglary,apartment,1,0,1,Friday,Jan,2010,2550,2550 SOUTHMORE,"[{'address_components': [{'long_name': '2550',...",29.719598,-95.373216,"2550 Southmore Blvd, Houston, TX 77004, USA"
1,1,2010-01-01 00:00:00,10H60,3500-3599,MACGREGOR,Theft,apartment,1,0,1,Friday,Jan,2010,3550,3550 MACGREGOR,"[{'address_components': [{'long_name': '3550',...",29.709357,-95.362421,"3550 S MacGregor Way, Houston, TX 77021, USA"
2,2,2010-01-01 04:00:00,10H60,4000-4099,CANFIELD,Robbery,bank/saving institution parking lot,1,4,1,Friday,Jan,2010,4050,4050 CANFIELD,"[{'address_components': [{'long_name': '4050',...",29.720348,-95.354861,"4050 Canfield St, Houston, TX 77004, USA"
3,3,2010-01-01 06:00:00,10H60,3700-3799,ODIN,Theft,apartment,1,6,1,Friday,Jan,2010,3750,3750 ODIN,[{'address_components': [{'long_name': 'Housto...,29.760427,-95.369803,"Houston, TX, USA"
4,4,2010-01-01 14:00:00,10H60,5500-5599,LIVE OAK,Theft,apartment,1,14,1,Friday,Jan,2010,5550,5550 LIVE OAK,"[{'address_components': [{'long_name': '5550',...",29.716282,-95.375548,"5550 Live Oak St, Houston, TX 77004, USA"

In [32]:
df_10H60 = df_10H60[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'add']]

In [33]:
df_10H60.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7671 entries, 0 to 7670
Data columns (total 13 columns):
Date_Hour      7671 non-null object
Beat           7671 non-null object
OffenseType    7671 non-null object
Premise        7671 non-null object
NumOffenses    7671 non-null int64
Hour           7671 non-null int64
day            7671 non-null int64
weekday        7671 non-null object
month          7671 non-null object
year           7671 non-null int64
lat            7671 non-null float64
lon            7671 non-null float64
add            7671 non-null object
dtypes: float64(2), int64(4), object(7)
memory usage: 779.2+ KB

In [34]:
df_10H60.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 00:00:00,10H60,Burglary,apartment,1,0,1,Friday,Jan,2010,29.719598,-95.373216,"2550 Southmore Blvd, Houston, TX 77004, USA"
1,2010-01-01 00:00:00,10H60,Theft,apartment,1,0,1,Friday,Jan,2010,29.709357,-95.362421,"3550 S MacGregor Way, Houston, TX 77021, USA"
2,2010-01-01 04:00:00,10H60,Robbery,bank/saving institution parking lot,1,4,1,Friday,Jan,2010,29.720348,-95.354861,"4050 Canfield St, Houston, TX 77004, USA"
3,2010-01-01 06:00:00,10H60,Theft,apartment,1,6,1,Friday,Jan,2010,29.760427,-95.369803,"Houston, TX, USA"
4,2010-01-01 14:00:00,10H60,Theft,apartment,1,14,1,Friday,Jan,2010,29.716282,-95.375548,"5550 Live Oak St, Houston, TX 77004, USA"

In [35]:
df_10H60.to_csv('crime_data_clean/df_10H60FINAL.csv')

# 10H10

In [98]:
# crime_10H60_10_17LATLON

path = 'crime_data_clean/crime_10H10_10_17ADD.csv'
df_10H10 = pd.read_csv(path)

In [99]:
df_10H10

,Unnamed: 0,Date_Hour,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add,lat,lon,add
0,0,2010-01-01 00:00:00,10H10,500-599,EASTWOOD,Burglary,misc. business (non-specific),1,0,1,Friday,Jan,2010,550,550 EASTWOOD,"[{'address_components': [{'long_name': '550', ...",29.743716,-95.332731,"550 Eastwood St, Houston, TX 77011, USA"
1,1,2010-01-01 06:00:00,10H10,2300-2399,SPERBER,Rape,residence/house,1,6,1,Friday,Jan,2010,2350,2350 SPERBER,"[{'address_components': [{'long_name': '2350',...",29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA"
2,2,2010-01-01 17:00:00,10H10,1900-1999,RUNNELS,Burglary,apartment,1,17,1,Friday,Jan,2010,1950,1950 RUNNELS,"[{'address_components': [{'long_name': '1950',...",29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
3,3,2010-01-01 20:00:00,10H10,1900-1999,RUNNELS,Theft,road/street/sidewalk,1,20,1,Friday,Jan,2010,1950,1950 RUNNELS,"[{'address_components': [{'long_name': '1950',...",29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
4,4,2010-01-02 19:00:00,10H10,0-99,YORK,Burglary,residence/house,1,19,2,Saturday,Jan,2010,50,50 YORK,"[{'address_components': [{'long_name': '50', '...",29.750896,-95.337716,"50 N York St, Houston, TX 77003, USA"
5,5,2010-01-03 00:00:00,10H10,200-299,GRACE,Auto Theft,apartment parking lot,1,0,3,Sunday,Jan,2010,250,250 GRACE,[{'address_components': [{'long_name': 'Grace ...,29.982173,-95.347130,"Grace St, Houston, TX 77032, USA"
6,6,2010-01-03 12:00:00,10H10,500-599,BRYAN,Burglary,auto repair,1,12,3,Sunday,Jan,2010,550,550 BRYAN,"[{'address_components': [{'long_name': '550', ...",29.742949,-95.325523,"550 Bryan St, Houston, TX 77011, USA"
7,7,2010-01-04 08:00:00,10H10,400-499,HUNT,Theft,commercial parking lot/garage,1,8,4,Monday,Jan,2010,450,450 HUNT,"[{'address_components': [{'long_name': '450', ...",29.745343,-95.334955,"450 Hunt St, Houston, TX 77003, USA"
8,8,2010-01-04 14:00:00,10H10,1900-1999,RUNNELS,Burglary,apartment,1,14,4,Monday,Jan,2010,1950,1950 RUNNELS,"[{'address_components': [{'long_name': '1950',...",29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
9,9,2010-01-05 02:00:00,10H10,3300-3399,CANAL,Burglary,convenience store,1,2,5,Tuesday,Jan,2010,3350,3350 CANAL,"[{'address_components': [{'long_name': '3350',...",29.752561,-95.338303,"3350 Canal St, Houston, TX 77003, USA"
10,10,2010-01-07 17:00:00,10H10,600-699,NAVIGATION,Robbery,road/street/sidewalk,1,17,7,Thursday,Jan,2010,650,650 NAVIGATION,[{'address_components': [{'long_name': 'Naviga...,29.748622,-95.318490,"Navigation Blvd, Houston, TX, USA"
11,11,2010-01-08 18:00:00,10H10,3300-3399,CANAL,Theft,service/gas station,1,18,8,Friday,Jan,2010,3350,3350 CANAL,"[{'address_components': [{'long_name': '3350',...",29.752561,-95.338303,"3350 Canal St, Houston, TX 77003, USA"
12,12,2010-01-09 05:00:00,10H10,300-399,SIDNEY,Theft,road/street/sidewalk,1,5,9,Saturday,Jan,2010,350,350 SIDNEY,"[{'address_components': [{'long_name': '350', ...",29.745550,-95.333140,"350 Sidney St, Houston, TX 77003, USA"
13,13,2010-01-09 13:00:00,10H10,5300-5399,AVE J,Burglary,"vacant single occupancy residence (houses,town...",1,13,9,Saturday,Jan,2010,5350,5350 AVE J,"[{'address_components': [{'long_name': '5350',...",29.748600,-95.319878,"5350 Avenue J, Houston, TX 77011, USA"
14,14,2010-01-09 13:00:00,10H10,5300-5399,AVE J,Burglary,"vacant single occupancy residence (houses,town...",1,13,9,Saturday,Jan,2010,5350,5350 AVE J,"[{'address_components': [{'long_name': '5350',...",29.748600,-95.319878,"5350 Avenue J, Houston, TX 77011, USA"
15,15,2010-01-10 02:00:00,10H10,4700-4799,CANAL,Auto Theft,other/unknown,1,2,10,Sunday,Jan,2010,4750,4750 CANAL,"[{'address_components': [{'long_name': '4750',...",29.747593,-95.326009,"4750 Canal St, Houston, TX 77011, USA"
16,16,2010-01-10 22:00:00,10H10,5300-5399,SHERMAN,Theft,road/street/sidewalk,1,22,10,Sunday,Jan,2010,5350,5350 SHERMAN,"[{'address_components': [{'long_name': '5350',...",29.743543,-95.320859,"5350 Sherman St, Houston, TX 77011, USA"
17,17,2010-01-10 22:00:00,10H10,5200-5299,SHERMAN,Theft,driveway,1,22,10,Sunday,Jan,2010,5250,5250 SHERMAN,"[{'address_components': [{'long_name': '5250',...",29.743970,-95.322029,"5250 Sherman St, Houston, TX 77011, USA"
18,18,2010-01-12 23:00:00,10H10,4400-4499,HARRISBURG,Robbery,convenience store,1,23,12,Tuesday,Jan,2010,4450,4450 HARRISBURG,"[{'address_components': [{'long_name': '4450',...",29.744531,-95.333675,"4450 Harrisburg Blvd, Houston, TX 77003, USA"
19,19,2010-01-13 10:00:00,10H10,6200-6299,HARRISBURG,Robbery,check cashing places,1,10,13,Wednesday,Jan,2010,6250,6250 HARRISBURG,"[{'address_components': [{'long_name': '6250',...",29.738884,-95.313757,"6250 Harrisburg Blvd, Houston, TX 77011, USA"
20,20,2010-01-13 11:00:00,10H10,2800-2899,CANAL,Theft,apartment,1,11,13,Wednesday,Jan,2010,2850,2850 CANAL,"[{'address_components': [{'long_name': '2850',...",29.754861,-95.341877,"2850 Canal St, Houston, TX 77003, USA"
21,21,2010-01-13 22:00:00,10H10,3200-3299,GARROW,Theft,commercial parking lot/garage,1,22,13,Wednesday,Jan,2010,3250,3250 GARROW,"[{'address_components': [{'long_name': '3250',...",29.750238,-95.341462,"3250 Garrow St, Houston, TX 77003, USA"
22,22,2010-01-15 01:00:00,10H10,0-99,NORWOOD,Theft,apartment,1,1,15,Friday,Jan,2010,50,50 NORWOOD,"[{'address_components': [{'long_name': '50', '...",29.743833,-95.316592,"50 Norwood St, Houston, TX 77011, USA"
23,23,2010-01-15 17:00:00,10H10,200-299,STILES,Auto Theft,driveway,1,17,15,Friday,Jan,2010,250,250 STILES,"[{'address_components': [{'long_name': '250', ...",29.744182,-95.326409,"250 Stiles St, Houston, TX 77011, USA"
24,24,2010-01-15 22:00:00,10H10,1900-1999,RUNNELS,Theft,apartment parking lot,1,22,15,Friday,Jan,2010,1950,1950 RUNNELS,"[{'address_components': [{'long_name': '1950',...",29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
25,25,2010-01-16 20:00:00,10H10,4200-4299,CRITES,Aggravated Assault,residence/house,1,20,16,Saturday,Jan,2010,4250,4250 CRITES,"[{'address_components': [{'long_name': '4250',...",29.754063,-95.328045,"4250 Crites St, Houston, TX 77003, USA"
26,26,2010-01-16 22:00:00,10H10,2900-2999,NAVIGATION,Theft,highway/freeway,1,22,16,Saturday,Jan,2010,2950,2950 NAVIGATION,"[{'address_components': [{'long_name': '2950',...",29.755684,-95.340604,"2950 Navigation Blvd, Houston, TX 77003, USA"
27,27,2010-01-17 01:00:00,10H10,4300-4399,NAVIGATION,Aggravated Assault,road/street/sidewalk,1,1,17,Sunday,Jan,2010,4350,4350 NAVIGATION,"[{'address_components': [{'long_name': '4350',...",29.752463,-95.328337,"4350 Navigation Blvd, Houston, TX 77003, USA"
28,28,2010-01-17 23:00:00,10H10,1900-1999,RUNNELS,Burglary,apartment,1,23,17,Sunday,Jan,2010,1950,1950 RUNNELS,"[{'address_components': [{'long_name': '1950',...",29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
29,29,2010-01-18 01:00:00,10H10,4500-4599,CANAL,Robbery,road/street/sidewalk,1,1,18,Monday,Jan,2010,4550,4550 CANAL,"[{'address_components': [{'long_name': '4550',...",29.748060,-95.327739,"4550 Canal St, Houston, TX 77011, USA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3957,3957,2017-12-14 04:00:00,10H10,2800-2899,COMMERCE ST,Robbery,road/street/sidewalk,1,4,14,Thursday,Dec,2017,2850,2850 COMMERCE ST,"[{'address_components': [{'long_name': '2850',...",29.753945,-95.343794,"2850 Commerce St, Houston, TX 77003, USA"
3958,3959,2017-12-15 08:00:00,10H10,2500-2599,NAVIGATION,Theft,restaurant/cafeteria parking lot,1,8,15,Friday,Dec,2017,2550,2550 NAVIGATION,"[{'address_components': [{'long_name': '2550',...",29.757803,-95.343642,"2550 Navigation Blvd, Houston, TX 77003, USA"
3959,3960,2017-12-16 09:00:00,10H10,2100-2199,RUNNELS,Theft,commercial parking lot or garage,1,9,16,Saturday,Dec,2017,2150,2150 RUNNELS,"[{'address_components': [{'long_name': '2150',...",29.760183,-95.347268,"2150 Runnels St, Houston, TX 77003, USA"
3960,3961,2017-12-16 15:00:00,10H10,11300-11399,SAGEVALE,Theft,apartment parking lot,1,15,16,Saturday,Dec,2017,11350,11350 SAGEVALE,[{'address_components': [{'long_name': '11350'...,29.586160,-95.224453,"11350 Sagevale Ln, Houston, TX 77089, USA"
3961,3962,2017-12-16 18:00:00,10H10,4900-4999,HARRISBURG,Theft,convenience store,1,18,16,Saturday,Dec,2017,4950,4950 HARRISBURG,"[{'address_components': [{'long_name': '4950',...",29.742985,-95.326115,"4950 Harrisburg Blvd, Houston, TX 77011, USA"
3962,3963,2017-12-17 08:00:00,10H10,2300-2399,SPERBER LN,Theft,road/street/sidewalk,1,8,17,Sunday,Dec,2017,2350,2350 SPERBER LN,"[{'address_components': [{'long_name': '2350',...",29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA"
3963,3964,2017-12-17 11:00:00,10H10,2300-2399,SPERBER LN,Theft,road/street/sidewalk,1,11,17,Sunday,Dec,2017,2350,2350 SPERBER LN,"[{'address_components': [{'long_name': '2350',...",29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA"
3964,3965,2017-12-17 12:00:00,10H10,200-299,N BURR,Theft,residence/house,1,12,17,Sunday,Dec,2017,250,250 N BURR,"[{'address_components': [{'long_name': '250', ...",29.748573,-95.324580,"250 N Burr St, Houston, TX 77011, USA"
3965,3966,2017-12-18 10:00:00,10H10,2300-2399,CANAL ST,Robbery,bus stop,1,10,18,Monday,Dec,2017,2350,2350 CANAL ST,"[{'address_components': [{'long_name': '2350',...",29.757531,-95.346702,"2350 Canal St, Houston, TX 77003, USA"
3966,3967,2017-12-19 07:00:00,10H10,2100-2199,CANAL ST,Auto Theft,apartment parking lot,1,7,19,Tuesday,Dec,2017,2150,2150 CANAL ST,"[{'address_components': [{'long_name': '2150',...",29.758591,-95.348541,"2150 Canal St, Houston, TX 77003, USA"
3967,3968,2017-12-19 07:00:00,10H10,2300-2399,SPERBER LN,Theft,driveway,1,7,19,Tuesday,Dec,2017,2350,2350 SPERBER LN,"[{'address_components': [{'long_name': '2350',...",29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA"
3968,3969,2017-12-19 10:00:00,10H10,2100-2199,CANAL ST,Theft,apartment parking lot,1,10,19,Tuesday,Dec,2017,2150,2150 CANAL ST,"[{'address_components': [{'long_name': '2150',...",29.758591,-95.348541,"2150 Canal St, Houston, TX 77003, USA"
3969,3970,2017-12-20 09:00:00,10H10,100-199,HUTCHESON,Burglary,vehicle/auto sales/lease/auto parts store,1,9,20,Wednesday,Dec,2017,150,150 HUTCHESON,"[{'address_components': [{'long_name': '150', ...",29.752055,-95.335693,"150 N Hutcheson St, Houston, TX 77003, USA"
3970,3971,2017-12-20 20:00:00,10H10,5500-5599,HARRISBURG BLVD,Theft,light rail (metro rail) vehicle,1,20,20,Wednesday,Dec,2017,5550,5550 HARRISBURG BLVD,"[{'address_components': [{'long_name': '5550',...",29.741016,-95.319984,"5550 Harrisburg Blvd, Houston, TX 77011, USA"
3971,3972,2017-12-22 06:00:00,10H10,2500-2599,GARROW,Theft,residence/house,1,6,22,Friday,Dec,2017,2550,2550 GARROW,"[{'address_components': [{'long_name': '2550',...",29.753327,-95.346633,"2550 Garrow St, Houston, TX 77003, USA"
3972,3973,2017-12-22 07:00:00,10H10,3500-3599,CANAL,Burglary,"laundry, dry cleaners, washaterias",1,7,22,Friday,Dec,2017,3550,3550 CANAL,"[{'address_components': [{'long_name': '3550',...",29.751543,-95.336506,"3550 Canal St, Houston, TX 77003, USA"
3973,3974,2017-12-22 22:00:00,10H10,2200-2299,CANAL ST,Burglary,vacant government or public building,1,22,22,Friday,Dec,2017,2250,2250 CANAL ST,"[{'address_components': [{'long_name': '2250',...",29.758291,-95.348051,"2250 Canal St, Houston, TX 77003, USA"
3974,3975,2017-12-24 04:00:00,10H10,4200-4299,NAVIGATION,Burglary,bar or night club,1,4,24,Sunday,Dec,2017,4250,4250 NAVIGATION,"[{'address_components': [{'long_name': '4250',...",29.752836,-95.329108,"4250 Navigation Blvd, Houston, TX 77003, USA"
3975,3976,2017-12-25 11:00:00,10H10,100-199,DRENNAN,Burglary,warehouse,1,11,25,Monday,Dec,2017,150,150 DRENNAN,"[{'address_components': [{'long_name': '150', ...",29.750670,-95.332279,"150 N Drennan St, Houston, TX 77003, USA"
3976,3977,2017-12-26 07:00:00,10H10,5900-5999,HARRISBURG,Burglary,auto repair,1,7,26,Tuesday,Dec,2017,5950,5950 HARRISBURG,"[{'address_components': [{'long_name': '5950',...",29.740018,-95.316495,"5950 Harrisburg Blvd, Houston, TX 77011, USA"
3977,3978,2017-12-26 09:00:00,10H10,5500-5599,HARRISBURG,Burglary,vehicle/auto sales/lease/auto parts store,1,9,26,Tuesday,Dec,2017,5550,5550 HARRISBURG,"[{'address_components': [{'long_name': '5550',...",29.741016,-95.319984,"5550 Harrisburg Blvd, Houston, TX 77011, USA"
3978,3979,2017-12-26 17:00:00,10H10,400-499,ENGEL ST,Aggravated Assault,road/street/sidewalk,1,17,26,Tuesday,Dec,2017,450,450 ENGEL ST,"[{'address_components': [{'long_name': '450', ...",29.749513,-95.320072,"450 Engel St, Houston, TX 77011, USA"
3979,3980,2017-12-27 08:00:00,10H10,400-499,COWLING ST,Theft,road/street/sidewalk,1,8,27,Wednesday,Dec,2017,450,450 COWLING ST,"[{'address_components': [{'long_name': '450', ...",29.739191,-95.316836,"450 Cowling St, Houston, TX 77011, USA"
3980,3981,2017-12-28 10:00:00,10H10,3300-3399,CANAL ST,Robbery,convenience store,1,10,28,Thursday,Dec,2017,3350,3350 CANAL ST,"[{'address_components': [{'long_name': '3350',...",29.752561,-95.338303,"3350 Canal St, Houston, TX 77003, USA"
3981,3982,2017-12-28 12:00:00,10H10,300-399,HUNT,Auto Theft,driveway,1,12,28,Thursday,Dec,2017,350,350 HUNT,"[{'address_components': [{'long_name': '350', ...",29.746025,-95.334668,"350 Hunt St, Houston, TX 77003, USA"
3982,3983,2017-12-28 12:00:00,10H10,2800-2899,NAVIGATION,Theft,restaurant/cafeteria parking lot,1,12,28,Thursday,Dec,2017,2850,2850 NAVIGATION,"[{'address_components': [{'long_name': '2850',...",29.756278,-95.341400,"2850 Navigation Blvd, Houston, TX 77003, USA"
3983,3984,2017-12-28 20:00:00,10H10,7900-7999,LAURA KOPPE,Robbery,road/street/sidewalk,1,20,28,Thursday,Dec,2017,7950,7950 LAURA KOPPE,"[{'address_components': [{'long_name': '7950',...",29.840329,-95.282279,"7950 Laura Koppe Rd, Houston, TX 77028, USA"
3984,3985,2017-12-30 06:00:00,10H10,2800-2899,NAVIGATION,Burglary,restaurant or cafeteria,1,6,30,Saturday,Dec,2017,2850,2850 NAVIGATION,"[{'address_components': [{'long_name': '2850',...",29.756278,-95.341400,"2850 Navigation Blvd, Houston, TX 77003, USA"
3985,3986,2017-12-31 11:00:00,10H10,400-499,N LIVE OAK ST,Theft,road/street/sidewalk,1,11,31,Sunday,Dec,2017,450,450 N LIVE OAK ST,"[{'address_components': [{'long_name': '450', ...",29.759400,-95.341881,"450 N Live Oak St, Houston, TX 77003, USA"
3986,3987,2017-12-31 18:00:00,10H10,2300-2399,COMMERCE ST,Theft,other parking lot,1,18,31,Sunday,Dec,2017,2350,2350 COMMERCE ST,"[{'address_components': [{'long_name': '2350',...",29.756351,-95.347639,"2350 Commerce St, Houston, TX 77003, USA"

In [100]:
df_10H10 = df_10H10[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'add']]

In [101]:
df_10H10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3987 entries, 0 to 3986
Data columns (total 13 columns):
Date_Hour      3987 non-null object
Beat           3987 non-null object
OffenseType    3987 non-null object
Premise        3987 non-null object
NumOffenses    3987 non-null int64
Hour           3987 non-null int64
day            3987 non-null int64
weekday        3987 non-null object
month          3987 non-null object
year           3987 non-null int64
lat            3987 non-null float64
lon            3987 non-null float64
add            3987 non-null object
dtypes: float64(2), int64(4), object(7)
memory usage: 405.0+ KB

In [102]:
df_10H10.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 00:00:00,10H10,Burglary,misc. business (non-specific),1,0,1,Friday,Jan,2010,29.743716,-95.332731,"550 Eastwood St, Houston, TX 77011, USA"
1,2010-01-01 06:00:00,10H10,Rape,residence/house,1,6,1,Friday,Jan,2010,29.755055,-95.348144,"2350 Sperber Ln, Houston, TX 77003, USA"
2,2010-01-01 17:00:00,10H10,Burglary,apartment,1,17,1,Friday,Jan,2010,29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
3,2010-01-01 20:00:00,10H10,Theft,road/street/sidewalk,1,20,1,Friday,Jan,2010,29.762874,-95.351209,"1950 Runnels St, Houston, TX 77002, USA"
4,2010-01-02 19:00:00,10H10,Burglary,residence/house,1,19,2,Saturday,Jan,2010,29.750896,-95.337716,"50 N York St, Houston, TX 77003, USA"

In [103]:
df_10H10.to_csv('crime_data_clean/df_10H10FINAL.csv')

# 1A10

In [47]:
path = 'crime_data_clean/crime_1A10_10_17LATLON.csv'
df_1A10 = pd.read_csv(path)

In [48]:
df_1A10

,Unnamed: 0,Date_Hour,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add,lat,lon,add
0,0,2010-01-01 00:00:00,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ...",29.757212,-95.353294,"350 Hamilton St, Houston, TX 77002, USA"
1,1,2010-01-01 00:00:00,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',...",29.753512,-95.363811,"1250 Caroline St, Houston, TX 77002, USA"
2,2,2010-01-01 00:00:00,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN,"[{'address_components': [{'long_name': '450', ...",29.760954,-95.362089,"450 S Main St, Houston, TX 77002, USA"
3,3,2010-01-01 00:00:00,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',...",29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
4,4,2010-01-01 00:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',...",29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701..."
5,5,2010-01-01 01:00:00,1A10,1200-1299,SAN JACINTO,Burglary,restaurant/cafeteria,1,1,1,Friday,Jan,2010,1250,1250 SAN JACINTO,"[{'address_components': [{'long_name': '1250',...",29.753827,-95.365190,"1250 San Jacinto St, Houston, TX 77002, USA"
6,6,2010-01-01 02:00:00,1A10,700-799,MAIN,Theft,bar/night club parking lot,1,2,1,Friday,Jan,2010,750,750 MAIN,"[{'address_components': [{'long_name': '750', ...",29.758682,-95.363866,"750 S Main St, Houston, TX 77002, USA"
7,7,2010-01-01 02:00:00,1A10,400-499,CAROLINE,Theft,road/street/sidewalk,1,2,1,Friday,Jan,2010,450,450 CAROLINE,"[{'address_components': [{'long_name': '450', ...",29.759401,-95.359398,"450 Caroline St, Houston, TX 77002, USA"
8,8,2010-01-01 06:00:00,1A10,1200-1299,TRAVIS,Auto Theft,auto repair,1,6,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',...",29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
9,9,2010-01-01 23:00:00,1A10,700-799,MAIN,Theft,bar/night club,1,23,1,Friday,Jan,2010,750,750 MAIN,"[{'address_components': [{'long_name': '750', ...",29.758682,-95.363866,"750 S Main St, Houston, TX 77002, USA"
10,10,2010-01-01 23:00:00,1A10,600-699,TEXAS,Burglary,"theatres,dinner theaters,auditor.",1,23,1,Friday,Jan,2010,650,650 TEXAS,"[{'address_components': [{'long_name': '650', ...",29.761574,-95.365701,"650 Texas St, Houston, TX 77002, USA"
11,11,2010-01-02 00:00:00,1A10,1000-1099,LOUISIANA,Theft,commercial building,1,0,2,Saturday,Jan,2010,1050,1050 LOUISIANA,"[{'address_components': [{'long_name': '1050',...",29.758122,-95.368310,"1050 Louisiana St, Houston, TX 77002, USA"
12,12,2010-01-02 00:00:00,1A10,100-199,TRAVIS,Theft,bar/night club,1,0,2,Saturday,Jan,2010,150,150 TRAVIS,"[{'address_components': [{'long_name': '150', ...",29.763859,-95.361350,"150 Travis St, Houston, TX 77002, USA"
13,13,2010-01-02 01:00:00,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,1,2,Saturday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',...",29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
14,14,2010-01-02 03:00:00,1A10,300-399,MAIN,Theft,apartment,1,3,2,Saturday,Jan,2010,350,350 MAIN,"[{'address_components': [{'long_name': '350', ...",29.761727,-95.361468,"350 S Main St, Houston, TX 77002, USA"
15,15,2010-01-02 14:00:00,1A10,1200-1299,TRAVIS,Theft,highway/freeway,1,14,2,Saturday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',...",29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
16,16,2010-01-02 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,14,2,Saturday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',...",29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701..."
17,17,2010-01-02 14:00:00,1A10,1400-1499,DALLAS,Auto Theft,road/street/sidewalk,1,14,2,Saturday,Jan,2010,1450,1450 DALLAS,"[{'address_components': [{'long_name': '1450',...",29.753138,-95.362235,"1450 Dallas St, Houston, TX 77002, USA"
18,18,2010-01-02 18:00:00,1A10,1600-1699,FANNIN,Theft,residence/house,1,18,2,Saturday,Jan,2010,1650,1650 FANNIN,"[{'address_components': [{'long_name': '1650',...",29.751411,-95.368310,"1650 Fannin St, Houston, TX 77002, USA"
19,19,2010-01-02 19:00:00,1A10,1200-1299,TEXAS,Burglary,jail/prison,1,19,2,Saturday,Jan,2010,1250,1250 TEXAS,"[{'address_components': [{'long_name': '1250',...",29.758311,-95.360323,"1250 Texas St, Houston, TX 77002, USA"
20,20,2010-01-02 19:00:00,1A10,700-799,SAN JACINTO,Theft,convenience store parking lot,1,19,2,Saturday,Jan,2010,750,750 SAN JACINTO,"[{'address_components': [{'long_name': '750', ...",29.757785,-95.362132,"750 San Jacinto St, Houston, TX 77002, USA"
21,21,2010-01-02 23:00:00,1A10,400-499,TRAVIS,Theft,commercial parking lot/garage,1,23,2,Saturday,Jan,2010,450,450 TRAVIS,"[{'address_components': [{'long_name': '450', ...",29.761720,-95.363098,"450 Travis St, Houston, TX 77002, USA"
22,22,2010-01-03 00:00:00,1A10,100-199,MAIN,Theft,bar/night club,1,0,3,Sunday,Jan,2010,150,150 MAIN,"[{'address_components': [{'long_name': '150', ...",29.763309,-95.360216,"150 S Main St, Houston, TX 77002, USA"
23,23,2010-01-03 00:00:00,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,3,Sunday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',...",29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
24,24,2010-01-03 12:00:00,1A10,1300-1399,BELL,Theft,residence/house,1,12,3,Sunday,Jan,2010,1350,1350 BELL,"[{'address_components': [{'long_name': '1350',...",29.751391,-95.364850,"1350 Bell St, Houston, TX 77002, USA"
25,25,2010-01-03 15:00:00,1A10,500-599,MCKINNEY,Theft,"libraries, museums",1,15,3,Sunday,Jan,2010,550,550 MCKINNEY,"[{'address_components': [{'long_name': '550', ...",29.758875,-95.369134,"550 McKinney St, Houston, TX 77002, USA"
26,26,2010-01-03 20:00:00,1A10,1000-1099,FRANKLIN,Theft,road/street/sidewalk,1,20,3,Sunday,Jan,2010,1050,1050 FRANKLIN,"[{'address_components': [{'long_name': '1050',...",29.762703,-95.359681,"1050 Franklin St, Houston, TX 77002, USA"
27,27,2010-01-03 22:00:00,1A10,1000-1099,CONGRESS,Theft,road/street/sidewalk,1,22,3,Sunday,Jan,2010,1050,1050 CONGRESS,"[{'address_components': [{'long_name': '1050',...",29.761684,-95.360146,"1050 Congress Ave, Houston, TX 77002, USA"
28,28,2010-01-03 22:00:00,1A10,1300-1399,TEXAS,Theft,road/street/sidewalk,1,22,3,Sunday,Jan,2010,1350,1350 TEXAS,"[{'address_components': [{'long_name': '1350',...",29.757678,-95.359496,"1350 Texas St, Houston, TX 77002, USA"
29,29,2010-01-03 23:00:00,1A10,300-399,TRAVIS,Auto Theft,road/street/sidewalk,1,23,3,Sunday,Jan,2010,350,350 TRAVIS,"[{'address_components': [{'long_name': '350', ...",29.762405,-95.361940,"350 Travis St, Houston, TX 77002, USA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14904,14948,2017-12-22 14:00:00,1A10,1500-1599,POLK,Theft,"stadium, sports arena, race track",1,14,22,Friday,Dec,2017,1550,1550 POLK,"[{'address_components': [{'long_name': '1550',...",29.751457,-95.361924,"1550 Polk St, Houston, TX 77002, USA"
14905,14949,2017-12-22 15:00:00,1A10,1300-1399,CLAY ST,Theft,other parking lot,1,15,22,Friday,Dec,2017,1350,1350 CLAY ST,"[{'address_components': [{'long_name': '1350',...",29.752124,-95.364242,"1350 Clay St, Houston, TX 77002, USA"
14906,14950,2017-12-23 16:00:00,1A10,1800-1899,RUIZ,Theft,"other, unknown, or not listed",1,16,23,Saturday,Dec,2017,1850,1850 RUIZ,"[{'address_components': [{'long_name': '1850',...",29.759994,-95.351410,"1850 Ruiz St, Houston, TX 77002, USA"
14907,14951,2017-12-23 16:00:00,1A10,1700-1799,JEFFERSON ST,Auto Theft,liquor store parking lot,1,16,23,Saturday,Dec,2017,1750,1750 JEFFERSON ST,"[{'address_components': [{'long_name': '1750',...",29.746821,-95.363352,"1750 Jefferson St, Houston, TX 77003, USA"
14908,14952,2017-12-24 00:00:00,1A10,700-799,CRAWFORD ST,Theft,"hotel, motel, inn, etc.",1,0,24,Sunday,Dec,2017,750,750 CRAWFORD ST,"[{'address_components': [{'long_name': '750', ...",29.755586,-95.358684,"750 Crawford St, Houston, TX 77002, USA"
14909,14953,2017-12-24 01:00:00,1A10,500-599,MAIN ST,Theft,road/street/sidewalk,1,1,24,Sunday,Dec,2017,550,550 MAIN ST,"[{'address_components': [{'long_name': '550', ...",29.770634,-95.358926,"550 N Main St, Houston, TX 77002, USA"
14910,14954,2017-12-24 14:00:00,1A10,1300-1399,TRAVIS ST,Theft,other parking lot,1,14,24,Sunday,Dec,2017,1350,1350 TRAVIS ST,"[{'address_components': [{'long_name': '1350',...",29.754859,-95.368477,"1350 Travis St, Houston, TX 77002, USA"
14911,14955,2017-12-24 20:00:00,1A10,100-199,FANNIN ST,Theft,road/street/sidewalk,1,20,24,Sunday,Dec,2017,150,150 FANNIN ST,"[{'address_components': [{'long_name': '150', ...",29.762799,-95.359038,"150 Fannin St, Houston, TX 77002, USA"
14912,14956,2017-12-25 14:00:00,1A10,1100-1199,COMMERCE ST,Theft,road/street/sidewalk,1,14,25,Monday,Dec,2017,1150,1150 COMMERCE ST,"[{'address_components': [{'long_name': '1150',...",29.762897,-95.358144,"1150 Commerce St, Houston, TX 77002, USA"
14913,14957,2017-12-25 14:00:00,1A10,1100-1199,PEASE ST,Theft,commercial parking lot or garage,1,14,25,Monday,Dec,2017,1150,1150 PEASE ST,"[{'address_components': [{'long_name': '1150',...",29.750573,-95.368056,"1150 Pease St, Houston, TX 77002, USA"
14914,14958,2017-12-26 06:00:00,1A10,6700-6799,SATSUMA,Burglary,construction site,1,6,26,Tuesday,Dec,2017,6750,6750 SATSUMA,"[{'address_components': [{'long_name': '6750',...",29.875142,-95.601878,"6750 Satsuma Dr, Houston, TX 77041, USA"
14915,14959,2017-12-26 12:00:00,1A10,400-499,SAN JACINTO,Theft,restaurant or cafeteria,1,12,26,Tuesday,Dec,2017,450,450 SAN JACINTO,"[{'address_components': [{'long_name': '450', ...",29.760124,-95.360222,"450 San Jacinto St, Houston, TX 77002, USA"
14916,14960,2017-12-26 13:00:00,1A10,500-599,FANNIN ST,Auto Theft,road/street/sidewalk,1,13,26,Tuesday,Dec,2017,550,550 FANNIN ST,"[{'address_components': [{'long_name': '550', ...",29.759671,-95.361786,"550 Fannin St, Houston, TX 77002, USA"
14917,14961,2017-12-27 11:00:00,1A10,1600-1699,SMITH ST,Aggravated Assault,bank,1,11,27,Wednesday,Dec,2017,1650,1650 SMITH ST,"[{'address_components': [{'long_name': '1650',...",29.754294,-95.372906,"1650 Smith St, Houston, TX 77002, USA"
14918,14962,2017-12-27 15:00:00,1A10,1100-1199,MAIN ST,Theft,road/street/sidewalk,1,15,27,Wednesday,Dec,2017,1150,1150 MAIN ST,"[{'address_components': [{'long_name': '1150',...",29.756040,-95.366302,"1150 S Main St, Houston, TX 77002, USA"
14919,14963,2017-12-27 18:00:00,1A10,1100-1199,FANNIN ST,Theft,commercial parking lot or garage,1,18,27,Wednesday,Dec,2017,1150,1150 FANNIN ST,"[{'address_components': [{'long_name': '1150',...",29.755077,-95.365240,"1150 Fannin St, Houston, TX 77002, USA"
14920,14964,2017-12-27 23:00:00,1A10,2400-2499,SHOREBROOK,Theft,road/street/sidewalk,1,23,27,Wednesday,Dec,2017,2450,2450 SHOREBROOK,[{'address_components': [{'long_name': 'Shoreb...,29.900468,-95.623985,"Shorebrook Dr, Houston, TX 77095, USA"
14921,14965,2017-12-28 10:00:00,1A10,700-799,CRAWFORD ST,Theft,"hotel, motel, inn, etc.",1,10,28,Thursday,Dec,2017,750,750 CRAWFORD ST,"[{'address_components': [{'long_name': '750', ...",29.755586,-95.358684,"750 Crawford St, Houston, TX 77002, USA"
14922,14966,2017-12-28 13:00:00,1A10,700-799,N SAN JACINTO ST,Theft,road/street/sidewalk,1,13,28,Thursday,Dec,2017,750,750 N SAN JACINTO ST,"[{'address_components': [{'long_name': '750', ...",29.764627,-95.357128,"750 N San Jacinto St, Houston, TX 77002, USA"
14923,14967,2017-12-29 02:00:00,1A10,1600-1699,FANNIN ST,Aggravated Assault,apartment,1,2,29,Friday,Dec,2017,1650,1650 FANNIN ST,"[{'address_components': [{'long_name': '1650',...",29.751411,-95.368310,"1650 Fannin St, Houston, TX 77002, USA"
14924,14968,2017-12-29 09:00:00,1A10,800-899,TRAVIS ST,Theft,garage or carport,1,9,29,Friday,Dec,2017,850,850 TRAVIS ST,"[{'address_components': [{'long_name': '850', ...",29.758513,-95.365254,"850 Travis St, Houston, TX 77002, USA"
14925,14969,2017-12-29 10:00:00,1A10,10600-10699,MAIN,Theft,rental storage facility,1,10,29,Friday,Dec,2017,10650,10650 MAIN,[{'address_components': [{'long_name': '10650'...,29.673019,-95.431014,"10650 S Main St, Houston, TX 77054, USA"
14926,14970,2017-12-29 10:00:00,1A10,12600-12699,MONACO,Auto Theft,road/street/sidewalk,1,10,29,Friday,Dec,2017,12650,12650 MONACO,"[{'address_components': [{'long_name': '8333',...",29.692994,-95.417079,"8333 Braesmain Dr, Houston, TX 77025, USA"
14927,14971,2017-12-29 16:00:00,1A10,900-999,COMMERCE ST,Auto Theft,commercial parking lot or garage,1,16,29,Friday,Dec,2017,950,950 COMMERCE ST,"[{'address_components': [{'long_name': '950', ...",29.763832,-95.360101,"950 Commerce St, Houston, TX 77002, USA"
14928,14972,2017-12-30 11:00:00,1A10,6700-6799,MOBILE HOME,Theft,commercial parking lot or garage,1,11,30,Saturday,Dec,2017,6750,6750 MOBILE HOME,"[{'address_components': [{'long_name': '28', '...",30.050840,-95.186626,"4321 Kingwood Dr #28, Kingwood, TX 77339, USA"
14929,14973,2017-12-30 15:00:00,1A10,1800-1899,ST JOSEPH PKWY,Theft,apartment,1,15,30,Saturday,Dec,2017,1850,1850 ST JOSEPH PKWY,"[{'address_components': [{'long_name': '1850',...",29.745560,-95.362803,"1850 St Joseph Pkwy, Houston, TX 77003, USA"
14930,14974,2017-12-31 02:00:00,1A10,1500-1599,DALLAS ST,Aggravated Assault,"hotel, motel, inn, etc.",1,2,31,Sunday,Dec,2017,1550,1550 DALLAS ST,"[{'address_components': [{'long_name': '1550',...",29.752417,-95.361416,"1550 Dallas St, Houston, TX 77002, USA"
14931,14975,2017-12-31 16:00:00,1A10,900-999,PIERCE ST,Robbery,bus stop,1,16,31,Sunday,Dec,2017,950,950 PIERCE ST,"[{'address_components': [{'long_name': '950', ...",29.749452,-95.370759,"950 Pierce St, Houston, TX 77002, USA"
14932,14976,2017-12-31 17:00:00,1A10,14900-14999,MONRAD,Theft,commercial parking lot or garage,1,17,31,Sunday,Dec,2017,14950,14950 MONRAD,[{'address_components': [{'long_name': '14950'...,29.609287,-95.442111,"14950 Monrad Dr, Houston, TX 77053, USA"
14933,14977,2017-12-31 22:00:00,1A10,700-799,WALNUT ST,Auto Theft,road/street/sidewalk,1,22,31,Sunday,Dec,2017,750,750 WALNUT ST,"[{'address_components': [{'long_name': '750', ...",29.767134,-95.354628,"750 Walnut St, Houston, TX 77002, USA"

In [50]:
df_1A10 = df_1A10[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'add']]

In [51]:
df_1A10.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 00:00:00,1A10,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,29.757212,-95.353294,"350 Hamilton St, Houston, TX 77002, USA"
1,2010-01-01 00:00:00,1A10,Theft,bar/night club,1,0,1,Friday,Jan,2010,29.753512,-95.363811,"1250 Caroline St, Houston, TX 77002, USA"
2,2010-01-01 00:00:00,1A10,Burglary,office building,1,0,1,Friday,Jan,2010,29.760954,-95.362089,"450 S Main St, Houston, TX 77002, USA"
3,2010-01-01 00:00:00,1A10,Theft,other/unknown,1,0,1,Friday,Jan,2010,29.755595,-95.367677,"1250 Travis St, Houston, TX 77002, USA"
4,2010-01-01 00:00:00,1A10,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,29.752015,-95.359181,"1050 Avenida De Las Americas, Houston, TX 7701..."

In [52]:
df_1A10.to_csv('crime_data_clean/df_1A10FINAL.csv')

## 10H70

In [62]:
ls crime_data_clean/

beats_alternate_10_17.csv*      crime_10H70_10_17df_1000.csv*
beats_filter_10_17.csv*         crime_10H70_10_17df_2000.csv*
crime_10H10_10_17ADD.csv*       crime_10H70_10_17df_3000.csv*
crime_10H10_10_17.csv*          crime_10H70_10_17df_4000.csv*
crime_10H10_10_17df_1000.csv*   crime_10H70_10_17df_5000.csv*
crime_10H10_10_17df_2000.csv*   crime_10H70_10_17df_6000.csv*
crime_10H10_10_17df_3000.csv*   crime_10H70_10_17df_7000.csv*
crime_10H10_10_17df_4000.csv*   crime_10H70_10_17df_8000.csv*
crime_10H30_10_17ADD.csv*       crime_10H70_10_17df_9000.csv*
crime_10H30_10_17.csv*          crime_10H80_10_17ADD.csv*
crime_10H30_10_17FINAL.csv*     crime_10H80_10_17.csv*
crime_10H40_10_17ADD.csv*       crime_10H80_10_17FINAL.csv*
crime_10H40_10_17.csv*          crime_15E40_10_17ADD.csv*
crime_10H40_10_17df_10000.csv*  crime_15E40_10_17.csv*
crime_10H40_10_17df_1000.csv*   crime_15E40_10_17df_12000.csv*
crime_10H40_10_17df_2000.csv*   crime_15E40_10_17df_16281.csv*
crime_10H40_10_17df_3000.csv*   crime_15E40_10_17df_4000.csv*
crime_10H40_10_17df_4000.csv*   crime_15E40_10_17df_8000.csv*
crime_10H40_10_17df_5000.csv*   crime_15E40_10_17FINAL.csv*
crime_10H40_10_17df_6000.csv*   crime_1A10_10_17ADD.csv*
crime_10H40_10_17df_7000.csv*   crime_1A10_10_17.csv*
crime_10H40_10_17df_8000.csv*   crime_1A10_10_17df_14978.csv*
crime_10H40_10_17df_9000.csv*   crime_1A10_10_17df_4000.csv*
crime_10H40_10_17LATLON.csv*    crime_1A10_10_17df_8000.csv*
crime_10H50_10_17ADD.csv*       crime_1A10_10_17df_p1.csv*
crime_10H50_10_17.csv*          crime_1A10_10_17df_p2.csv*
crime_10H50_10_17FINAL.csv*     crime_1A10_10_17df_p3.csv*
crime_10H60_10_17ADD.csv*       crime_1A10_10_17df_p4.csv*
crime_10H60_10_17.csv*          crime_1A10_10_17FINAL.csv*
crime_10H60_10_17df_1000.csv*   crime_1A10_10_17LATLON.csv*
crime_10H60_10_17df_2000.csv*   crime_final_clean10_17.csv*
crime_10H60_10_17df_3000.csv*   df_10H10FINAL.csv*
crime_10H60_10_17df_4000.csv*   df_10H40FINAL.csv*
crime_10H60_10_17df_5000.csv*   df_10H60FINAL.csv*
crime_10H60_10_17df_6000.csv*   df_1A10FINAL.csv*
crime_10H60_10_17df_7000.csv*   new/
crime_10H60_10_17LATLON.csv*    stadium_beats_geocode.csv*
crime_10H70_10_17ADD.csv*       stadiums_final.csv*
crime_10H70_10_17.csv*          years/
crime_10H70_10_17df_10000.csv*

In [63]:
path = 'crime_data_clean/crime_10H70_10_17ADD.csv'
df_10H70 = pd.read_csv(path)

In [65]:
df_10H70.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11109 entries, 0 to 11108
Data columns (total 19 columns):
Unnamed: 0     11109 non-null int64
Date_Hour      11109 non-null object
Beat           11109 non-null object
BlockRange     11109 non-null object
StreetName     11109 non-null object
OffenseType    11109 non-null object
Premise        11109 non-null object
NumOffenses    11109 non-null int64
Hour           11109 non-null int64
day            11109 non-null int64
weekday        11109 non-null object
month          11109 non-null object
year           11109 non-null int64
block          11109 non-null int64
address        11109 non-null object
tup_add        11109 non-null object
lat            11109 non-null float64
lon            11109 non-null float64
add            11109 non-null object
dtypes: float64(2), int64(6), object(11)
memory usage: 1.6+ MB

In [66]:
df_10H70.head()

,Unnamed: 0,Date_Hour,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add,lat,lon,add
0,0,2010-01-01 19:00:00,10H70,6500-6599,FANNIN,Aggravated Assault,hospital,1,19,1,Friday,Jan,2010,6550,6550 FANNIN,"[{'address_components': [{'long_name': '6550',...",29.711448,-95.399988,"6550 Fannin St, Houston, TX 77030, USA"
1,1,2010-01-01 21:00:00,10H70,4800-4899,AUSTIN,Burglary,residence/house,1,21,1,Friday,Jan,2010,4850,4850 AUSTIN,"[{'address_components': [{'long_name': '4850',...",29.728541,-95.382676,"4850 Austin St, Houston, TX 77004, USA"
2,2,2010-01-01 23:00:00,10H70,1900-1999,WENTWORTH,Aggravated Assault,residence/house,1,23,1,Friday,Jan,2010,1950,1950 WENTWORTH,"[{'address_components': [{'long_name': '1950',...",29.726239,-95.376586,"1950 Wentworth St, Houston, TX 77004, USA"
3,3,2010-01-02 15:00:00,10H70,6600-6699,FANNIN,Theft,hospital,1,15,2,Saturday,Jan,2010,6650,6650 FANNIN,"[{'address_components': [{'long_name': '6650',...",29.707713,-95.403292,"6650 Fannin St, Houston, TX 77030, USA"
4,4,2010-01-02 15:00:00,10H70,6400-6499,FANNIN,Theft,hospital,1,15,2,Saturday,Jan,2010,6450,6450 FANNIN,"[{'address_components': [{'long_name': '6450',...",29.712163,-95.399011,"6450 Fannin St, Houston, TX 77030, USA"

In [69]:
df_10H70 = df_10H70[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'add']]

In [70]:
df_10H70.to_csv('crime_data_clean/df_10H70FINAL.csv')

In [71]:
df_10H70.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,add
0,2010-01-01 19:00:00,10H70,Aggravated Assault,hospital,1,19,1,Friday,Jan,2010,29.711448,-95.399988,"6550 Fannin St, Houston, TX 77030, USA"
1,2010-01-01 21:00:00,10H70,Burglary,residence/house,1,21,1,Friday,Jan,2010,29.728541,-95.382676,"4850 Austin St, Houston, TX 77004, USA"
2,2010-01-01 23:00:00,10H70,Aggravated Assault,residence/house,1,23,1,Friday,Jan,2010,29.726239,-95.376586,"1950 Wentworth St, Houston, TX 77004, USA"
3,2010-01-02 15:00:00,10H70,Theft,hospital,1,15,2,Saturday,Jan,2010,29.707713,-95.403292,"6650 Fannin St, Houston, TX 77030, USA"
4,2010-01-02 15:00:00,10H70,Theft,hospital,1,15,2,Saturday,Jan,2010,29.712163,-95.399011,"6450 Fannin St, Houston, TX 77030, USA"

# 10H30

In [1]:
path = 'crime_data_clean/crime_10H30_10_17FINAL.csv'
df2 = pd.read_csv(path)
#df2.drop(['Unnamed: 0'],axis=1,inplace=True)
df2.head(2)

NameError: name 'pd' is not defined

In [88]:
df2[['lat','lon']]= df2['lat_lon'].str.extract(r"\((.*?)\)", expand=False).str.split(',',expand=True)

In [89]:
df2[['lat','lon']].dtypes

lat    object
lon    object
dtype: object

In [90]:
df2[['lat','lon']].dtypes

lat    object
lon    object
dtype: object

In [91]:
df2['lat'] =  pd.to_numeric(df2['lat'])
df2['lon'] =  pd.to_numeric(df2['lon'])

In [92]:
df2[['lat','lon']].dtypes

lat    float64
lon    float64
dtype: object

In [94]:
df2.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address,lat,lon
0,2010-01-01 00:00:00,10H30,Theft,residence/house,1,0,1,Friday,Jan,2010,"(29.7390659, -95.34897509999999)","1750 Sampson St, Houston, TX 77003, USA",29.739066,-95.348975
1,2010-01-01 19:00:00,10H30,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,"(29.7536483, -95.3510778)","550 Bastrop St, Houston, TX 77003, USA",29.753648,-95.351078

In [95]:
df_10H30 = df2[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'full_address']]

In [84]:
df2.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,full_address
0,2010-01-01 00:00:00,10H30,Theft,residence/house,1,0,1,Friday,Jan,2010,29.739066,-95.348975,"1750 Sampson St, Houston, TX 77003, USA"
1,2010-01-01 19:00:00,10H30,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,29.753648,-95.351078,"550 Bastrop St, Houston, TX 77003, USA"
2,2010-01-01 20:00:00,10H30,Theft,residence/house,1,20,1,Friday,Jan,2010,29.745298,-95.359324,"1750 Hutchins St, Houston, TX 77003, USA"
3,2010-01-02 01:00:00,10H30,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,29.746607,-95.359335,"2050 Leeland St, Houston, TX 77003, USA"
4,2010-01-03 04:00:00,10H30,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,29.758830,-95.351403,"1950 Commerce St, Houston, TX 77002, USA"

In [96]:
df_10H30.to_csv('crime_data_clean/df_10H30FINAL.csv')

In [97]:
df_10H30.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,full_address
0,2010-01-01 00:00:00,10H30,Theft,residence/house,1,0,1,Friday,Jan,2010,29.739066,-95.348975,"1750 Sampson St, Houston, TX 77003, USA"
1,2010-01-01 19:00:00,10H30,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,29.753648,-95.351078,"550 Bastrop St, Houston, TX 77003, USA"
2,2010-01-01 20:00:00,10H30,Theft,residence/house,1,20,1,Friday,Jan,2010,29.745298,-95.359324,"1750 Hutchins St, Houston, TX 77003, USA"
3,2010-01-02 01:00:00,10H30,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,29.746607,-95.359335,"2050 Leeland St, Houston, TX 77003, USA"
4,2010-01-03 04:00:00,10H30,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,29.758830,-95.351403,"1950 Commerce St, Houston, TX 77002, USA"

# 10H50

In [4]:
path = 'crime_data_clean/crime_10H50_10_17FINAL.csv'
df3 = pd.read_csv(path)
#df2.drop(['Unnamed: 0'],axis=1,inplace=True)
df3.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address
0,2010-01-01 09:00:00,10H50,Theft,residence/house,1,9,1,Friday,Jan,2010,"(29.731311, -95.36411439999999)","3450 Nagle St, Houston, TX 77004, USA"
1,2010-01-01 12:00:00,10H50,Burglary,"vacant single occupancy residence (houses,town...",1,12,1,Friday,Jan,2010,"(29.728306, -95.36597750000001)","2650 Truxillo St, Houston, TX 77004, USA"

In [5]:
df3[['lat','lon']]= df3['lat_lon'].str.extract(r"\((.*?)\)", expand=False).str.split(',',expand=True)

In [6]:
df3[['lat','lon']].dtypes

lat    object
lon    object
dtype: object

In [7]:
df3['lat'] =  pd.to_numeric(df3['lat'])
df3['lon'] =  pd.to_numeric(df3['lon'])

In [8]:
df3[['lat','lon']].dtypes

lat    float64
lon    float64
dtype: object

In [9]:
df3.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address,lat,lon
0,2010-01-01 09:00:00,10H50,Theft,residence/house,1,9,1,Friday,Jan,2010,"(29.731311, -95.36411439999999)","3450 Nagle St, Houston, TX 77004, USA",29.731311,-95.364114
1,2010-01-01 12:00:00,10H50,Burglary,"vacant single occupancy residence (houses,town...",1,12,1,Friday,Jan,2010,"(29.728306, -95.36597750000001)","2650 Truxillo St, Houston, TX 77004, USA",29.728306,-95.365977

In [111]:
df_10H50 = df3[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'full_address']]

In [113]:
df_10H50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9155 entries, 0 to 9154
Data columns (total 13 columns):
Date_Hour       9155 non-null object
Beat            9155 non-null object
OffenseType     9155 non-null object
Premise         9155 non-null object
NumOffenses     9155 non-null int64
Hour            9155 non-null int64
day             9155 non-null int64
weekday         9155 non-null object
month           9155 non-null object
year            9155 non-null int64
lat             9155 non-null float64
lon             9155 non-null float64
full_address    9155 non-null object
dtypes: float64(2), int64(4), object(7)
memory usage: 929.9+ KB

In [114]:
df_10H50.to_csv('crime_data_clean/df_10H50FINAL.csv')

# 15E40

In [25]:
path = 'crime_data_clean/crime_15E40_10_17FINAL.csv'
df4 = pd.read_csv(path)
#df2.drop(['Unnamed: 0'],axis=1,inplace=True)
df4.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address
0,2010-01-01 23:00:00,1.500000e+41,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6823316, -95.4169951)","2550 Westridge St, Houston, TX 77054, USA"
1,2010-01-01 23:00:00,1.500000e+41,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6845315, -95.40031289999999)","8350 Knight Rd, Houston, TX 77054, USA"

In [26]:
df4.Beat = '15E40x'
df4.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address
0,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6823316, -95.4169951)","2550 Westridge St, Houston, TX 77054, USA"
1,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6845315, -95.40031289999999)","8350 Knight Rd, Houston, TX 77054, USA"

In [27]:
df4.lat_lon.value_counts(dropna=False)

(29.68949839999999, -95.4136259)           1223
(29.6904116, -95.4176631)                   671
(29.6899253, -95.4143501)                   545
(29.6851906, -95.3985319)                   494
(29.7604267, -95.3698028)                   465
(29.6820484, -95.38725389999999)            456
(29.6890022, -95.3990941)                   405
(29.6810444, -95.4221614)                   386
(29.6821382, -95.41636129999999)            385
(29.6814768, -95.4253667)                   378
(29.67808119999999, -95.41922129999999)     343
(29.6745626, -95.4248057)                   340
(29.6694014, -95.4201861)                   340
(29.6856544, -95.4256395)                   316
(29.680448, -95.42042839999999)             310
(29.6869435, -95.40331019999999)            299
(29.68490329999999, -95.3970744)            263
(29.6823316, -95.4169951)                   260
(29.6826402, -95.4202601)                   258
(29.6986054, -95.4032943)                   257
(29.6875677, -95.3964961)                   254
(29.68759009999999, -95.4213276)            253
(29.6678401, -95.38704899999999)            236
(29.678717, -95.42544389999999)             226
(29.6803376, -95.4124038)                   225
(29.6948485, -95.41553979999999)            222
(29.6834862, -95.4243652)                   221
(29.6931889, -95.4110869)                   220
(29.8082368, -95.44456679999999)            219
(29.6852115, -95.41982650000001)            216
                                           ...
(29.6312843, -95.14793039999999)              1
(29.7799384, -95.3821819)                     1
(29.6696657, -95.4892716)                     1
(29.733587, -95.4741153)                      1
(29.6986468, -95.4147775)                     1
(29.6775992, -95.6444301)                     1
(29.6984041, -95.4054544)                     1
(29.6722387, -95.45788789999999)              1
(29.6624941, -95.43773449999999)              1
(29.7477837, -95.413499)                      1
(29.6654287, -95.3262014)                     1
(29.9783337, -95.1523623)                     1
(29.6264351, -95.4365591)                     1
(29.6838602, -95.4269118)                     1
(29.9168647, -95.6450582)                     1
(29.86011, -95.69774799999999)                1
(29.6940459, -95.3639532)                     1
(29.7123351, -95.5519776)                     1
(29.7131377, -95.39368879999999)              1
(29.6744683, -95.3948064)                     1
(29.6357456, -95.4778831)                     1
(29.7089074, -95.36753399999999)              1
(29.5628884, -95.11442129999999)              1
(29.6887178, -95.3905317)                     1
(29.6011131, -95.2708511)                     1
(29.66239509999999, -95.4399033)              1
(29.6945414, -95.4395983)                     1
(29.5766587, -95.1173065)                     1
(29.6018872, -95.4888191)                     1
(29.9868623, -95.5043783)                     1
Name: lat_lon, Length: 702, dtype: int64

In [28]:
df4[['lat','lon']]= df4['lat_lon'].str.extract(r"\((.*?)\)", expand=False).str.split(',',expand=True)
df4[['lat','lon']].dtypes

lat    object
lon    object
dtype: object

In [29]:
df4['lat'] =  pd.to_numeric(df4['lat'])
df4['lon'] =  pd.to_numeric(df4['lon'])

In [30]:
df4[['lat','lon']].dtypes

lat    float64
lon    float64
dtype: object

In [31]:
df4.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address,lat,lon
0,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6823316, -95.4169951)","2550 Westridge St, Houston, TX 77054, USA",29.682332,-95.416995
1,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,"(29.6845315, -95.40031289999999)","8350 Knight Rd, Houston, TX 77054, USA",29.684531,-95.400313

In [32]:
df_15E40 = df4[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'full_address']]

In [33]:
df_15E40.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,full_address
0,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,29.682332,-95.416995,"2550 Westridge St, Houston, TX 77054, USA"
1,2010-01-01 23:00:00,15E40x,Aggravated Assault,apartment,1,23,1,Friday,Jan,2010,29.684531,-95.400313,"8350 Knight Rd, Houston, TX 77054, USA"
2,2010-01-01 23:00:00,15E40x,Theft,convenience store,1,23,1,Friday,Jan,2010,29.682332,-95.416995,"2550 Westridge St, Houston, TX 77054, USA"
3,2010-01-01 23:00:00,15E40x,Theft,convenience store,1,23,1,Friday,Jan,2010,29.684531,-95.400313,"8350 Knight Rd, Houston, TX 77054, USA"
4,2010-01-02 00:00:00,15E40x,Theft,other/unknown,1,0,2,Saturday,Jan,2010,29.685654,-95.425640,"3050 Murworth Dr, Houston, TX 77025, USA"

In [34]:
df_15E40.to_csv('crime_data_clean/df_15E40FINAL.csv')

In [35]:
ls crime_data_clean

beats_alternate_10_17.csv*      crime_10H70_10_17df_3000.csv*
beats_filter_10_17.csv*         crime_10H70_10_17df_4000.csv*
crime_10H10_10_17ADD.csv*       crime_10H70_10_17df_5000.csv*
crime_10H10_10_17.csv*          crime_10H70_10_17df_6000.csv*
crime_10H10_10_17df_1000.csv*   crime_10H70_10_17df_7000.csv*
crime_10H10_10_17df_2000.csv*   crime_10H70_10_17df_8000.csv*
crime_10H10_10_17df_3000.csv*   crime_10H70_10_17df_9000.csv*
crime_10H10_10_17df_4000.csv*   crime_10H80_10_17ADD.csv*
crime_10H30_10_17ADD.csv*       crime_10H80_10_17.csv*
crime_10H30_10_17.csv*          crime_10H80_10_17FINAL.csv*
crime_10H30_10_17FINAL.csv*     crime_15E40_10_17ADD.csv*
crime_10H40_10_17ADD.csv*       crime_15E40_10_17.csv*
crime_10H40_10_17.csv*          crime_15E40_10_17df_12000.csv*
crime_10H40_10_17df_10000.csv*  crime_15E40_10_17df_16281.csv*
crime_10H40_10_17df_1000.csv*   crime_15E40_10_17df_4000.csv*
crime_10H40_10_17df_2000.csv*   crime_15E40_10_17df_8000.csv*
crime_10H40_10_17df_3000.csv*   crime_15E40_10_17FINAL.csv*
crime_10H40_10_17df_4000.csv*   crime_1A10_10_17ADD.csv*
crime_10H40_10_17df_5000.csv*   crime_1A10_10_17.csv*
crime_10H40_10_17df_6000.csv*   crime_1A10_10_17df_14978.csv*
crime_10H40_10_17df_7000.csv*   crime_1A10_10_17df_4000.csv*
crime_10H40_10_17df_8000.csv*   crime_1A10_10_17df_8000.csv*
crime_10H40_10_17df_9000.csv*   crime_1A10_10_17df_p1.csv*
crime_10H40_10_17LATLON.csv*    crime_1A10_10_17df_p2.csv*
crime_10H50_10_17ADD.csv*       crime_1A10_10_17df_p3.csv*
crime_10H50_10_17.csv*          crime_1A10_10_17df_p4.csv*
crime_10H50_10_17FINAL.csv*     crime_1A10_10_17FINAL.csv*
crime_10H60_10_17ADD.csv*       crime_1A10_10_17LATLON.csv*
crime_10H60_10_17.csv*          crime_final_clean10_17.csv*
crime_10H60_10_17df_1000.csv*   df_10H10FINAL.csv*
crime_10H60_10_17df_2000.csv*   df_10H30FINAL.csv*
crime_10H60_10_17df_3000.csv*   df_10H40FINAL.csv*
crime_10H60_10_17df_4000.csv*   df_10H50FINAL.csv*
crime_10H60_10_17df_5000.csv*   df_10H60FINAL.csv*
crime_10H60_10_17df_6000.csv*   df_10H70FINAL.csv*
crime_10H60_10_17df_7000.csv*   df_15E40FINAL.csv*
crime_10H60_10_17LATLON.csv*    df_1A10FINAL.csv*
crime_10H70_10_17ADD.csv*       new/
crime_10H70_10_17.csv*          stadium_beats_geocode.csv*
crime_10H70_10_17df_10000.csv*  stadiums_final.csv*
crime_10H70_10_17df_1000.csv*   years/
crime_10H70_10_17df_2000.csv*

# 10H80_

In [36]:
path = 'crime_data_clean/crime_10H80_10_17FINAL.csv'
df5 = pd.read_csv(path)
#df2.drop(['Unnamed: 0'],axis=1,inplace=True)
df5.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address
0,2010-01-03 16:00:00,10H80,Theft,"gym,recreat,club hse,indr pool,spa",1,16,3,Sunday,Jan,2010,"(29.781236, -95.3678655)","2450 South St, Houston, TX 77009, USA"
1,2010-01-03 17:00:00,10H80,Burglary,"garden supply, nursery, florist",1,17,3,Sunday,Jan,2010,"(29.7193942, -95.4151567)","5150 Morningside Dr, Houston, TX 77005, USA"

In [37]:
df5[['lat','lon']]= df5['lat_lon'].str.extract(r"\((.*?)\)", expand=False).str.split(',',expand=True)
df5[['lat','lon']].dtypes

lat    object
lon    object
dtype: object

In [38]:
df5['lat'] =  pd.to_numeric(df5['lat'])
df5['lon'] =  pd.to_numeric(df5['lon'])

In [39]:
df5[['lat','lon']].dtypes

lat    float64
lon    float64
dtype: object

In [40]:
df5.head(2)

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address,lat,lon
0,2010-01-03 16:00:00,10H80,Theft,"gym,recreat,club hse,indr pool,spa",1,16,3,Sunday,Jan,2010,"(29.781236, -95.3678655)","2450 South St, Houston, TX 77009, USA",29.781236,-95.367866
1,2010-01-03 17:00:00,10H80,Burglary,"garden supply, nursery, florist",1,17,3,Sunday,Jan,2010,"(29.7193942, -95.4151567)","5150 Morningside Dr, Houston, TX 77005, USA",29.719394,-95.415157

In [41]:
df_10H80 = df5[[
 'Date_Hour',
 'Beat',
 'OffenseType',
 'Premise',
 'NumOffenses',
 'Hour',
 'day',
 'weekday',
 'month',
 'year',
 'lat',
 'lon',
 'full_address']]

In [42]:
df_10H80.head()

,Date_Hour,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat,lon,full_address
0,2010-01-03 16:00:00,10H80,Theft,"gym,recreat,club hse,indr pool,spa",1,16,3,Sunday,Jan,2010,29.781236,-95.367866,"2450 South St, Houston, TX 77009, USA"
1,2010-01-03 17:00:00,10H80,Burglary,"garden supply, nursery, florist",1,17,3,Sunday,Jan,2010,29.719394,-95.415157,"5150 Morningside Dr, Houston, TX 77005, USA"
2,2010-01-03 22:00:00,10H80,Theft,driveway,1,22,3,Sunday,Jan,2010,29.728945,-95.405608,"1850 Milford St, Houston, TX 77098, USA"
3,2010-01-03 22:00:00,10H80,Theft,driveway,1,22,3,Sunday,Jan,2010,29.730343,-95.406391,"1950 Vassar St, Houston, TX 77098, USA"
4,2010-01-03 22:00:00,10H80,Theft,driveway,1,22,3,Sunday,Jan,2010,29.728945,-95.405608,"1850 Milford St, Houston, TX 77098, USA"

In [43]:
df_10H80.to_csv('crime_data_clean/df_10H80FINAL.csv')