In [1]:
import pandas as pd

In [2]:
ls sports_data_clean

astros_10_17_plo_clean.csv*       nfl_08_17_clean.csv*
astros_10_17_reg_clean.csv*       nfl10clean.csv*
astros_1A10.csv*                  nfl10yearsfull.csv*
dynamo_10_17_plo.csv*             nfl17years_clean.csv*
dynamo_10_17__reg.csv*            nfl17years_PST_clean.csv*
dynamo_10H30.csv*                 rice_08_17_clean.csv*
hou_nfl_1017_post.csv*            Rice_10H80.csv*
hou_nfl_1017_reg.csv*             rockets_1A10.csv*
hou_rockets_08_17_clean.csv*      Tex_15E40.csv*
hou_rockets_10_17_plo_clean.csv*  uh_08_17_clean.csv*
hou_rockets_10_17_reg_clean.csv*  UH_10H50.csv*

In [3]:
hou_reg = 'sports_data_clean/uh_08_17_clean.csv'

In [4]:
df = pd.read_csv(hou_reg)

In [5]:
df = df[['Date','School','Pts','home_away','Opponent','Opp']]

In [6]:
df = df[df.home_away == 'home']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 0 to 128
Data columns (total 6 columns):
Date         61 non-null object
School       61 non-null object
Pts          61 non-null int64
home_away    61 non-null object
Opponent     61 non-null object
Opp          61 non-null int64
dtypes: int64(2), object(4)
memory usage: 3.3+ KB

In [8]:
df

           Date   School  Pts home_away              Opponent  Opp
0    2008-08-30  Houston   55      home              Southern    3
2    2008-09-13  Houston   28      home             Air Force   31
5    2008-10-09  Houston   45      home                   UAB   20
8    2008-11-08  Houston   42      home                Tulane   14
9    2008-11-15  Houston   70      home                 Tulsa   30
10   2008-11-22  Houston   42      home                  UTEP   37
13   2009-09-05  Houston   55      home    Northwestern State    7
15   2009-09-26  Houston   29      home            Texas Tech   28
19   2009-10-24  Houston   38      home                   SMU   15
20   2009-10-31  Houston   50      home  Southern Mississippi   43
23   2009-11-21  Houston   55      home               Memphis   14
24   2009-11-28  Houston   73      home                  Rice   14
27   2010-09-04  Houston   68      home           Texas State   28
28   2010-09-10  Houston   54      home                  UTEP   24
30   2010-09-25  Houston   42      home                Tulane   23
31   2010-10-09  Houston   24      home     Mississippi State   47
35   2010-11-05  Houston   33      home                   UCF   40
36   2010-11-13  Houston   25      home                 Tulsa   28
39   2011-09-03  Houston   38      home                  UCLA   34
42   2011-09-24  Houston   56      home         Georgia State    0
44   2011-10-08  Houston   56      home         East Carolina    3
45   2011-10-22  Houston   63      home              Marshall   28
46   2011-10-27  Houston   73      home                  Rice   34
49   2011-11-19  Houston   37      home                   SMU    7
51   2011-12-03  Houston   28      home  Southern Mississippi   49
53   2012-09-01  Houston   13      home           Texas State   30
54   2012-09-08  Houston   49      home        Louisiana Tech   56
57   2012-10-06  Houston   44      home           North Texas   21
58   2012-10-13  Houston   39      home                   UAB   17
60   2012-10-27  Houston   45      home                  UTEP   35
..          ...      ...  ...       ...                   ...  ...
64   2012-11-24  Houston   40      home                Tulane   17
65   2013-08-30  Houston   62      home              Southern   13
72   2013-10-31  Houston   35      home         South Florida   23
78   2014-08-29  Houston    7      home                  UTSA   27
79   2014-09-06  Houston   47      home       Grambling State    0
81   2014-09-20  Houston   47      home      Nevada-Las Vegas   14
82   2014-10-02  Houston   12      home                   UCF   17
84   2014-10-17  Houston   31      home                Temple   10
86   2014-11-08  Houston   24      home                Tulane   31
87   2014-11-22  Houston   38      home                 Tulsa   28
91   2015-09-05  Houston   52      home        Tennessee Tech   24
93   2015-09-26  Houston   59      home           Texas State   14
95   2015-10-08  Houston   49      home                   SMU   28
98   2015-10-31  Houston   34      home            Vanderbilt    0
99   2015-11-07  Houston   33      home            Cincinnati   30
100  2015-11-14  Houston   35      home               Memphis   34
102  2015-11-27  Houston   52      home                  Navy   31
103  2015-12-05  Houston   24      home                Temple   13
106  2016-09-10  Houston   42      home                 Lamar    0
109  2016-09-29  Houston   42      home           Connecticut   14
111  2016-10-15  Houston   38      home                 Tulsa   31
113  2016-10-29  Houston   31      home                   UCF   24
114  2016-11-12  Houston   30      home                Tulane   18
115  2016-11-17  Houston   36      home            Louisville   10
119  2017-09-16  Houston   38      home                  Rice    3
120  2017-09-23  Houston   24      home            Texas Tech   27
122  2017-10-07  Houston   35      home                   SMU   22
124  2017-10-19  Houston   38      home               Memphis   42
126  2017-11-04  Houston   52      home         East Carolina   27
128  2017-11-24  Houston   24      home                  Navy   14

[61 rows x 6 columns]

In [9]:
# date
df.Date = pd.to_datetime(df.Date)

df = df.set_index('Date').sort_index(ascending=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 61 entries, 2008-08-30 to 2017-11-24
Data columns (total 5 columns):
School       61 non-null object
Pts          61 non-null int64
home_away    61 non-null object
Opponent     61 non-null object
Opp          61 non-null int64
dtypes: int64(2), object(3)
memory usage: 2.9+ KB

In [ ]:
ls sports_data_clean/

In [11]:
uh_df = df.loc[df.index.year >= 2010]
uh_df

             School  Pts home_away              Opponent  Opp
Date
2010-09-04  Houston   68      home           Texas State   28
2010-09-10  Houston   54      home                  UTEP   24
2010-09-25  Houston   42      home                Tulane   23
2010-10-09  Houston   24      home     Mississippi State   47
2010-11-05  Houston   33      home                   UCF   40
2010-11-13  Houston   25      home                 Tulsa   28
2011-09-03  Houston   38      home                  UCLA   34
2011-09-24  Houston   56      home         Georgia State    0
2011-10-08  Houston   56      home         East Carolina    3
2011-10-22  Houston   63      home              Marshall   28
2011-10-27  Houston   73      home                  Rice   34
2011-11-19  Houston   37      home                   SMU    7
2011-12-03  Houston   28      home  Southern Mississippi   49
2012-09-01  Houston   13      home           Texas State   30
2012-09-08  Houston   49      home        Louisiana Tech   56
2012-10-06  Houston   44      home           North Texas   21
2012-10-13  Houston   39      home                   UAB   17
2012-10-27  Houston   45      home                  UTEP   35
2012-11-10  Houston    7      home                 Tulsa   41
2012-11-24  Houston   40      home                Tulane   17
2013-08-30  Houston   62      home              Southern   13
2013-10-31  Houston   35      home         South Florida   23
2014-08-29  Houston    7      home                  UTSA   27
2014-09-06  Houston   47      home       Grambling State    0
2014-09-20  Houston   47      home      Nevada-Las Vegas   14
2014-10-02  Houston   12      home                   UCF   17
2014-10-17  Houston   31      home                Temple   10
2014-11-08  Houston   24      home                Tulane   31
2014-11-22  Houston   38      home                 Tulsa   28
2015-09-05  Houston   52      home        Tennessee Tech   24
2015-09-26  Houston   59      home           Texas State   14
2015-10-08  Houston   49      home                   SMU   28
2015-10-31  Houston   34      home            Vanderbilt    0
2015-11-07  Houston   33      home            Cincinnati   30
2015-11-14  Houston   35      home               Memphis   34
2015-11-27  Houston   52      home                  Navy   31
2015-12-05  Houston   24      home                Temple   13
2016-09-10  Houston   42      home                 Lamar    0
2016-09-29  Houston   42      home           Connecticut   14
2016-10-15  Houston   38      home                 Tulsa   31
2016-10-29  Houston   31      home                   UCF   24
2016-11-12  Houston   30      home                Tulane   18
2016-11-17  Houston   36      home            Louisville   10
2017-09-16  Houston   38      home                  Rice    3
2017-09-23  Houston   24      home            Texas Tech   27
2017-10-07  Houston   35      home                   SMU   22
2017-10-19  Houston   38      home               Memphis   42
2017-11-04  Houston   52      home         East Carolina   27
2017-11-24  Houston   24      home                  Navy   14

In [12]:
uh_df['beat'] = '10H50'

/home/frank/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
uh_df.to_csv('sports_data_clean/UH_10H50.csv')

In [14]:
ls sports_data_clean/

astros_10_17_plo_clean.csv*       nfl_08_17_clean.csv*
astros_10_17_reg_clean.csv*       nfl10clean.csv*
astros_1A10.csv*                  nfl10yearsfull.csv*
dynamo_10_17_plo.csv*             nfl17years_clean.csv*
dynamo_10_17__reg.csv*            nfl17years_PST_clean.csv*
dynamo_10H30.csv*                 rice_08_17_clean.csv*
hou_nfl_1017_post.csv*            Rice_10H80.csv*
hou_nfl_1017_reg.csv*             rockets_1A10.csv*
hou_rockets_08_17_clean.csv*      Tex_15E40.csv*
hou_rockets_10_17_plo_clean.csv*  uh_08_17_clean.csv*
hou_rockets_10_17_reg_clean.csv*  UH_10H50.csv*