In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

# Location
- repo
[FoodballData repo](https://github.com/jokecamp/FootballData)

# Problem

- data does not contain year
- needs cleaning

### Solution

- Create function that does:
    1. create a column for given year
    2. create a full_year column that appends date and year column
    3. convert full_year column to datetime
    4. split result column with two colums given score of each team
    5. organize dataframe
    6. create winner column based on score of teams
    7. set and sort index to full_date column 

-  dataframes will be loaded one at a time given year

In [5]:
ls sports_data_raw/MLS/HOU/reg/

HOU_10.csv*  HOU_12.csv*  HOU_14.csv*  HOU_16.csv*
HOU_11.csv*  HOU_13.csv*  HOU_15.csv*  HOU_17.csv*

In [6]:

h10 = 'sports_data_raw//MLS/HOU/reg/HOU_10.csv'
h11 = 'sports_data_raw/MLS/HOU/reg/HOU_11.csv'
h12 = 'sports_data_raw/MLS/HOU/reg/HOU_12.csv'
h13 = 'sports_data_raw/MLS/HOU/reg/HOU_13.csv'
h14 = 'sports_data_raw/MLS/HOU/reg/HOU_14.csv'
h15 = 'sports_data_raw/MLS/HOU/reg/HOU_15.csv'
h16 = 'sports_data_raw/MLS/HOU/reg/HOU_16.csv'
h17 = 'sports_data_raw/MLS/HOU/reg/HOU_17.csv'

In [7]:

df10 = pd.read_csv(h10)
df11 = pd.read_csv(h11)
df12 = pd.read_csv(h12)
df13 = pd.read_csv(h13)
df14 = pd.read_csv(h14)
df15 = pd.read_csv(h15)
df16 = pd.read_csv(h16)
df17 = pd.read_csv(h17)

In [8]:
df11

          day          date       home_team result       away_team
0    Saturday      March 19             HOU    0-1    Philadelphia
1      Friday      March 25         Seattle    1-1             HOU
2    Saturday       April 2    NY Red Bulls    1-1             HOU
3      Sunday      April 10             HOU    3-1       Vancouver
4      Sunday      April 17             HOU    1-0     New England
5    Saturday      April 23         Chicago    1-1             HOU
6      Friday      April 29             HOU    4-1     D.C. United
7   Wednesday         May 4             HOU    1-2        Colorado
8    Saturday         May 7      Toronto FC    2-1             HOU
9    Saturday        May 14  Real Salt Lake    0-0             HOU
10   Saturday        May 21             HOU    2-2    NY Red Bulls
11  Wednesday        May 25       LA Galaxy    1-0             HOU
12   Saturday        May 28             HOU    2-2       FC Dallas
13   Saturday        June 4        San Jose    2-0             HOU
14   Saturday       June 11             HOU    2-1      Chivas USA
15   Saturday       June 18             HOU    0-2        Columbus
16   Saturday       June 25     D.C. United    2-2             HOU
17     Sunday        July 3        Colorado    0-0             HOU
18   Saturday        July 9             HOU    2-0      Toronto FC
19   Saturday       July 16             HOU    1-1     Sporting KC
20   Saturday       July 23      Chivas USA    3-0             HOU
21   Saturday       July 30         Seattle    3-1             HOU
22   Saturday      August 6    Philadelphia    1-1             HOU
23     Sunday     August 14             HOU    2-1        Portland
24  Wednesday     August 17     New England    1-1             HOU
25   Saturday     August 20             HOU    3-2  Real Salt Lake
26   Saturday     August 27       Vancouver    1-0             HOU
27   Saturday  September 10     Sporting KC    3-0             HOU
28  Wednesday  September 14        Columbus    2-2             HOU
29   Saturday  September 17             HOU    2-1        San Jose
30   Saturday  September 24       FC Dallas    0-1             HOU
31   Saturday     October 1             HOU    1-1         Chicago
32     Friday    October 14        Portland    0-2             HOU
33     Sunday    October 23             HOU    3-1       LA Galaxy

## Create function

In [9]:
def cleanup(df,year):
    '''function that clean up dataframe'''
    df['year'] = year  # create col with var year
    df['full_date'] = df['date'] + ' ' + df['year']  # append date and year cols
    df['full_date'] =  pd.to_datetime(df['full_date'])  # convert full_date to datetime
    df['home_score']= df['result'].str.split('-').apply(lambda x: x[0])  # split score vals
    df['away_score']= df['result'].str.split('-').apply(lambda x: x[1])  # split score vals
    df = df[['full_date','home_team','home_score','away_team','away_score']]  # org df
    # winner cols given value scores
    df['winner'] = np.where(df['home_score'] > df['away_score'], df['home_team'], df['away_team']) 
    df = df.set_index('full_date').sort_index(ascending=True)  # set full_date as index
    return df

In [10]:

dy_10 = cleanup(df10,'2010')
dy_11 = cleanup(df11,'2011')
dy_12 = cleanup(df12,'2012')
dy_13 = cleanup(df13,'2013')
dy_14 = cleanup(df14,'2014')
dy_15 = cleanup(df15,'2015')
dy_16 = cleanup(df16,'2016')
dy_17 = cleanup(df17,'2017')

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

In [11]:
dy_10

,home_team,home_score,away_team,away_score,winner
full_date,,,,,
2010-03-27,FC Dallas,1,HOU,1,HOU
2010-04-01,HOU,2,Real Salt Lake,1,HOU
2010-04-10,HOU,0,LA Galaxy,2,LA Galaxy
2010-04-17,HOU,3,Chivas USA,0,HOU
2010-04-24,Chicago,2,HOU,0,Chicago
2010-05-01,HOU,3,Sporting KC,0,HOU
2010-05-05,HOU,0,FC Dallas,1,FC Dallas
2010-05-08,Chivas USA,0,HOU,2,HOU
2010-05-13,Real Salt Lake,3,HOU,1,Real Salt Lake
2010-05-22,HOU,2,D.C. United,0,HOU
2010-05-29,HOU,2,Philadelphia,3,Philadelphia
2010-06-02,NY Red Bulls,2,HOU,1,NY Red Bulls
2010-06-05,LA Galaxy,4,HOU,1,LA Galaxy
2010-06-26,HOU,2,Colorado,2,Colorado
2010-07-01,Toronto FC,1,HOU,1,HOU
2010-07-10,HOU,0,Columbus,0,Columbus
2010-07-24,Columbus,3,HOU,0,Columbus
2010-07-31,HOU,2,NY Red Bulls,2,NY Red Bulls
2010-08-08,Seattle,2,HOU,0,Seattle
2010-08-14,New England,1,HOU,0,New England
2010-08-21,HOU,4,Chicago,3,HOU
2010-08-28,Colorado,3,HOU,0,Colorado
2010-09-05,HOU,1,San Jose,2,San Jose
2010-09-18,HOU,1,Toronto FC,2,Toronto FC
2010-09-22,Sporting KC,4,HOU,3,Sporting KC
2010-09-25,D.C. United,1,HOU,3,HOU
2010-10-02,Philadelphia,1,HOU,1,HOU
2010-10-10,HOU,1,New England,2,New England
2010-10-16,San Jose,0,HOU,1,HOU
2010-10-23,Seattle,2,HOU,1,Seattle

# Combine add dataframes

- 2010-2017

In [12]:
frames = [dy_10,dy_11,dy_12,dy_13,
          dy_14,dy_15,dy_16,dy_17]

dynamo10_17 = pd.concat(frames)

In [13]:
dynamo10_17.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 268 entries, 2010-03-27 to 2017-10-22
Data columns (total 5 columns):
home_team     268 non-null object
home_score    268 non-null object
away_team     268 non-null object
away_score    268 non-null object
winner        268 non-null object
dtypes: object(5)
memory usage: 12.6+ KB

In [14]:
dynamo10_17.head()

            home_team home_score       away_team away_score     winner
full_date
2010-03-27  FC Dallas          1             HOU          1        HOU
2010-04-01        HOU          2  Real Salt Lake          1        HOU
2010-04-10        HOU          0       LA Galaxy          2  LA Galaxy
2010-04-17        HOU          3      Chivas USA          0        HOU
2010-04-24    Chicago          2             HOU          0    Chicago

In [15]:
dynamo10_17['season'] = 'reg'

In [17]:
dynamo10_17.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 268 entries, 2010-03-27 to 2017-10-22
Data columns (total 6 columns):
home_team     268 non-null object
home_score    268 non-null object
away_team     268 non-null object
away_score    268 non-null object
winner        268 non-null object
season        268 non-null object
dtypes: object(6)
memory usage: 14.7+ KB

## Save clean data to  to csv

In [18]:
dynamo10_17.to_csv('sports_data_clean/dynamo_10_17__reg_clean.csv')

In [19]:
ls sports_data_clean/

astros_08_17_clean.csv*               nfl_08_17_clean.csv*
astros_10_17_clean.csv*               nfl10clean.csv*
dynamo_08_17_clean.csv*               nfl10yearsfull.csv*
dynamo_10_17_clean.csv*               nfl17years_clean.csv*
dynamo_10_17_plo.csv*                 nfl17years_PST_clean.csv*
dynamo_10_17__reg_clean.csv*          rice_08_17_clean.csv*
hou_home_10_17_clean.csv*             tsu_08_17_clean.csv*
hou_rockets_08_17_clean.csv*          uh_08_17_clean.csv*
hou_rockets_10_17_reg_plo_clean.csv*

In [ ]:
## Finish