In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

## Source

####  baseball-reference.com

https://www.baseball-reference.com/teams/HOU/2018-schedule-scores.shtml

- saved regular seasons from 2008 - 2017 to csv

In [6]:
ls sports_data_raw/MLB/plo

mlb_h_15_plo.csv*  mlb_h_17_plo.csv*

## get all data

In [7]:
path = 'sports_data_raw/MLB/plo'
all_files = glob.glob(os.path.join(path, "*.csv")) 

df_from_each_file = (pd.read_csv(f) for f in all_files)
df   = pd.concat(df_from_each_file, ignore_index=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 10 columns):
Unnamed: 7    0 non-null float64
Unnamed: 8    0 non-null float64
Unnamed: 9    0 non-null float64
date          24 non-null object
location      24 non-null object
score_1       24 non-null int64
score_2       24 non-null int64
team_1        24 non-null object
team_2        24 non-null object
time          24 non-null object
dtypes: float64(3), int64(2), object(5)
memory usage: 2.0+ KB

In [9]:
df

,Unnamed: 7,Unnamed: 8,Unnamed: 9,date,location,score_1,score_2,team_1,team_2,time
0,NaN,NaN,NaN,"Tuesday, October 6, 2015",Yankee Stadium III,3,0,Houston,New York,8:10
1,NaN,NaN,NaN,"Thursday, October 8, 2015",Kauffman Stadium,5,2,Houston,Kansas City,6:37
2,NaN,NaN,NaN,"Friday, October 9, 2015",Kauffman Stadium,4,5,Houston,Kansas City,2:47
3,NaN,NaN,NaN,"Sunday, October 11, 2015",Minute Maid Park,2,4,Kansas City,Houston,3:10
4,NaN,NaN,NaN,"Monday, October 12, 2015",Minute Maid Park,9,6,Kansas City,Houston,12:07
5,NaN,NaN,NaN,"Wednesday, October 14, 2015",Kauffman Stadium,2,7,Houston,Kansas City,7:08
6,NaN,NaN,NaN,"Thursday, October 5, 2017",Minute Maid Park,2,8,Boston,Houston,4pm
7,NaN,NaN,NaN,"Friday, October 6, 2017",Minute Maid Park,2,8,Boston,Houston,2pm
8,NaN,NaN,NaN,"Sunday, October 8, 2017",Fenway Park,3,10,Houston,Boston,2:30
9,NaN,NaN,NaN,"Monday, October 9, 2017",Fenway Park,5,4,Houston,Boston,1:00
10,NaN,NaN,NaN,"Friday, October 13, 2017",Minute Maid Park,1,2,New York,Houston,8:00
11,NaN,NaN,NaN,"Saturday, October 14, 2017",Minute Maid Park,1,2,New York,Houston,4:00
12,NaN,NaN,NaN,"Monday, October 16, 2017",Yankee Stadium III,1,8,Houston,New York,8:00
13,NaN,NaN,NaN,"Tuesday, October 17, 2017",Yankee Stadium III,4,6,Houston,New York,5:00
14,NaN,NaN,NaN,"Wednesday, October 18, 2017",Yankee Stadium III,0,5,Houston,New York,5:00
15,NaN,NaN,NaN,"Friday, October 20, 2017",Minute Maid Park,1,7,New York,Houston,8:00
16,NaN,NaN,NaN,"Saturday, October 21, 2017",Minute Maid Park,0,4,New York,Houston,8:00
17,NaN,NaN,NaN,"Tuesday, October 24, 2017",Dodger Stadium,1,3,Houston,Los Angeles,8:00
18,NaN,NaN,NaN,"Wednesday, October 25, 2017",Dodger Stadium,7,6,Houston,Los Angeles,8:00
19,NaN,NaN,NaN,"Friday, October 27, 2017",Minute Maid Park,3,5,Los Angeles,Houston,8:00
20,NaN,NaN,NaN,"Saturday, October 28, 2017",Minute Maid Park,6,2,Los Angeles,Houston,8:00
21,NaN,NaN,NaN,"Sunday, October 29, 2017",Minute Maid Park,12,13,Los Angeles,Houston,8:00
22,NaN,NaN,NaN,"Tuesday, October 31, 2017",Dodger Stadium,1,3,Houston,Los Angeles,8:00
23,NaN,NaN,NaN,"Wednesday, November 1, 2017",Dodger Stadium,5,1,Houston,Los Angeles,8:00

## Create slice with only needed columns

In [10]:
mlb = df[['date','time','location','team_1','score_1','team_2','score_2']]

In [11]:
mlb.head()

,date,time,location,team_1,score_1,team_2,score_2
0,"Tuesday, October 6, 2015",8:10,Yankee Stadium III,Houston,3,New York,0
1,"Thursday, October 8, 2015",6:37,Kauffman Stadium,Houston,5,Kansas City,2
2,"Friday, October 9, 2015",2:47,Kauffman Stadium,Houston,4,Kansas City,5
3,"Sunday, October 11, 2015",3:10,Minute Maid Park,Kansas City,2,Houston,4
4,"Monday, October 12, 2015",12:07,Minute Maid Park,Kansas City,9,Houston,6

In [12]:
mlb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
date        24 non-null object
time        24 non-null object
location    24 non-null object
team_1      24 non-null object
score_1     24 non-null int64
team_2      24 non-null object
score_2     24 non-null int64
dtypes: int64(2), object(5)
memory usage: 1.4+ KB

## convert year column to string

In [13]:
mlb.date = pd.to_datetime(mlb.date)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/pandas/core/generic.py:3643: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [16]:
mlb[mlb.location == 'Minute Maid Park']

         date   time          location       team_1  score_1   team_2  score_2
3  2015-10-11   3:10  Minute Maid Park  Kansas City        2  Houston        4
4  2015-10-12  12:07  Minute Maid Park  Kansas City        9  Houston        6
7  2017-10-06    2pm  Minute Maid Park       Boston        2  Houston        8
10 2017-10-13  8:00   Minute Maid Park     New York        1  Houston        2
11 2017-10-14   4:00  Minute Maid Park     New York        1  Houston        2
15 2017-10-20   8:00  Minute Maid Park     New York        1  Houston        7
16 2017-10-21   8:00  Minute Maid Park     New York        0  Houston        4
19 2017-10-27   8:00  Minute Maid Park  Los Angeles        3  Houston        5
20 2017-10-28   8:00  Minute Maid Park  Los Angeles        6  Houston        2
21 2017-10-29   8:00  Minute Maid Park  Los Angeles       12  Houston       13

## Create new column with full date

In [17]:
mlb[mlb.team_1 == 'Houston']

,date,time,location,team_1,score_1,team_2,score_2
0,2015-10-06,8:10,Yankee Stadium III,Houston,3,New York,0
1,2015-10-08,6:37,Kauffman Stadium,Houston,5,Kansas City,2
2,2015-10-09,2:47,Kauffman Stadium,Houston,4,Kansas City,5
5,2015-10-14,7:08,Kauffman Stadium,Houston,2,Kansas City,7
8,2017-10-08,2:30,Fenway Park,Houston,3,Boston,10
12,2017-10-16,8:00,Yankee Stadium III,Houston,1,New York,8
13,2017-10-17,5:00,Yankee Stadium III,Houston,4,New York,6
14,2017-10-18,5:00,Yankee Stadium III,Houston,0,New York,5
17,2017-10-24,8:00,Dodger Stadium,Houston,1,Los Angeles,3
18,2017-10-25,8:00,Dodger Stadium,Houston,7,Los Angeles,6
22,2017-10-31,8:00,Dodger Stadium,Houston,1,Los Angeles,3
23,2017-11-01,8:00,Dodger Stadium,Houston,5,Los Angeles,1

In [18]:
mlb[mlb.team_2 == 'Houston']

,date,time,location,team_1,score_1,team_2,score_2
3,2015-10-11,3:10,Minute Maid Park,Kansas City,2,Houston,4
4,2015-10-12,12:07,Minute Maid Park,Kansas City,9,Houston,6
6,2017-10-05,4pm,Minute Maid Park,Boston,2,Houston,8
7,2017-10-06,2pm,Minute Maid Park,Boston,2,Houston,8
10,2017-10-13,8:00,Minute Maid Park,New York,1,Houston,2
11,2017-10-14,4:00,Minute Maid Park,New York,1,Houston,2
15,2017-10-20,8:00,Minute Maid Park,New York,1,Houston,7
16,2017-10-21,8:00,Minute Maid Park,New York,0,Houston,4
19,2017-10-27,8:00,Minute Maid Park,Los Angeles,3,Houston,5
20,2017-10-28,8:00,Minute Maid Park,Los Angeles,6,Houston,2
21,2017-10-29,8:00,Minute Maid Park,Los Angeles,12,Houston,13

## Remve parenthesis from dates from double  games

In [ ]:
mlb[mlb.location == 'Minute Maid Park']

In [19]:
mlb['home_away'] = np.where(mlb.location == 'Minute Maid Park' , 'HOME', 'AWAY')

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [23]:
mlb = mlb.set_index('date').sort_index(ascending=True)

In [27]:
mlb['season'] = 'plo'

In [28]:
mlb

,time,location,team_1,score_1,team_2,score_2,home_away,season
date,,,,,,,,
2015-10-06,8:10,Yankee Stadium III,Houston,3,New York,0,AWAY,plo
2015-10-08,6:37,Kauffman Stadium,Houston,5,Kansas City,2,AWAY,plo
2015-10-09,2:47,Kauffman Stadium,Houston,4,Kansas City,5,AWAY,plo
2015-10-11,3:10,Minute Maid Park,Kansas City,2,Houston,4,HOME,plo
2015-10-12,12:07,Minute Maid Park,Kansas City,9,Houston,6,HOME,plo
2015-10-14,7:08,Kauffman Stadium,Houston,2,Kansas City,7,AWAY,plo
2017-10-05,4pm,Minute Maid Park,Boston,2,Houston,8,AWAY,plo
2017-10-06,2pm,Minute Maid Park,Boston,2,Houston,8,HOME,plo
2017-10-08,2:30,Fenway Park,Houston,3,Boston,10,AWAY,plo
2017-10-09,1:00,Fenway Park,Houston,5,Boston,4,AWAY,plo
2017-10-13,8:00,Minute Maid Park,New York,1,Houston,2,HOME,plo
2017-10-14,4:00,Minute Maid Park,New York,1,Houston,2,HOME,plo
2017-10-16,8:00,Yankee Stadium III,Houston,1,New York,8,AWAY,plo
2017-10-17,5:00,Yankee Stadium III,Houston,4,New York,6,AWAY,plo
2017-10-18,5:00,Yankee Stadium III,Houston,0,New York,5,AWAY,plo
2017-10-20,8:00,Minute Maid Park,New York,1,Houston,7,HOME,plo
2017-10-21,8:00,Minute Maid Park,New York,0,Houston,4,HOME,plo
2017-10-24,8:00,Dodger Stadium,Houston,1,Los Angeles,3,AWAY,plo
2017-10-25,8:00,Dodger Stadium,Houston,7,Los Angeles,6,AWAY,plo
2017-10-27,8:00,Minute Maid Park,Los Angeles,3,Houston,5,HOME,plo
2017-10-28,8:00,Minute Maid Park,Los Angeles,6,Houston,2,HOME,plo
2017-10-29,8:00,Minute Maid Park,Los Angeles,12,Houston,13,HOME,plo
2017-10-31,8:00,Dodger Stadium,Houston,1,Los Angeles,3,AWAY,plo
2017-11-01,8:00,Dodger Stadium,Houston,5,Los Angeles,1,AWAY,plo

In [29]:
mlb.to_csv('sports_data_clean/astros_10_17_plo_clean.csv')