In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import googlemaps
import gmaps
import requests
API_KEY = 'your_apikey'

import gmaps_func as gf

In [2]:
path = 'crime_data_clean/crime_10H30_10_17.csv'
df = pd.read_csv(path,index_col='Date_Hour', parse_dates=True)

In [3]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4398 entries, 2010-01-01 00:00:00 to 2017-12-31 16:00:00
Data columns (total 11 columns):
Beat           4398 non-null object
BlockRange     4398 non-null object
StreetName     4398 non-null object
OffenseType    4398 non-null object
Premise        4398 non-null object
NumOffenses    4398 non-null int64
Hour           4398 non-null int64
day            4398 non-null int64
weekday        4398 non-null object
month          4398 non-null object
year           4398 non-null int64
dtypes: int64(4), object(7)
memory usage: 412.3+ KB

## Return a good blockrange value

In [5]:
gf.block_split(df)

ValueError: invalid literal for int() with base 10: 'UNK'

## Drop 'UNK' values

In [6]:
unk = df.BlockRange == 'UNK'

In [7]:
df = df[~unk]

In [8]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010

In [9]:
df['block'] = gf.block_split(df)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block
Date_Hour,,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010,1750
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,550
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010,1750
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,2050
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,1950

## Create full addres col

In [11]:
df['address']  = df[['block', 'StreetName']].apply(lambda x: ' '.join(x), axis=1)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [12]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address
Date_Hour,,,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010,1750,1750 SAMPSON
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,550,550 BASTROP
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010,1750,1750 HUTCHINS
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,2050,2050 LEELAND
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,1950,1950 COMMERCE

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4382 entries, 2010-01-01 00:00:00 to 2017-12-31 16:00:00
Data columns (total 13 columns):
Beat           4382 non-null object
BlockRange     4382 non-null object
StreetName     4382 non-null object
OffenseType    4382 non-null object
Premise        4382 non-null object
NumOffenses    4382 non-null int64
Hour           4382 non-null int64
day            4382 non-null int64
weekday        4382 non-null object
month          4382 non-null object
year           4382 non-null int64
block          4382 non-null object
address        4382 non-null object
dtypes: int64(4), object(9)
memory usage: 639.3+ KB

In [18]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address
Date_Hour,,,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010,1750,1750 SAMPSON
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,550,550 BASTROP
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010,1750,1750 HUTCHINS
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,2050,2050 LEELAND
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,1950,1950 COMMERCE

# get full lat long and address from google

In [19]:
df['tup_add'] = df['address'].apply(gf.gm_geocode,args=(API_KEY,))

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
df_100 = df.iloc[:100].copy()
df_20 = df.iloc[:20].copy()
df_30 = df.iloc[:30].copy()

In [14]:
df_100.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 100 entries, 2010-01-01 00:00:00 to 2010-03-05 13:00:00
Data columns (total 13 columns):
Beat           100 non-null object
BlockRange     100 non-null object
StreetName     100 non-null object
OffenseType    100 non-null object
Premise        100 non-null object
NumOffenses    100 non-null int64
Hour           100 non-null int64
day            100 non-null int64
weekday        100 non-null object
month          100 non-null object
year           100 non-null int64
block          100 non-null object
address        100 non-null object
dtypes: int64(4), object(9)
memory usage: 10.9+ KB

In [ ]:
df_100

In [15]:
df_100['tup_add'] = df_100['address'].apply(gf.gm_geocode,args=(API_KEY,))

In [16]:
df_100

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010,1750,1750 SAMPSON,"((29.7390659, -95.34897509999999), 1750 Sampso..."
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,550,550 BASTROP,"((29.7536483, -95.3510778), 550 Bastrop St, Ho..."
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010,1750,1750 HUTCHINS,"((29.7452984, -95.3593236), 1750 Hutchins St, ..."
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,2050,2050 LEELAND,"((29.7466075, -95.3593348), 2050 Leeland St, H..."
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,1950,1950 COMMERCE,"((29.7588305, -95.35140249999999), 1950 Commer..."
2010-01-03 18:00:00,10H30,2000-2099,MCKINNEY,Theft,construction site,1,18,3,Sunday,Jan,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-01-04 08:00:00,10H30,1700-1799,ADEN MIST,Burglary,apartment,1,8,4,Monday,Jan,2010,1750,1750 ADEN MIST,"((29.741344, -95.35397789999999), 1750 Aden Mi..."
2010-01-05 13:00:00,10H30,100-199,CHARTRES,Theft,road/street/sidewalk,1,13,5,Tuesday,Jan,2010,150,150 CHARTRES,"((29.7611979, -95.34920699999999), 150 Chartre..."
2010-01-05 18:00:00,10H30,2300-2399,LAMAR,Burglary,commercial building,1,18,5,Tuesday,Jan,2010,2350,2350 LAMAR,"((29.7488639, -95.3537793), 2350 Lamar St, Hou..."
2010-01-06 00:00:00,10H30,900-999,MCKINNEY PARK,Theft,driveway,1,0,6,Wednesday,Jan,2010,950,950 MCKINNEY PARK,"((29.7571808, -95.36528919999999), 950 McKinne..."
2010-01-07 21:00:00,10H30,2500-2599,RUSK,Theft,road/street/sidewalk,1,21,7,Thursday,Jan,2010,2550,2550 RUSK,"((29.7502127, -95.35054699999999), 2550 Rusk S..."
2010-01-08 08:00:00,10H30,3100-3199,POLK,Theft,other parking lot,1,8,8,Friday,Jan,2010,3150,3150 POLK,"((29.7430184, -95.3485319), 3150 Polk St, Hous..."
2010-01-08 16:00:00,10H30,2100-2199,RUSK,Theft,road/street/sidewalk,1,16,8,Friday,Jan,2010,2150,2150 RUSK,"((29.752323, -95.35382469999999), 2150 Rusk St..."
2010-01-08 23:00:00,10H30,2100-2199,LAMAR,Theft,bar/night club parking lot,1,23,8,Friday,Jan,2010,2150,2150 LAMAR,"((29.7499994, -95.3558456), 2150 Lamar St, Hou..."
2010-01-08 23:00:00,10H30,2000-2099,MCKINNEY,Theft,bar/night club parking lot,1,23,8,Friday,Jan,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-01-09 00:00:00,10H30,2400-2499,POLK,Burglary,misc. business (non-specific),1,0,9,Saturday,Jan,2010,2450,2450 POLK,"((29.7463608, -95.3546763), 2450 Polk St, Hous..."
2010-01-09 01:00:00,10H30,2000-2099,LEELAND,Theft,commercial parking lot/garage,1,1,9,Saturday,Jan,2010,2050,2050 LEELAND,"((29.7466075, -95.3593348), 2050 Leeland St, H..."
2010-01-11 18:00:00,10H30,1800-1899,MILBY,Auto Theft,other/unknown,1,18,11,Monday,Jan,2010,1850,1850 MILBY,"((29.736935, -95.34435789999999), 1850 Milby S..."
2010-01-11 20:00:00,10H30,1400-1499,MILBY,Theft,residence/house,1,20,11,Monday,Jan,2010,1450,1450 MILBY,"((29.7393956, -95.3433508), 1450 Milby St, Hou..."
2010-01-11 23:00:00,10H30,2000-2099,MCKINNEY,Theft,restaurant/cafeteria parking lot,1,23,11,Monday,Jan,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-01-12 12:00:00,10H30,2700-2799,CLAY,Burglary,residence/house,1,12,12,Tuesday,Jan,2010,2750,2750 CLAY,"((29.7444096, -95.3523431), 2750 Clay St, Hous..."
2010-01-13 14:00:00,10H30,2300-2399,LAMAR,Theft,vacant building (commercial),1,14,13,Wednesday,Jan,2010,2350,2350 LAMAR,"((29.7488639, -95.3537793), 2350 Lamar St, Hou..."
2010-01-13 22:00:00,10H30,1900-1999,BELL,Robbery,road/street/sidewalk,1,22,13,Wednesday,Jan,2010,1950,1950 BELL,"((29.75480599999999, -95.404411), 1950 W Bell ..."
2010-01-15 14:00:00,10H30,1700-1799,ENNIS,Theft,other/unknown,1,14,15,Friday,Jan,2010,1750,1750 ENNIS,"((29.7410944, -95.3522058), 1750 Ennis St, Hou..."
2010-01-16 20:00:00,10H30,3200-3299,DALLAS,Theft,apartment parking lot,1,20,16,Saturday,Jan,2010,3250,3250 DALLAS,"((29.7574315, -95.40048360000002), 3250 W Dall..."
2010-01-16 21:00:00,10H30,2300-2399,JEFFERSON,Burglary,vehicle/auto sales/lease/auto parts store,1,21,16,Saturday,Jan,2010,2350,2350 JEFFERSON,"((29.7436105, -95.35807129999999), 2350 Jeffer..."
2010-01-17 12:00:00,10H30,2200-2299,DALLAS,Theft,apartment,1,12,17,Sunday,Jan,2010,2250,2250 DALLAS,"((29.7488265, -95.35544519999999), 2250 Dallas..."
2010-01-20 01:00:00,10H30,2100-2199,TEXAS,Auto Theft,road/street/sidewalk,1,1,20,Wednesday,Jan,2010,2150,2150 TEXAS,"((29.7540067, -95.3529071), 2150 Texas St, Hou..."
2010-01-22 19:00:00,10H30,3400-3499,DALLAS,Auto Theft,apartment parking lot,1,19,22,Friday,Jan,2010,3450,3450 DALLAS,"((29.7584223, -95.40566559999999), 3450 W Dall..."
2010-01-22 23:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,23,22,Friday,Jan,2010,1950,1950 COMMERCE,"((29.7588305, -95.35140249999999), 1950 Commer..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2010-02-14 01:00:00,10H30,2000-2099,LEELAND,Theft,bar/night club,1,1,14,Sunday,Feb,2010,2050,2050 LEELAND,"((29.7466075, -95.3593348), 2050 Leeland St, H..."
2010-02-14 01:00:00,10H30,2200-2299,DALLAS,Theft,apartment parking lot,1,1,14,Sunday,Feb,2010,2250,2250 DALLAS,"((29.7488265, -95.35544519999999), 2250 Dallas..."
2010-02-14 02:00:00,10H30,2000-2099,MCKINNEY,Theft,bar/night club,1,2,14,Sunday,Feb,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-02-14 21:00:00,10H30,2100-2199,CAPITOL,Theft,road/street/sidewalk,1,21,14,Sunday,Feb,2010,2150,2150 CAPITOL,"((29.7528252, -95.35350799999999), 2150 Capito..."
2010-02-16 12:00:00,10H30,1500-1599,PAIGE,Burglary,condominium,1,12,16,Tuesday,Feb,2010,1550,1550 PAIGE,"((29.7428734, -95.3522813), 1550 Paige St, Hou..."
2010-02-17 19:00:00,10H30,2900-2999,PEASE,Theft,road/street/sidewalk,1,19,17,Wednesday,Feb,2010,2950,2950 PEASE,"((29.741796, -95.35225319999999), 2950 Pease S..."
2010-02-18 16:00:00,10H30,800-899,ST EMANUEL,Theft,bar/night club parking lot,1,16,18,Thursday,Feb,2010,850,850 ST EMANUEL,"((29.7524653, -95.35478769999999), 850 St Eman..."
2010-02-18 22:00:00,10H30,2500-2599,MCKINNEY,Theft,bar/night club,1,22,18,Thursday,Feb,2010,2550,2550 MCKINNEY,"((29.7485764, -95.35152880000001), 2550 McKinn..."
2010-02-19 12:00:00,10H30,800-899,DELANO,Theft,other parking lot,1,12,19,Friday,Feb,2010,850,850 DELANO,"((29.7486069, -95.3487529), 850 Delano St, Hou..."
2010-02-19 22:00:00,10H30,1500-1599,CHARTRES,Aggravated Assault,bar/night club,1,22,19,Friday,Feb,2010,1550,1550 CHARTRES,"((29.7475521, -95.3596541), 1550 Chartres St, ..."
2010-02-19 23:00:00,10H30,3500-3599,GULF,Theft,service/gas station,1,23,19,Friday,Feb,2010,3550,3550 GULF,"((29.6961263, -95.28912539999999), 3550 Gulf F..."
2010-02-20 00:00:00,10H30,2000-2099,COMMERCE,Theft,bar/night club parking lot,1,0,20,Saturday,Feb,2010,2050,2050 COMMERCE,"((29.7578815, -95.35042209999999), 2050 Commer..."
2010-02-20 15:00:00,10H30,1000-1099,ST EMANUEL,Theft,grocery/supermarket parking lot,1,15,20,Saturday,Feb,2010,1050,1050 ST EMANUEL,"((29.7506861, -95.3561113), 1050 St Emanuel St..."
2010-02-21 19:00:00,10H30,2100-2199,TEXAS,Theft,road/street/sidewalk,1,19,21,Sunday,Feb,2010,2150,2150 TEXAS,"((29.7540067, -95.3529071), 2150 Texas St, Hou..."
2010-02-21 22:00:00,10H30,2200-2299,RUSK,Theft,road/street/sidewalk,1,22,21,Sunday,Feb,2010,2250,2250 RUSK,"((29.7522163, -95.3535181), 2250 Rusk St, Hous..."
2010-02-22 20:00:00,10H30,3100-3199,DALLAS,Burglary,residence/house,1,20,22,Monday,Feb,2010,3150,3150 DALLAS,"((29.7441012, -95.3477688), 3150 Dallas St, Ho..."
2010-02-23 00:00:00,10H30,1100-1199,ENNIS,Theft,road/street/sidewalk,1,0,23,Tuesday,Feb,2010,1150,1150 ENNIS,"((29.7456742, -95.34896429999999), 1150 Ennis ..."
2010-02-23 17:00:00,10H30,3500-3599,POLK,Theft,other parking lot,1,17,23,Tuesday,Feb,2010,3550,3550 POLK,"((29.7413924, -95.34446779999999), 3550 Polk S..."
2010-02-23 17:00:00,10H30,3500-3599,POLK,Theft,other parking lot,1,17,23,Tuesday,Feb,2010,3550,3550 POLK,"((29.7413924, -95.34446779999999), 3550 Polk S..."
2010-02-23 18:00:00,10H30,1300-1399,LIVE OAK,Theft,road/street/sidewalk,1,18,23,Tuesday,Feb,2010,1350,1350 LIVE OAK,"((29.7462034, -95.3537372), 1350 Live Oak St, ..."
2010-02-26 11:00:00,10H30,2800-2899,GULF,Theft,specialty store (non-specific),1,11,26,Friday,Feb,2010,2850,2850 GULF,"((29.6957046, -95.29001749999999), 2850 Gulf F..."
2010-02-28 09:00:00,10H30,1600-1699,EDMUNDSON,Theft,warehouse,1,9,28,Sunday,Feb,2010,1650,1650 EDMUNDSON,"((29.7377948, -95.34589059999999), 1650 Edmund..."
2010-03-01 10:00:00,10H30,1300-1399,DOWLING,Theft,road/street/sidewalk,1,10,1,Monday,Mar,2010,1350,1350 DOWLING,"((29.7469619, -95.3555075), 1350 Emancipation ..."
2010-03-01 18:00:00,10H30,2000-2099,CAPITOL,Theft,road/street/sidewalk,1,18,1,Monday,Mar,2010,2050,2050 CAPITOL,"((29.7537558, -95.3541151), 2050 Capitol St, H..."
2010-03-03 00:00:00,10H30,2000-2099,MCKINNEY,Theft,bar/night club parking lot,1,0,3,Wednesday,Mar,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-03-03 00:00:00,10H30,1200-1299,ST EMANUEL,Theft,road/street/sidewalk,1,0,3,Wednesday,Mar,2010,1250,1250 ST EMANUEL,"((29.7492849, -95.3574047), 1250 St Emanuel St..."
2010-03-03 00:00:00,10H30,2200-2299,MCKINNEY,Theft,road/street/sidewalk,1,0,3,Wednesday,Mar,2010,2250,2250 MCKINNEY,"((29.750029, -95.35416699999999), 2250 McKinne..."
2010-03-03 16:00:00,10H30,2000-2099,MCKINNEY,Theft,bar/night club parking lot,1,16,3,Wednesday,Mar,2010,2050,2050 MCKINNEY,"((29.7511977, -95.3561884), 2050 McKinney St, ..."
2010-03-04 15:00:00,10H30,700-799,CHARTRES,Robbery,commercial parking lot/garage,1,15,4,Thursday,Mar,2010,750,750 CHARTRES,"((29.7536373, -95.354855), 750 Chartres St, Ho..."
2010-03-05 13:00:00,10H30,2300-2399,RUSK,Theft,road/street/sidewalk,1,13,5,Friday,Mar,2010,2350,2350 RUSK,"((29.7511974, -95.3517481), 2350 Rusk St, Hous..."

In [21]:
df.to_csv('crime_data_clean/crime_10H30_10_17ADD.csv')

In [22]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01 00:00:00,10H30,1700-1799,SAMPSON,Theft,residence/house,1,0,1,Friday,Jan,2010,1750,1750 SAMPSON,"((29.7390659, -95.34897509999999), 1750 Sampso..."
2010-01-01 19:00:00,10H30,500-599,BASTROP,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,550,550 BASTROP,"((29.7536483, -95.3510778), 550 Bastrop St, Ho..."
2010-01-01 20:00:00,10H30,1700-1799,HUTCHINS,Theft,residence/house,1,20,1,Friday,Jan,2010,1750,1750 HUTCHINS,"((29.7452984, -95.3593236), 1750 Hutchins St, ..."
2010-01-02 01:00:00,10H30,2000-2099,LEELAND,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,2050,2050 LEELAND,"((29.7466075, -95.3593348), 2050 Leeland St, H..."
2010-01-03 04:00:00,10H30,1900-1999,COMMERCE,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,1950,1950 COMMERCE,"((29.7588305, -95.35140249999999), 1950 Commer..."

In [23]:
new_add = df.tup_add.apply(pd.Series,index=['lat_lon','full_address'])

In [25]:
new_add.head()

,lat_lon,full_address
Date_Hour,,
2010-01-01 00:00:00,"(29.7390659, -95.34897509999999)","1750 Sampson St, Houston, TX 77003, USA"
2010-01-01 19:00:00,"(29.7536483, -95.3510778)","550 Bastrop St, Houston, TX 77003, USA"
2010-01-01 20:00:00,"(29.7452984, -95.3593236)","1750 Hutchins St, Houston, TX 77003, USA"
2010-01-02 01:00:00,"(29.7466075, -95.3593348)","2050 Leeland St, Houston, TX 77003, USA"
2010-01-03 04:00:00,"(29.7588305, -95.35140249999999)","1950 Commerce St, Houston, TX 77002, USA"

In [26]:
df = df.join(new_add)

In [28]:
df.drop(['block','BlockRange','StreetName','address','tup_add','address','tup_add',],axis=1,inplace=True)

In [30]:
df.drop('block', axis=1,inplace=True)

In [31]:
df.head()

,Beat,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,lat_lon,full_address
Date_Hour,,,,,,,,,,,
2010-01-01 00:00:00,10H30,Theft,residence/house,1,0,1,Friday,Jan,2010,"(29.7390659, -95.34897509999999)","1750 Sampson St, Houston, TX 77003, USA"
2010-01-01 19:00:00,10H30,Theft,apartment parking lot,1,19,1,Friday,Jan,2010,"(29.7536483, -95.3510778)","550 Bastrop St, Houston, TX 77003, USA"
2010-01-01 20:00:00,10H30,Theft,residence/house,1,20,1,Friday,Jan,2010,"(29.7452984, -95.3593236)","1750 Hutchins St, Houston, TX 77003, USA"
2010-01-02 01:00:00,10H30,Theft,road/street/sidewalk,1,1,2,Saturday,Jan,2010,"(29.7466075, -95.3593348)","2050 Leeland St, Houston, TX 77003, USA"
2010-01-03 04:00:00,10H30,Theft,commercial parking lot/garage,1,4,3,Sunday,Jan,2010,"(29.7588305, -95.35140249999999)","1950 Commerce St, Houston, TX 77002, USA"

In [32]:
df.to_csv('crime_data_clean/crime_10H30_10_17FINAL.csv')