In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import googlemaps
import gmaps
import requests
API_KEY = 'AIzaSyDx5QmI3U_EDK3N8uVW32D65fdLdv82C58'

import gmaps_func as gf
import datetime as dt

In [2]:
path = 'crime_data_clean/crime_1A10_10_17.csv'
df = pd.read_csv(path,index_col='Date_Hour', parse_dates=True)

In [3]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15204 entries, 2010-01-01 00:00:00 to 2017-12-31 22:00:00
Data columns (total 11 columns):
Beat           15204 non-null object
BlockRange     15204 non-null object
StreetName     15204 non-null object
OffenseType    15204 non-null object
Premise        15204 non-null object
NumOffenses    15204 non-null int64
Hour           15204 non-null int64
day            15204 non-null int64
weekday        15204 non-null object
month          15204 non-null object
year           15204 non-null int64
dtypes: int64(4), object(7)
memory usage: 1.4+ MB

## Return a good blockrange value

In [5]:
gf.block_split(df)

ValueError: invalid literal for int() with base 10: 'UNK'

## Drop 'UNK' values

In [6]:
unk = df.BlockRange == 'UNK'

In [7]:
df = df[~unk]

In [8]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010

In [9]:
df['block'] = gf.block_split(df)

ValueError: invalid literal for int() with base 10: '1.1103e+006'

In [10]:
df.BlockRange.value_counts()

1200-1299      1555
900-999        1132
1000-1099      1061
1500-1599       973
1100-1199       924
500-599         921
800-899         868
700-799         865
1600-1699       819
1400-1499       783
1300-1399       728
400-499         598
600-699         543
1800-1899       522
1900-1999       419
1700-1799       415
300-399         407
100-199         292
200-299         271
2000-2099       117
0-99             90
2400-2499        30
2800-2899        26
2100-2199        18
2300-2399        18
5000-5099        14
3100-3199        14
2500-2599        12
3000-3099        12
8200-8299        11
               ...
16200-16299       1
33400-33499       1
12100-12199       1
14500-14599       1
21600-21699       1
17300-17399       1
22900-22999       1
13000-13099       1
16800-16899       1
15800-15899       1
13100-13199       1
18200-18299       1
13600-13699       1
14600-14699       1
18400-18499       1
14200-14299       1
15200-15299       1
4100-4199         1
18700-18799       1
11500-11599       1
15400-15499       1
11100-11199       1
16700-16799       1
16400-16499       1
13900-13999       1
13800-13899       1
10800-10899       1
12000-12099       1
13400-13499       1
8800-8899         1
Name: BlockRange, Length: 161, dtype: int64

In [11]:
ran = df.BlockRange == '1.1103e+006-1.1104e+006'

In [12]:
df[ran]

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2017-09-01 21:00:00,1A10,1.1103e+006-1.1104e+006,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,21,1,Friday,Sep,2017

In [13]:
av = df.StreetName == 'AVENIDA DE LAS AMERICAS'

In [14]:
df[av]

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01 00:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010
2010-01-02 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,14,2,Saturday,Jan,2010
2010-02-22 19:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial parking lot/garage,1,19,22,Monday,Feb,2010
2010-02-28 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial parking lot/garage,1,9,28,Sunday,Feb,2010
2010-03-27 13:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,department/discount store,1,13,27,Saturday,Mar,2010
2010-03-28 10:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other/unknown,1,10,28,Sunday,Mar,2010
2010-04-03 11:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,"parks & recreation, zoo, swim pool",1,11,3,Saturday,Apr,2010
2010-05-01 15:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other parking lot,1,15,1,Saturday,May,2010
2010-05-02 11:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other parking lot,1,11,2,Sunday,May,2010
2010-06-08 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,14,8,Tuesday,Jun,2010
2010-06-12 10:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other parking lot,1,10,12,Saturday,Jun,2010
2010-07-07 18:00:00,1A10,600-699,AVENIDA DE LAS AMERICAS,Auto Theft,commercial parking lot/garage,1,18,7,Wednesday,Jul,2010
2010-09-04 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other/unknown,1,9,4,Saturday,Sep,2010
2010-09-24 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,road/street/sidewalk,1,14,24,Friday,Sep,2010
2010-09-25 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,hotel/motel parking lot,1,12,25,Saturday,Sep,2010
2010-10-15 11:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial building,1,11,15,Friday,Oct,2010
2010-11-01 10:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial building,1,10,1,Monday,Nov,2010
2010-11-02 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,14,2,Tuesday,Nov,2010
2010-11-03 17:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial building,1,17,3,Wednesday,Nov,2010
2010-11-05 11:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,11,5,Friday,Nov,2010
2010-11-10 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other/unknown,1,12,10,Wednesday,Nov,2010
2010-11-11 10:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,10,11,Thursday,Nov,2010
2010-11-13 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other/unknown,1,9,13,Saturday,Nov,2010
2010-11-13 15:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,specialty store (non-specific),1,15,13,Saturday,Nov,2010
2010-11-14 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,9,14,Sunday,Nov,2010
2010-12-02 19:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Burglary,government/public building,1,19,2,Thursday,Dec,2010
2011-01-09 15:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,15,9,Sunday,Jan,2011
2011-01-15 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other/unknown,1,12,15,Saturday,Jan,2011
2011-02-05 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,12,5,Saturday,Feb,2011
2011-02-05 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,12,5,Saturday,Feb,2011
...,...,...,...,...,...,...,...,...,...,...,...
2014-10-25 20:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,20,25,Saturday,Oct,2014
2014-10-31 15:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,hotel or motel parking lot,1,15,31,Friday,Oct,2014
2014-11-09 19:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,"parks and recreation, zoo, swimming pool",1,19,9,Sunday,Nov,2014
2014-11-30 13:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,13,30,Sunday,Nov,2014
2014-12-14 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,14,14,Sunday,Dec,2014
2015-03-29 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,12,29,Sunday,Mar,2015
2015-04-19 16:00:00,1A10,1200-1299,AVENIDA DE LAS AMERICAS,Theft,"hotel, motel, inn, etc.",1,16,19,Sunday,Apr,2015
2015-04-28 12:00:00,1A10,1200-1299,AVENIDA DE LAS AMERICAS,Theft,hotel or motel parking lot,1,12,28,Tuesday,Apr,2015
2015-05-24 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,9,24,Sunday,May,2015
2015-10-11 17:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,17,11,Sunday,Oct,2015
2015-10-16 14:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,14,16,Friday,Oct,2015
2016-05-15 23:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,23,15,Sunday,May,2016
2016-06-14 13:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,13,14,Tuesday,Jun,2016
2016-06-18 16:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,16,18,Saturday,Jun,2016
2016-08-27 16:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,other parking lot,1,16,27,Saturday,Aug,2016
2016-09-11 10:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,10,11,Sunday,Sep,2016
2016-09-29 09:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,9,29,Thursday,Sep,2016
2016-10-21 22:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,22,21,Friday,Oct,2016
2016-11-04 01:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,1,4,Friday,Nov,2016
2016-11-13 18:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,"other, unknown, or not listed",1,18,13,Sunday,Nov,2016
2016-11-22 13:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,13,22,Tuesday,Nov,2016
2017-02-02 22:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,bar or night club,1,22,2,Thursday,Feb,2017
2017-02-27 15:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,15,27,Monday,Feb,2017
2017-03-06 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,"other, unknown, or not listed",1,12,6,Monday,Mar,2017
2017-03-06 23:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,government or public building,1,23,6,Monday,Mar,2017
2017-04-30 19:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,"other, unknown, or not listed",1,19,30,Sunday,Apr,2017
2017-05-15 12:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,12,15,Monday,May,2017
2017-05-24 20:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,20,24,Wednesday,May,2017
2017-09-01 21:00:00,1A10,1.1103e+006-1.1104e+006,AVENIDA DE LAS AMERICAS,Theft,convention center or exhibit halls,1,21,1,Friday,Sep,2017
2017-09-07 17:00:00,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,commercial building,1,17,7,Thursday,Sep,2017

In [15]:
df.BlockRange[df.BlockRange == '1.1103e+006-1.1104e+006']= '1000-1099'

In [16]:
df[ran].BlockRange

Date_Hour
2017-09-01 21:00:00    1000-1099
Name: BlockRange, dtype: object

In [17]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year
Date_Hour,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010

In [18]:
df['block'] = gf.block_split(df)

In [19]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block
Date_Hour,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050

## Create full addres col

In [20]:
df['address']  = df[['block', 'StreetName']].apply(lambda x: ' '.join(x), axis=1)

In [21]:
df.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address
Date_Hour,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 14978 entries, 2010-01-01 00:00:00 to 2017-12-31 22:00:00
Data columns (total 13 columns):
Beat           14978 non-null object
BlockRange     14978 non-null object
StreetName     14978 non-null object
OffenseType    14978 non-null object
Premise        14978 non-null object
NumOffenses    14978 non-null int64
Hour           14978 non-null int64
day            14978 non-null int64
weekday        14978 non-null object
month          14978 non-null object
year           14978 non-null int64
block          14978 non-null object
address        14978 non-null object
dtypes: int64(4), object(9)
memory usage: 2.2+ MB

# get full lat long and address from google

In [23]:
df_4000 = df.iloc[:4000].copy()
df_8000 = df.iloc[4000:8000].copy()
df_12000 = df.iloc[8000:12000].copy()
df_14978  = df.iloc[12000:].copy()

## Test

In [24]:
df_20 = df.iloc[:20].copy()
df_20['tup_add'] = df_20['address'].apply(gf.gm_geocode,args=(API_KEY,))
df_20.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ..."
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN,"[{'address_components': [{'long_name': '450', ..."
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',..."

In [25]:
tt = df_20.tup_add

In [29]:
tt[4].to_json(orient='split')

'{"name":"tup_add","index":[4],"data":[{"address_components":[{"long_name":"1050","short_name":"1050","types":["street_number"]},{"long_name":"Avenida De Las Americas","short_name":"Avenida De Las Americas","types":["route"]},{"long_name":"Downtown","short_name":"Downtown","types":["neighborhood","political"]},{"long_name":"Houston","short_name":"Houston","types":["locality","political"]},{"long_name":"Harris County","short_name":"Harris County","types":["administrative_area_level_2","political"]},{"long_name":"Texas","short_name":"TX","types":["administrative_area_level_1","political"]},{"long_name":"United States","short_name":"US","types":["country","political"]},{"long_name":"77010","short_name":"77010","types":["postal_code"]}],"formatted_address":"1050 Avenida De Las Americas, Houston, TX 77010, USA","geometry":{"location":{"lat":29.7520152,"lng":-95.359181},"location_type":"RANGE_INTERPOLATED","viewport":{"northeast":{"lat":29.7533641803,"lng":-95.3578320197},"southwest":{"lat":29.7506662197,"lng":-95.3605299803}}},"place_id":"EjQxMDUwIEF2ZW5pZGEgRGUgTGFzIEFtZXJpY2FzLCBIb3VzdG9uLCBUWCA3NzAxMCwgVVNBIhsSGQoUChIJeb1WQyK_QIYRDjCAfIqMDAcQmgg","types":["street_address"]}]}'

## Attempt

In [30]:
df_4000.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4000 entries, 2010-01-01 00:00:00 to 2012-01-16 12:00:00
Data columns (total 13 columns):
Beat           4000 non-null object
BlockRange     4000 non-null object
StreetName     4000 non-null object
OffenseType    4000 non-null object
Premise        4000 non-null object
NumOffenses    4000 non-null int64
Hour           4000 non-null int64
day            4000 non-null int64
weekday        4000 non-null object
month          4000 non-null object
year           4000 non-null int64
block          4000 non-null object
address        4000 non-null object
dtypes: int64(4), object(9)
memory usage: 437.5+ KB

In [31]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_4000['tup_add'] = df_4000['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))

start:16:16:11
end:16:41:44

In [33]:
df_4000.head(2)

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ..."
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',..."

In [34]:
len(df_4000[df_4000.tup_add.isnull()])
df_4000.to_csv('crime_data_clean/crime_1A10_10_17df_4000.csv')

In [35]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_8000['tup_add'] = df_8000['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))

start:16:54:21
end:17:19:00

In [36]:
print(len(df_8000[df_8000.tup_add.isnull()]))

df_8000.to_csv('crime_data_clean/crime_1A10_10_17df_8000.csv')

0

## split df_1200 into 4 parts

In [40]:
df_12000.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address
Date_Hour,,,,,,,,,,,,,
2014-05-08 00:00:00,1A10,1800-1899,RUIZ,Theft,residence/house,1,0,8,Thursday,May,2014,1850,1850 RUIZ
2014-05-08 13:00:00,1A10,1000-1099,FANNIN,Theft,commercial building,1,13,8,Thursday,May,2014,1050,1050 FANNIN
2014-05-08 18:00:00,1A10,600-699,LAMAR,Aggravated Assault,road/street/sidewalk,1,18,8,Thursday,May,2014,650,650 LAMAR
2014-05-09 04:00:00,1A10,900-999,MAIN,Theft,clothing store,1,4,9,Friday,May,2014,950,950 MAIN
2014-05-09 10:00:00,1A10,9400-9499,SAM HOUSTON,Theft,no label,1,10,9,Friday,May,2014,9450,9450 SAM HOUSTON

In [49]:
df_p1 = df_12000.iloc[:1000].copy()
df_p2 = df_12000.iloc[1000:2000].copy()
df_p3 = df_12000.iloc[2000:3000].copy()
df_p4 = df_12000.iloc[3000:].copy()

In [50]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_p1['tup_add'] = df_p1['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))
df_p1.to_csv('crime_data_clean/crime_1A10_10_17df_p1.csv')

start:18:45:27
end:18:54:01

In [51]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_p2['tup_add'] = df_p2['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))
df_p2.to_csv('crime_data_clean/crime_1A10_10_17df_p2.csv')

start:18:55:03
end:19:01:08

In [52]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_p3['tup_add'] = df_p3['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))
df_p3.to_csv('crime_data_clean/crime_1A10_10_17df_p3.csv')

start:19:01:19
end:19:07:07

In [54]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_p4['tup_add'] = df_p4['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))
df_p4.to_csv('crime_data_clean/crime_1A10_10_17df_p4.csv')

start:19:08:58
end:19:15:43

In [55]:
df_12000_merge = pd.concat([df_p1,df_p2,df_p3,df_p4])

In [56]:
df_12000_merge.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2014-05-08 00:00:00,1A10,1800-1899,RUIZ,Theft,residence/house,1,0,8,Thursday,May,2014,1850,1850 RUIZ,"[{'address_components': [{'long_name': '1850',..."
2014-05-08 13:00:00,1A10,1000-1099,FANNIN,Theft,commercial building,1,13,8,Thursday,May,2014,1050,1050 FANNIN,"[{'address_components': [{'long_name': '1050',..."
2014-05-08 18:00:00,1A10,600-699,LAMAR,Aggravated Assault,road/street/sidewalk,1,18,8,Thursday,May,2014,650,650 LAMAR,"[{'address_components': [{'long_name': '650', ..."
2014-05-09 04:00:00,1A10,900-999,MAIN,Theft,clothing store,1,4,9,Friday,May,2014,950,950 MAIN,"[{'address_components': [{'long_name': '950', ..."
2014-05-09 10:00:00,1A10,9400-9499,SAM HOUSTON,Theft,no label,1,10,9,Friday,May,2014,9450,9450 SAM HOUSTON,"[{'address_components': [{'long_name': '9450',..."

In [57]:
df_12000_merge.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4000 entries, 2014-05-08 00:00:00 to 2016-04-28 00:00:00
Data columns (total 14 columns):
Beat           4000 non-null object
BlockRange     4000 non-null object
StreetName     4000 non-null object
OffenseType    4000 non-null object
Premise        4000 non-null object
NumOffenses    4000 non-null int64
Hour           4000 non-null int64
day            4000 non-null int64
weekday        4000 non-null object
month          4000 non-null object
year           4000 non-null int64
block          4000 non-null object
address        4000 non-null object
tup_add        4000 non-null object
dtypes: int64(4), object(10)
memory usage: 468.8+ KB

In [37]:
# bf = dt.datetime.now().time().strftime("%X")
# print('start:{}'.format(bf))
# df_12000['tup_add'] = df_12000['address'].apply(gf.gm_geocode,args=(API_KEY,))

# af = dt.datetime.now().time().strftime("%X")
# print('end:{}'.format(af))

start:17:19:21

KeyboardInterrupt:

In [ ]:
print(len(df_12000[df_8000.tup_add.isnull()]))
df_12000.to_csv('crime_data_clean/crime_1A10_10_17df_12000.csv')

In [38]:
bf = dt.datetime.now().time().strftime("%X")
print('start:{}'.format(bf))
df_14978['tup_add'] = df_14978['address'].apply(gf.gm_geocode,args=(API_KEY,))

af = dt.datetime.now().time().strftime("%X")
print('end:{}'.format(af))

start:18:13:22
end:18:38:36

In [53]:
print(len(df_14978[df_14978.tup_add.isnull()]))
df_14978.to_csv('crime_data_clean/crime_1A10_10_17df_14978.csv')

0

## Concat all

In [58]:
df_final = pd.concat([df_4000,df_8000,df_12000_merge,df_14978])

In [59]:
df_final.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ..."
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN,"[{'address_components': [{'long_name': '450', ..."
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',..."

In [60]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 14978 entries, 2010-01-01 00:00:00 to 2017-12-31 22:00:00
Data columns (total 14 columns):
Beat           14978 non-null object
BlockRange     14978 non-null object
StreetName     14978 non-null object
OffenseType    14978 non-null object
Premise        14978 non-null object
NumOffenses    14978 non-null int64
Hour           14978 non-null int64
day            14978 non-null int64
weekday        14978 non-null object
month          14978 non-null object
year           14978 non-null int64
block          14978 non-null object
address        14978 non-null object
tup_add        14978 non-null object
dtypes: int64(4), object(10)
memory usage: 1.7+ MB

In [61]:
df_final.to_csv('crime_data_clean/crime_1A10_10_17ADD.csv')

In [62]:
df_final.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ..."
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN,"[{'address_components': [{'long_name': '450', ..."
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',..."

In [ ]:
new_add = df.tup_add.apply(pd.Series,index=['lat_lon','full_address'])

In [ ]:
new_add.head()

In [ ]:
df = df.join(new_add)

In [ ]:
df.drop(['block','BlockRange','StreetName','address','tup_add','address','tup_add',],axis=1,inplace=True)

In [ ]:
#df.drop('block', axis=1,inplace=True)

In [66]:
df_final.head()

,Beat,BlockRange,StreetName,OffenseType,Premise,NumOffenses,Hour,day,weekday,month,year,block,address,tup_add
Date_Hour,,,,,,,,,,,,,,
2010-01-01,1A10,300-399,HAMILTON,Auto Theft,bar/night club parking lot,1,0,1,Friday,Jan,2010,350,350 HAMILTON,"[{'address_components': [{'long_name': '350', ..."
2010-01-01,1A10,1200-1299,CAROLINE,Theft,bar/night club,1,0,1,Friday,Jan,2010,1250,1250 CAROLINE,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,400-499,MAIN,Burglary,office building,1,0,1,Friday,Jan,2010,450,450 MAIN,"[{'address_components': [{'long_name': '450', ..."
2010-01-01,1A10,1200-1299,TRAVIS,Theft,other/unknown,1,0,1,Friday,Jan,2010,1250,1250 TRAVIS,"[{'address_components': [{'long_name': '1250',..."
2010-01-01,1A10,1000-1099,AVENIDA DE LAS AMERICAS,Theft,convention center/exhibit halls,1,0,1,Friday,Jan,2010,1050,1050 AVENIDA DE LAS AMERICAS,"[{'address_components': [{'long_name': '1050',..."

In [65]:
df_final.to_csv('crime_data_clean/crime_1A10_10_17FINAL.csv')